#!/bin/bash
for i in "$@";
    do if [ -d "$i" ] ; then
        if [ "$(ls -dlO "$i" | grep schg,uchg)" == "" ]; then
            sudo chflags uchg "$i" && sudo chflags schg "$i"
        else
            sudo chflags nouchg "$i" && sudo chflags noschg "$i"
        fi;
    elif [ -f "$i" ]; then
        if [ "$(ls -lO "$i" | grep schg,uchg)" == "" ]; then
            sudo chflags uchg "$i" && sudo chflags schg "$i"
        else
            sudo chflags nouchg "$i" && sudo chflags noschg "$i"
        fi;
    else
        echo "No valid argument input.";
        exit 1
    fi;
done