cask "font-tupo-vyaz" do
  version "1.000"
  sha256 :no_check # different sha256 generated by API

  url "https://api.paratype.com/api/editions/ofl/download/65273",
      referer: "https://www.paratype.com/"
  name "Tupo Vyaz"
  homepage "https://www.paratype.com/fonts/pt/tupo-vyaz/"

  font "PT/PT/Tupo-Vyaz/tupo-vyaz_vf.ttf"
end
