cask "font-pt-sans" do
  version "2.005,2.006"
  sha256 :no_check # different sha256 generated by API

  url "https://api.paratype.com/api/editions/ofl/download/52212",
      referer: "https://www.paratype.com/"
  name "PT Sans"
  homepage "https://www.paratype.com/fonts/pt/pt-sans"

  depends_on formula: "fonttools"

  font "pt-sans.ttc"

  preflight do
    system_command "/bin/bash", args: [
      "-c", <<~SHELL
        ls '#{staged_path}/PT/PT/PT-Sans/'*.ttf \
        | awk '{print "\\"" $0 "\\""}' \
        | xargs '#{HOMEBREW_PREFIX}/opt/fonttools/bin/fonttools' ttLib \
        -o '#{staged_path}/pt-sans.ttc'
      SHELL
    ]
  end
end
