cask "font-pt-mono" do
  version "1.003"
  sha256 :no_check # different sha256 generated by API

  url "https://api.paratype.com/api/editions/ofl/download/52218",
      referer: "https://www.paratype.com/"
  name "PT Mono"
  homepage "https://www.paratype.com/fonts/pt/pt-mono"

  depends_on formula: "fonttools"

  font "pt-mono.ttc"

  preflight do
    system_command "/bin/bash", args: [
      "-c", <<~SHELL
        ls '#{staged_path}/PT/PT/PT-Mono/'*.ttf \
        | awk '{print "\\"" $0 "\\""}' \
        | xargs '#{HOMEBREW_PREFIX}/opt/fonttools/bin/fonttools' ttLib \
        -o '#{staged_path}/pt-mono.ttc'
      SHELL
    ]
  end
end
