cask "font-pt-astra-sans" do
  version "1.003"
  sha256 :no_check # different sha256 generated by API

  url "https://api.paratype.com/api/editions/ofl/download/52180",
      referer: "https://www.paratype.com/"
  name "PT Astra Sans"
  homepage "https://www.paratype.com/fonts/pt/pt-astra-sans"

  depends_on formula: "fonttools"

  font "pt-astra-sans.ttc"

  preflight do
    system_command "/bin/bash", args: [
      "-c", <<~SHELL
        ls '#{staged_path}/PT/PT/PT-Astra-Sans/'*.ttf \
        | awk '{print "\\"" $0 "\\""}' \
        | xargs '#{HOMEBREW_PREFIX}/opt/fonttools/bin/fonttools' ttLib \
        -o '#{staged_path}/pt-astra-sans.ttc'
      SHELL
    ]
  end

  caveats do
    license "https://scripts.sil.org/OFL"
    <<~EOS
      You can preview font information generated by `otfinfo` at:
        #{__dir__}/#{token}.otfinfo
    EOS
  end
end
