cask "font-ink-draft" do
  version "1.00"
  sha256 "aa6590cabcdd26a4429924b11e0847858353345338499a07e54b933954efffc1"

  url "https://font.download/dl/font/ink-draft.zip"
  # url "https://web.archive.org/web/20250731144845/https://font.download/dl/font/ink-draft.zip"
  name "Ink Draft"
  homepage "https://font.download/font/ink-draft"

  font "INKDRAFT.TTF"

  caveats do
    <<~EOS
      # Generated by `otfinfo`
      Family:              Ink Draft
      Subfamily:           Regular
      Full name:           Ink Draft
      PostScript name:     InkDraft
      Version:             Version 1.00
      Unique ID:           Microsoft Ink Draft Regular
      Designer:            Richard Miller
      Designer URL:        http://www.millertype.com
      Manufacturer:        Monotype Imaging Inc.
      Vendor URL:          http://www.monotype.com
      Copyright:           Copyright © 2018 Miller Type Foundry. All rights reserved.
      License Description: Microsoft supplied font. You may use this font to create, display, and print content as permitted by the license terms or terms of use, of the Microsoft product, service, or content in which this font was included. You may only (i) embed this font in content as permitted by the embedding restrictions included in this font; and (ii) temporarily download this font to a printer or other output device to help print content. Any other use is prohibited.
      Permissions:         Editable
    EOS
  end
end
