cask "font-tupo-vyaz" do
  version "1.000"
  sha256 :no_check # different sha256 generated by API

  url "https://api.paratype.com/api/editions/ofl/download/65273",
      referer: "https://www.paratype.com/"
  name "Tupo Vyaz"
  homepage "https://www.paratype.com/fonts/pt/tupo-vyaz/"

  font "tupo-vyaz[wght].ttf"

  preflight do
    FileUtils.mv "#{staged_path}/PT/PT/Tupo-Vyaz/tupo-vyaz_vf.ttf",
                 "#{staged_path}/tupo-vyaz[wght].ttf"
  end

  caveats do
    license "http://scripts.sil.org/OFL"
    <<~EOS
      You can preview font information generated by `otfinfo` at:
        #{__dir__}/#{token}.otfinfo
    EOS
  end
end
