cask "font-pt-serif" do
  version "1.002"
  sha256 :no_check # different sha256 generated by API

  url "https://api.paratype.com/api/editions/ofl/download/52194",
      referer: "https://www.paratype.com/"
  name "PT Serif"
  homepage "https://www.paratype.com/fonts/pt/pt-serif"

  depends_on formula: "fonttools"

  font "pt-serif.ttc"

  preflight do
    system_command "/bin/bash", args: [
      "-c", <<~SHELL
        ls '#{staged_path}/PT/PT/PT-Serif/'*.ttf \
        | awk '{print "\\"" $0 "\\""}' \
        | xargs '#{HOMEBREW_PREFIX}/opt/fonttools/bin/fonttools' ttLib \
        -o '#{staged_path}/pt-serif.ttc'
      SHELL
    ]
  end

  caveats do
    license "https://www.paratype.com/public/pt_openlicense_eng.asp"
    <<~EOS
      You can preview font information generated by `otfinfo` at:
        #{__dir__}/#{token}.otfinfo
    EOS
  end
end
