cask "font-32768-no" do
  version "1.00"
  sha256 "770da400f4142ec7979d95e81cd07a2c04d7ee6a7ba2540fd062d8c9a1fdc345"

  url "https://dl.dafont.com/dl/?f=32768_no"
  name "32768 NO"
  homepage "https://www.dafont.com/32768-no.font"

  font "32768no.ttf"

    caveats do
    <<~EOS
      # Generated by `otfinfo`
      Family:              32768 NO
      Subfamily:           Regular
      Full name:           32768 NO
      PostScript name:     32768NO
      Version:             Version 1.00: 7.25.99 Revision 1
      Unique ID:           Version 1.00: 32768 NO Frog
      Description:
      Created by Tom Murphy 7.

      32768 is my favorite nontrivial power of two. This is kind of like Eye Of The Needle stuff.


      [Divide By Zero] fonts:
      http://fonts.tom7.com/

      Designer:            Tom Murphy 7
      Designer URL:        http://www.andrew.cmu.edu/~twm/
      Manufacturer:        [ Divide By Zero ]
      Vendor URL:          http://fonts.tom7.com/
      Trademark:           32768 NO is Copyright (c) 1999 Tom Murphy 7 of [ Divide By Zero ]
      Copyright:           http://fonts.tom7.com / - 32760 NO Copyright (c) 1999 Tom Murphy 7 - Use for anything, and distribute freely... But don't sell (on CD, for instance!). ImightbeTM@aol.com - 339 Still Hill Rd - Hamden CT 06518.1830 - I never asked for the truth, but you li
      License URL:         http://fonts.tom7.com/legal/
      License Description: Here is the summary of the license for this font, which may be overridden by (most likely very similar) new licenses at the URL below. If you want to do anything with this font you think I might not allow, please see the license URL at the bottom of this document and/or e-mail me.


      NO MONEY must ever exchange hands for this font file, without EXPLICIT WRITTEN PERMISSION from the designer.

      This means you MAY NOT SELL THIS FONT on a font-collection CD, nor singularly nor part of any other type package.

      You may distribute this font file to anyone you want, as long as you do not modify it and do not charge any money or services.

      You can use this font in noncommercial applications and websites freely and without the designer's permission.

      You can use this font to create commercial products or web sites, but when appropriate I'd love for you to send me a complimentary copy of the item you use it in.

      If you distribute or use this font, you may wish to link to the [ Divide By Zero ] web page (though this is not necessary):

      http://fonts.tom7.com/

      For the full license and updates:

      http://fonts.tom7.com/legal/

      Mailing address:

      Tom Murphy 7
      339 Still Hill Rd
      Hamden CT 06518.1830
      USA
      Vendor ID:           Frog
      Permissions:         Installable
    EOS
  end
end
