cask "font-dyspepsia" do
  version "5.002"
  sha256 "d02c8f77464d67c4ce83ac670330f46dd6d2998a6148bcbb12bf84885f1c7e61"

  url "https://dl.dafont.com/dl/?f=dyspepsia"
  name "Dyspepsia"
  homepage "https://www.dafont.com/dyspepsia.font"

  font "Dyspepsia.otf"

    caveats do
    <<~EOS
      # Generated by `otfinfo`
      Family:              Dyspepsia
      Subfamily:           Regular
      Full name:           Dyspepsia-Regular
      PostScript name:     Dyspepsia-Regular
      Preferred family:    Dyspepsia
      Preferred subfamily: Regular
      Version:             Version 5.002
      Unique ID:           5.001;TYPO;Dyspepsia-Regular
      Description:         This font has been released under a “no rights reserved” Creative Commons Zero license.  Please don’t ask permission to do anything with these fonts. Whatever you want to do with this font, the answer will be yes. Please read about the CC0 Public Domain license before contacting me. https://creativecommons.org/publicdomain/zero/1.0/ To the extent possible under law, Raymond Larabie has waived all copyright and related or neighboring rights to this font. This work is published from Japan.
      Designer:            Raymond Larabie
      Designer URL:        https://typodermicfonts.com
      Manufacturer:        Raymond Larabie
      Copyright:           Released in 2020 under CC0 license. No rights reserved.
      License URL:         https://creativecommons.org/publicdomain/zero/1.0/
      Vendor ID:           TYPO
      Permissions:         Installable
    EOS
  end
end
