cask "font-nadall" do
  version "1.0"
  sha256 "3b3e676b7b3cce821f48feb858a050ff2cf189b010596ff0bcf7afb69b766706"

  url "https://dl.dafont.com/dl/?f=nadall"
  name "Nadall"
  homepage "https://www.dafont.com/nadall.font"

  font "NADALL.TTF"

  caveats do
    <<~EOS
      # Generated by `otfinfo`
      Family:              Nadall
      Subfamily:           Normal
      Full name:           Nadall
      PostScript name:     Nadall
      Version:             1.0 Mon Oct 18 00:51:56 1993
      Unique ID:           Grun:Nadall
      Copyright:           Nadall copyright (c) 1993, Eric Grunin
      Vendor ID:           Alts
      Permissions:         Unknown (1)
    EOS
  end
end
