cask "font-a-charming-font" do
  version "1.03"
  sha256 "8ae8664c80ccb9bc0bce849a35310e29cd1f09b27a686a2d512c89291a458604"

  url "https://dl.dafont.com/dl/?f=a_charming_font"
  name "A Charming Font"
  homepage "https://www.dafont.com/a-charming-font.font"

  depends_on formula: "fonttools"

  font "Achaf.ttc"

  preflight do
    system_command "/bin/bash", args: [
      "-c", <<~SHELL
        ls '#{staged_path}/'*.ttf \
        | awk '{print "\\"" $0 "\\""}' \
        | xargs '#{HOMEBREW_PREFIX}/opt/fonttools/bin/fonttools' ttLib \
        -o '#{staged_path}/Achaf.ttc'
      SHELL
    ]
  end

  caveats do
    <<~EOS
      # Generated by `otfinfo`
      Family:                 A Charming Font         A Charming Font Italic
                              Expanded
      Subfamily:              Regular                 Regular
      Full name:              A Charming Font         A Charming Font Italic
                              Expanded
      PostScript name:        ACharmingFontExpanded   ACharmingFontItalic
      Version:                1.03                    1.03
      Unique ID:              A Charming Font         A Charming Font
      Copyright:              ©GeM / A. Höfeld
      Vendor ID:              Gem
      Permissions:            Installable

      Family:                 A Charming Font         A Charming Font
                              Leftleaning
      Subfamily:              Regular                 Regular
      Full name:              A Charming Font         A Charming Font
                              Leftleaning
      PostScript name:        A                       ACharmingFont
                              CharmingFontLeftleaning
      Version:                1.03                    1.03
      Unique ID:              A Charming Font         A Charming Font
      Copyright:              ©GeM / A. Höfeld
      Vendor ID:              Gem
      Permissions:            Installable

      Family:                 A Charming Font Outline A Charming Font
                                                      Superexpanded
      Subfamily:              Regular                 Regular
      Full name:              A Charming Font Outline A Charming Font
                                                      Superexpanded
      PostScript name:        ACharmingFontOutline    ACh
                                                      armingFontSuperexpanded
      Version:                1.03                    1.03
      Unique ID:              A Charming Font         A Charming Font
      Copyright:              ©GeM / A. Höfeld
      Vendor ID:              Gem
      Permissions:            Installable
    EOS
  end
end
