cask "font-ink-journal" do
  version "1.00"
  sha256 "56f6f77ca9f2caacbbef169d3ec2b0a4d6506d3995a90dffbdd45152e36a3d7a"

  url "https://www.cufonfonts.com/get/font/download/1f7a643cc441a9b17da0d7be5a898f94"
  # url "https://web.archive.org/web/20250731124547/https://www.cufonfonts.com/get/font/download/1f7a643cc441a9b17da0d7be5a898f94"
  name "Ink Journal"
  homepage "https://www.cufonfonts.com/font/ink-journal"

  font "INKJOURNAL.TTF"

  caveats do
    <<~EOS
      # Generated by `otfinfo`
      Family:              Ink Journal
      Subfamily:           Regular
      Full name:           Ink Journal
      PostScript name:     InkJournal
      Version:             Version 1.00
      Unique ID:           Microsoft Ink Journal Regular
      Designer:            Jim Ford
      Designer URL:        http://www.monotype.com
      Manufacturer:        Monotype Imaging, Inc.
      Vendor URL:          http://www.monotype.com
      Copyright:           Copyright © 2009-2018 Monotype Imaging Inc. All rights reserved.
      License Description: Microsoft supplied font. You may use this font to create, display, and print content as permitted by the license terms or terms of use, of the Microsoft product, service, or content in which this font was included. You may only (i) embed this font in content as permitted by the embedding restrictions included in this font; and (ii) temporarily download this font to a printer or other output device to help print content. Any other use is prohibited.
      Vendor ID:           MONO
      Permissions:         Editable
    EOS
  end
end
