cask "font-old-english-att" do
  version "1.0"
  sha256 "f83a27f84736e8ed33d41d2ad8dac39a289f0ce3fd4e9a3ea6e065d63bfb7791"

  url "https://www.cufonfonts.com/get/font/download/85b319a27718032bfa84d7c65602502e"
  # url "https://web.archive.org/web/20250731143541/https://www.cufonfonts.com/get/font/download/85b319a27718032bfa84d7c65602502e"
  name "Old English ATT"
  homepage "https://www.cufonfonts.com/font/old-english-att"

  font "OLDENGLI.TTF"

  caveats do
    <<~EOS
      # Generated by `otfinfo`
      Family:              Old English ATT
      Subfamily:           Regular
      Full name:           Old English ATT
      PostScript name:     OldEnglishATT
      Version:             1.0
      Unique ID:           Agfa Corporation: Old English ATT
      Copyright:           Copyright © 1991 by Agfa Corporation. All rights reserved.
      Vendor ID:           AGFA
      Permissions:         Unknown (6)
    EOS
  end
end
