cask "ml-0013-risers" do
  version "5bf8f878ad74887fe3dac1de764a7db5-12"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0013_risers/ml_0013_risers.aar"
  name "TransitionEffects"
  desc "SoundEffectsPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0013_risers/ml_0013_risers.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0013_risers.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "～/Music/Logic Pro Library.bundle/Apple Loops/Transition Effects",
    "～/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0013_risers.plist",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/00.8s Drum Booth One-OST.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/03 Plate Reverbs/0.7s_Drum Plate.SDIR",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Liquid Light.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Liquid Light.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Liquid Light.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Liquid Light.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Adrenaline Rush.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Adrenaline Rush.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Adrenaline Rush.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Adrenaline Rush.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Alien Chorus.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Alien Chorus.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Alien Chorus.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Alien Chorus.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Another Dimension.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Another Dimension.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Another Dimension.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Another Dimension.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Chopped Riser.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Chopped Riser.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Chopped Riser.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Chopped Riser.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Cymbal Swell.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Cymbal Swell.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Cymbal Swell.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Cymbal Swell.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Echolocation.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Echolocation.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Echolocation.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Echolocation.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Encoded Transmission.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Encoded Transmission.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Encoded Transmission.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Encoded Transmission.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Forever Riser.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Forever Riser.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Forever Riser.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Forever Riser.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Fuel Cells.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Fuel Cells.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Fuel Cells.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Fuel Cells.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Howling Riser.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Howling Riser.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Howling Riser.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Howling Riser.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Light Speed.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Light Speed.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Light Speed.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Light Speed.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Ludicrous Speed.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Ludicrous Speed.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Ludicrous Speed.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Ludicrous Speed.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Motoriser.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Motoriser.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Motoriser.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Motoriser.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Particle Accelerator.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Particle Accelerator.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Particle Accelerator.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Particle Accelerator.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Plasma Drop.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Plasma Drop.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Plasma Drop.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Plasma Drop.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Pole Position.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Pole Position.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Pole Position.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Pole Position.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Ridiculous Speed.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Ridiculous Speed.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Ridiculous Speed.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Ridiculous Speed.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Trill Riser.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Trill Riser.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Trill Riser.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Trill Riser.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Unison Riser.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Unison Riser.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Unison Riser.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Unison Riser.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Vowel Disintegrator.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Vowel Disintegrator.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Vowel Disintegrator.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Vowel Disintegrator.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Adrenaline Rush.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Alien Chorus.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Another Dimension.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Chopped Riser.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Cymbal Swell.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Echolocation.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Encoded Transmission.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Forever Riser.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Fuel Cells.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Howling Riser.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Light Speed.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Liquid Light.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Ludicrous Speed.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Motoriser.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Particle Accelerator.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Plasma Drop.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Pole Position.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Ridiculous Speed.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Trill Riser.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Unison Riser.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Vowel Disintegrator.acp",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Elevated Beats.logicx/Alternatives/000/DisplayState.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Elevated Beats.logicx/Alternatives/000/DisplayStateArchive",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Elevated Beats.logicx/Alternatives/000/MetaData.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Elevated Beats.logicx/Alternatives/000/ProjectData",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Elevated Beats.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Elevated Beats.logicx/Contents/Resources/template.tif",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Elevated Beats.logicx/Contents/Resources/template_ios.png",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Elevated Beats.logicx/Resources/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Elevated Beats.logicx/Resources/ProjectInformation.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Rising Higher.logicx/Alternatives/000/DisplayState.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Rising Higher.logicx/Alternatives/000/DisplayStateArchive",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Rising Higher.logicx/Alternatives/000/MetaData.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Rising Higher.logicx/Alternatives/000/ProjectData",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Rising Higher.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Rising Higher.logicx/Contents/Resources/template.tif",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Rising Higher.logicx/Contents/Resources/template_ios.png",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Rising Higher.logicx/Resources/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Rising Higher.logicx/Resources/ProjectInformation.plist",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Single Samples/Closed Analog Hi Hat.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/46 OpenHH 4-S.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/49 Crash1 4-S.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/53 Cup1 2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/53 Cup1 3-S.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Alien Ship Scan C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Beta Piercer C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Cherry Improv Phrases 1 0045-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Cherry Improv Phrases 1 0055-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Cinematic Drum Hit 06-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Dragon Drone C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Drone FX Bmetal Orch C3-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Eleanor Improv Phrases 1 0042-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Finger Snap Ambience-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Light Mech C3-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Radio Breakthrough-ASF_1.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Radio Breakthrough-ASF_2.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Reactor Room C3-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/The Dream C3-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Tom Sound Word-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Trompong 2-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Warping Tunnel C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Synth/Custom/Formant Sweep Slow C2.caf",
  ]
end
