cask "ml-0043-sessionplayersdrummeracoustic" do
  version "6d65058a213743dcd5b8734696d27cae-337"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0043_sessionplayersdrummeracoustic/ml_0043_sessionplayersdrummeracoustic.aar"
  name "AcousticDrums"
  desc "SessionPlayerPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0043_sessionplayersdrummeracoustic/ml_0043_sessionplayersdrummeracoustic.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0043_sessionplayersdrummeracoustic.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/60s Songwriter Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/60s Songwriter Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/60s Songwriter Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/60s Songwriter Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/60s Songwriter Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Always the Same Bridge Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Always the Same Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Always the Same Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Brighter Illusion Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Brighter Illusion Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/By the Fire Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Candy Coupe Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Central Park Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Changing Guard Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Concrete Below Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Chorus Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Intro Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Verse Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desperate Love Bridge Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desperate Love Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desperate Love Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Dreams of Neon Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Echo Chamber Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Echo Chamber Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/End of the Road Bridge Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/End of the Road Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/End of the Road Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Experimental Songwriter Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Experimental Songwriter Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Experimental Songwriter Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Experimental Songwriter Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Experimental Songwriter Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Falling Fast Bridge Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Falling Fast Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Falling Fast Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Flying Beyond Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Forever Disco Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Friday Night Drive Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Friday Night Drive Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funk Rock Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funk Rock Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funk Rock Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funk Rock Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funk Rock Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funk Rock Drums 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Drums 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Drums 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Drums 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Galactic Guide Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Garage Rock Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Garage Rock Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Garage Rock Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Garage Rock Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Garage Rock Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Garage Rock Drums 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Gliding Away Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Gliding Away Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Hard Rock Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Hard Rock Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Hard Rock Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Drums 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Drums 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Drums 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Drums 09.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Pop Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Pop Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Pop Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Pop Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Pop Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Rock Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Rock Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Rock Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Rock Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Rock Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Rock Drums 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Inline Skates Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Just What You Needed Bridge Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Just What You Needed Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Just What You Needed Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lo-Fi Summer Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lo-Fi Summer Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lost and Found Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lost and Found Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Mean Streets Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern Motown Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern Motown Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern Motown Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern Motown Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern Motown Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern R&B Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern R&B Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern R&B Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern R&B Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern R&B Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern R&B Drums 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern R&B Drums 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Drums 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Drums 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Drums 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Drums 09.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Notes on Top Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Notes on Top Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Paint it Blue Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Paint it Blue Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Brush Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Brush Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Brush Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Brush Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Brush Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Rock Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Rock Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Rock Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Rock Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Songwriter Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Songwriter Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Songwriter Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Songwriter Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Psychedelic Rock Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Psychedelic Rock Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Psychedelic Rock Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Psychedelic Rock Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Punk Rock Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Punk Rock Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Punk Rock Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Punk Rock Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Punk Rock Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Punk Rock Drums 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Retro Rock Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Retro Rock Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Retro Rock Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Retro Rock Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Retro Rock Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Retro Rock Drums 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Brush Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Brush Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Brush Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Brush Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Brush Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Brush Drums 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Brush Drums 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Brush Drums 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Songwriter Drummer - Edgewood.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Songwriter Drums 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Songwriter Drums 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Songwriter Drums 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Songwriter Drums 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Songwriter Drums 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sixties Nostalgia Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/SoCal Sun Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Summertime Breeze Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Summertime Breeze Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Switching Lights Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Turned Around Bridge Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Turned Around Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Turned Around Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Twilight Rising Bridge Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Twilight Rising Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Twilight Rising Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Velvet Dreams Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Velvet Dreams Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Vision of Beauty Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Vision of Beauty Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Wilted Roses Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Witty Vibes Bridge Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Witty Vibes Chorus Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Witty Vibes Verse Drums.caf",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0043_sessionplayersdrummeracoustic.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Blue Ridge.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Blue Ridge.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Blue Ridge.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Blue Ridge.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Bluebird.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Bluebird.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Bluebird.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Bluebird.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Brooklyn.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Brooklyn.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Brooklyn.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Brooklyn.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Detroit Garage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Detroit Garage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Detroit Garage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Detroit Garage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/East Bay.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/East Bay.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/East Bay.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/East Bay.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Four on the Floor.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Four on the Floor.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Four on the Floor.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Four on the Floor.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Heavy.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Heavy.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Heavy.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Heavy.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Liverpool.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Liverpool.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Liverpool.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Liverpool.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Manchester.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Manchester.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Manchester.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Manchester.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Motown Revisited.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Motown Revisited.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Motown Revisited.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Motown Revisited.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Neo Soul.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Neo Soul.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Neo Soul.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Neo Soul.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Portland.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Portland.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Portland.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Portland.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Retro Rock.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Retro Rock.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Retro Rock.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Retro Rock.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Roots.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Roots.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Roots.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Roots.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Scientific Method.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Scientific Method.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Scientific Method.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Scientific Method.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Slow Jam.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Slow Jam.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Slow Jam.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Slow Jam.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Smash.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Smash.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Smash.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Smash.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/SoCal.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/SoCal.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/SoCal.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/SoCal.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Speakeasy.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Speakeasy.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Speakeasy.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Speakeasy.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Sunset.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Sunset.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Sunset.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/Sunset.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Four on the Floor.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Four on the Floor.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Four on the Floor.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Four on the Floor.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Liverpool.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Liverpool.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Liverpool.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Liverpool.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Motown Revisited.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Motown Revisited.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Motown Revisited.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Motown Revisited.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Neo Soul.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Neo Soul.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Neo Soul.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Neo Soul.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Roots.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Roots.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Roots.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Roots.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Sunset.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Sunset.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Sunset.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/01 Kicks/Kick - Sunset.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Bluebird.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Bluebird.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Bluebird.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Bluebird.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Four on the Floor.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Four on the Floor.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Four on the Floor.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Four on the Floor.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Liverpool.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Liverpool.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Liverpool.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Liverpool.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Motown Revisited.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Motown Revisited.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Motown Revisited.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Motown Revisited.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Neo Soul.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Neo Soul.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Neo Soul.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Neo Soul.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Roots.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Roots.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Roots.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Roots.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Sunset.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Sunset.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Sunset.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/02 Snares/Snare - Sunset.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Detroit Garage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Detroit Garage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Detroit Garage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Detroit Garage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Heavy.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Heavy.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Heavy.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Heavy.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Manchester.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Manchester.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Manchester.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Manchester.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Neo Soul.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Neo Soul.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Neo Soul.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Neo Soul.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Slow Jam.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Slow Jam.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Slow Jam.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Slow Jam.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Sunset.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Sunset.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Sunset.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Sunset.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Manchester.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Manchester.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Manchester.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Manchester.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Neo Soul.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Neo Soul.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Neo Soul.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Neo Soul.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Sunset.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Sunset.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Sunset.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Sunset.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - Brooklyn.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - Brooklyn.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - Brooklyn.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - Brooklyn.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - East Bay.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - East Bay.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - East Bay.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - East Bay.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - Neo Soul.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - Neo Soul.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - Neo Soul.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - Neo Soul.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - Roots.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - Roots.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - Roots.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash - Roots.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Bluebird.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Bluebird.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Bluebird.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Bluebird.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Manchester.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Manchester.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Manchester.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Manchester.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Roots.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Roots.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Roots.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Roots.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Slow Jam.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Slow Jam.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Slow Jam.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Crash Stop - Slow Jam.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - East Bay.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - East Bay.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - East Bay.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - East Bay.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Manchester.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Manchester.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Manchester.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Manchester.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Motown Revisited.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Motown Revisited.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Motown Revisited.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Motown Revisited.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Neo Soul.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Neo Soul.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Neo Soul.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Neo Soul.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Sunset.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Sunset.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Sunset.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride - Sunset.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride 1 - Detroit Garage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride 1 - Detroit Garage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride 1 - Detroit Garage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride 1 - Detroit Garage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride 2 - Detroit Garage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride 2 - Detroit Garage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride 2 - Detroit Garage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride 2 - Detroit Garage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride Bell - Brooklyn.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride Bell - Brooklyn.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride Bell - Brooklyn.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/04 Cymbals/Ride Bell - Brooklyn.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Liverpool.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Liverpool.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Liverpool.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Liverpool.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Manchester.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Manchester.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Manchester.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Manchester.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Neo Soul.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Neo Soul.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Neo Soul.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Neo Soul.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Sunset.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Sunset.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Sunset.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom High - Sunset.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Bluebird.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Bluebird.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Bluebird.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Bluebird.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Four on the Floor.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Four on the Floor.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Four on the Floor.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Four on the Floor.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Motown Revisited.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Motown Revisited.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Motown Revisited.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Motown Revisited.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Portland.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Portland.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Portland.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Low - Portland.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Brooklyn.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Brooklyn.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Brooklyn.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Brooklyn.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Four on the Floor.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Four on the Floor.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Four on the Floor.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Four on the Floor.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Motown Revisited.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Motown Revisited.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Motown Revisited.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Motown Revisited.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Slow Jam.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Slow Jam.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Slow Jam.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Acoustic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Slow Jam.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/z02 Stereo Kits v2",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Claps/Stereo",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Cowbell/Stereo",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Shaker/Stereo",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Sticks/Stereo",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Tambourine",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer/Stereo v2",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v1 Claps_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v1 Cowbell_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v1 Shaker_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v1 Sticks_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v1 Tambourine_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v2 Claps_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v2 Shaker_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v2 Tambourine_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v3 Claps_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v3 Shaker_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v3 Tambourine_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v4 Tambourine_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Blue Ridge Kit_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Speakeasy Kit Snare_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Speakeasy Kit_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v2",
  ]
end
