cask "ml-0016-newdisco" do
  version "86ab8e91de4aee56939407b5451d519e-40"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0016_newdisco/ml_0016_newdisco.aar"
  name "Prismatica"
  desc "Nu-DiscoPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0016_newdisco/ml_0016_newdisco.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0016_newdisco.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "～/Music/Logic Pro Library.bundle/Apple Loops/Prismatica",
    "～/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0016_newdisco.plist",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/03 Plate Reverbs/2.2s_Ramp Plate.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/06 Spring Reverbs/2.2s_Old Spring.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/1.0s_Vibes FX.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/02 Halls/1.6s_Short Vocal Hall.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/03 Plate Reverbs/0.7s_Drum Plate.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/06 Speakers/Transistor Radio Speaker 6.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/07 Analog Circuits/Analog Buffer.SDIR",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/BottleModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/Clap1ModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/Clap2ModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/ClaveModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/CongaModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/CrashModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/Delay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/HiHat1ModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/HiHat2ModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/HiHatOpenModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/Kick1ModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/Kick2ModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/LaserDiveModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/Reverb.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/RideModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/ShakerModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/SnapModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/Snare1ModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/Snare2ModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/Snare3ModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/TambourineModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/TomHighModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/TomLowModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/TomMidModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/TomRotoModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Modern Disco.patch/WoodblockModernDisco.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/Clap1Prismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/Clap2Prismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/Clap3Prismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/CrashPrismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/Delay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/DownlifterPrismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/HiHat1Prismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/HiHat2Prismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/HiHat3Prismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/Kick1Prismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/Kick2Prismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/Reverb.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/ReverseCrashPrismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/Snare1Prismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/Snare2Prismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/TomHighPrismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/TomLowPrismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Prismatica.patch/TrapCrashPrismatica.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/ChimesSolaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/Clap1Solaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/Clap2Solaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/CrashSolaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/Delay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/FX1Solaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/FX2Solaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/HiHat1Solaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/HiHat2Solaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/HiHat3Solaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/Kick1Solaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/Kick2Solaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/Reverb.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/ReverseCymbalSolaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/SnapSolaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/Snare1Solaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/TomHighSolaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Solaris.patch/TomLowSolaris.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Reverse Crash - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Reverse Crash - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Reverse Crash - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Reverse Crash - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Reverse Cymbal - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Reverse Cymbal - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Reverse Cymbal - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Reverse Cymbal - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Trap Crash - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Trap Crash - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Trap Crash - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Trap Crash - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Roto - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Roto - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Roto - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Roto - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 3 - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 3 - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 3 - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 3 - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Modern Disco.patch/com.apple.musicapps.intermediate.cache.zxml",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bottle - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bottle - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bottle - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bottle - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Downlifter - Prismatica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Downlifter - Prismatica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Downlifter - Prismatica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Downlifter - Prismatica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX 1 - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX 1 - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX 1 - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX 1 - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX 2 - Solaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX 2 - Solaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX 2 - Solaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX 2 - Solaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Laser Dive - Modern Disco.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Laser Dive - Modern Disco.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Laser Dive - Modern Disco.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Laser Dive - Modern Disco.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Instant Arcade.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Instant Arcade.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Instant Arcade.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Instant Arcade.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Sparkling Stars.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Sparkling Stars.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Sparkling Stars.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Sparkling Stars.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Astro Funk.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Astro Funk.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Astro Funk.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Astro Funk.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Fever Nights.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Fever Nights.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Fever Nights.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Fever Nights.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Fireworks.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Fireworks.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Fireworks.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Fireworks.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Layered Brass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Layered Brass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Layered Brass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Layered Brass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Liquid Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Liquid Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Liquid Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Liquid Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Midnight Fuzz.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Midnight Fuzz.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Midnight Fuzz.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Midnight Fuzz.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Thick Funk.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Thick Funk.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Thick Funk.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Thick Funk.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/80s Fantasy.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/80s Fantasy.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/80s Fantasy.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/80s Fantasy.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Celestial Brass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Celestial Brass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Celestial Brass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Celestial Brass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Late Night Brass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Late Night Brass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Late Night Brass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Late Night Brass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Lunaris.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Lunaris.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Lunaris.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Lunaris.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Neon Dreams.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Neon Dreams.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Neon Dreams.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Neon Dreams.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Shining Lights.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Shining Lights.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Shining Lights.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Shining Lights.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Les Inferno.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Les Inferno.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Les Inferno.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Les Inferno.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Classic Choir.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Classic Choir.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Classic Choir.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Classic Choir.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Floating Sensation.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Floating Sensation.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Floating Sensation.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Floating Sensation.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Plucky Sine.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Plucky Sine.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Plucky Sine.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Plucky Sine.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Instant Arcade.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Sparkling Stars.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Astro Funk.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Fever Nights.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Fireworks.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Layered Brass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Midnight Fuzz.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Thick Funk.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Brass/80s Fantasy.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Brass/Celestial Brass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Brass/Late Night Brass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Neon Dreams.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Shining Lights.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Lead/Les Inferno.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Classic Choir.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Plucked/Floating Sensation.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Plucked/Plucky Sine.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Plucked/Solaris.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Bass/Muted Electric Bass.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Modern Disco Kit.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Prismatica Kit.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Solaris Kit.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Mellotron/Mellotron.exs",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Neon Dreams.logicx/Alternatives/000/DisplayState.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Neon Dreams.logicx/Alternatives/000/DisplayStateArchive",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Neon Dreams.logicx/Alternatives/000/MetaData.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Neon Dreams.logicx/Alternatives/000/ProjectData",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Neon Dreams.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Neon Dreams.logicx/Contents/Resources/template.tif",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Neon Dreams.logicx/Contents/Resources/template_ios.png",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Neon Dreams.logicx/Resources/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Neon Dreams.logicx/Resources/ProjectInformation.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Solaris.logicx/Alternatives/000/DisplayState.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Solaris.logicx/Alternatives/000/DisplayStateArchive",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Solaris.logicx/Alternatives/000/MetaData.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Solaris.logicx/Alternatives/000/ProjectData",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Solaris.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Solaris.logicx/Contents/Resources/template.tif",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Solaris.logicx/Contents/Resources/template_ios.png",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Solaris.logicx/Resources/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Solaris.logicx/Resources/ProjectInformation.plist",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Saw Punch Bass",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Sub Sonic Bass",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Editorial-A.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Editorial-A_1.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Editorial-A_2.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Editorial-A_3.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Real Bass/MMBass Mute/MMBass Mute E0.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Single Samples/Mega Clap 1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Single Samples/Mega Kick 2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 01 C0.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 02 Eb0.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 03 F#0.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 04 A0.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 05 C1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 06 Eb1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 07 F#1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 08 A1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 09 C2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 10 Eb2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 11 F#2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 12 A2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 13 C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 14 Eb3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 15 F#3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 16 A3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 17 C4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 18 Eb4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 19 F#4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 20 A4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 21 C5.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 22 Eb5.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 23 F#5.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 24 A5.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Bottle Hit/Bottle Hit 25 C6.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Cheap Bell",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Musical Box/Musical Box A#3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Musical Box/Musical Box A#4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Musical Box/Musical Box E3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Musical Box/Musical Box E4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Musical Box/Musical Box E5.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Synthetic Mallets/Chrono Chime/Chrono Chime pp C2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Circuit Bent/CB Tand 19.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Real Strings/Group Pizz 2/Group Pizz 2 C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Real Strings/Group Pizz 2/Group Pizz 2 C4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Wet Funk Solo2",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws A#1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws A#2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws A#3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws A#4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws A#5.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws A#6.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws A#7.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws C1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws C2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws C4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws C5.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws C6.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws C7.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws C8.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws E1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws E2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws E3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws E4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws E5.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws E6.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws E7.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws G1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws G2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws G3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws G4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws G5.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws G6.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws/Analog Open Saws G7.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Dream Sweep",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Resonant Sequence",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz A#0.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Editorial-A-A01.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Editorial-B-A01.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Old School Keys-A-A01.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A0.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A5.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C0.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C5.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C6.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb0.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb5.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#0.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#5.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/West Coast Synth Waveforms/FM Drone F2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/West Coast Synth Waveforms/FM Drone F3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 1 A2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 1 A3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 1 C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 1 C4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 1 D#3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 1 D#4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 1 F#2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 1 F#3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 2 A2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 2 A3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 2 C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 2 C4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 2 D#3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 2 D#4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 2 F#2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 2 F#3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 3 A2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 3 A3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 3 C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 3 C4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 3 D#3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 3 D#4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 3 F#2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa/Anastacia Aa 3 F#3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Tom Sustain/Solo Tom Ahh/Solo Tom Ahh A2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Tom Sustain/Solo Tom Ahh/Solo Tom Ahh F3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal Phrases/Anastacia Improv Phrases/Anastacia Improv Phrases1/Anastacia Improv Phrases 1 0016.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Woodwinds/Synth Woodwinds/Blown/Blown 01 C0-A-A01.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Bass/Muted Electric Bass_consolidated.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Modern Disco Kit",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Prismatica Kit",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Solaris Kit",
    "～/Music/Logic Pro Library.bundle/Samples/Keyboard/Mellotron/Mellotron_consolidated.caf",
  ]
end
