cask "ml-0052-irs-surround" do
  version "715358d4b44a0b76f5ae2b37aa92e116-48"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0052_irs_surround/ml_0052_irs_surround.aar"
  name "SurroundIRs"
  desc "ImpulseResponsePack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0052_irs_surround/ml_0052_irs_surround.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0052_irs_surround.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0052_irs_surround.plist",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/00.3s Drum Booth Three-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/00.4s Drum Booth Three-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/00.5s Drum Booth Two-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/00.6s Drum Booth Four-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/00.7s Drum Booth Four-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/00.7s Drum Booth Two-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/00.8s Drum Booth One-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/00.8s Hard Studio-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/00.9s Hard Studio-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.0s Drum Booth One-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.0s Live Stage-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.0s Recording Room-CBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.0s Villa Office-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.0s Villa Office-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.1s Live Stage-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.1s Recording Room-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.1s Villa Bathroom-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.1s Villa Living Room-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.2s Recording Room-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.2s Villa Bathroom-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.3s Villa Parlor-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.3s Villa Parlor-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.4s Villa Living Room-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.6s Villa Kitchen-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.6s Villa Stairway-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.7s Prince Hall Two-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.7s Villa Kitchen-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.7s Villa Stairway-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/01.9s Prince Hall Two-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/02.0s Villa Lobby-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/02.0s Villa Lobby-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/02.1s Prince Hall One-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/02.2s Michaelis Abbey-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/02.3s Archaic Courtroom-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/02.3s Villa Wine Cellar-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/02.4s Prince Hall One-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/02.4s Villa Wine Cellar-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/02.6s Archaic Courtroom-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/02.7s Hansa Studio-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/02.8s Aranno Sacristy-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/02.8s Hansa Studio-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/02.8s Michaelis Abbey-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/02.9s Hansa Studio-CBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/03.0s Chamber Three-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/03.1s Aranno Sacristy-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/03.1s Chamber Four-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/03.1s Michaelis Chapel-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/03.2s Michaelis Chapel-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/03.3s Chamber Four-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/03.4s Chamber Three-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/03.5s Chamber Two-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/03.6s Chamber Two-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/03.6s Grand Hall Three-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/03.6s Grand Hall Three-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/03.8s Grand Hall One-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/03.8s Grand Hall One-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/04.1s Grand Hall Two-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/04.2s Grand Hall Two-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/05.5s Chamber One-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/01 Rooms/05.7s Chamber One-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/02.6s TV Studio-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/02.8s TV Studio-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/03.9s Prince Hall Three-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/03.9s Prince Hall Three-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/04.0s Ulm Chapel-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/04.4s Ulm Chapel-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/05.0s Aranno Chapel-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/05.0s Church Tower-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/05.0s Church Tower-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/05.3s Aranno Chapel-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/05.3s Prison Main Floor-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/05.3s Prison Main Floor-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/05.3s Sound Stage 12-CBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/05.4s Sound Stage-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/05.9s Sound Stage 12-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/06.4s Ancient Church-CBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/06.4s Barracks Two-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/06.5s Ancient Church-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/06.8s Ancient Church-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/06.8s Opulent Ballroom-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/06.9s Opulent Ballroom-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/06.9s Ulm Lobby-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/06.9s Ulm Lobby-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/07.0s Michaelis Nave-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/07.2s Botta Church-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/07.2s Michaelis Nave-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/07.3s Barracks Two-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/07.4s Botta Church-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/07.4s Marble Church-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/07.9s Marble Church-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/08.9s Bottom of Stairs-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/09.0s Bottom of Stairs-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/09.6s Abbey-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/10.1s Barracks One-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/10.3s Church Balcony-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/10.3s Church Balcony-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/10.4s Abbey-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/10.4s Barracks One-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/10.8s Conservatory-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/11.2s Conservatory-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/11.2s Ulm Nave-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/11.9s Ulm Nave-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/12.0s Conservatory-CBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/13.0s Stairs Top Floor-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/13.9s Stairs Top Floor-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/14.3s Stairs Mid Level-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/02 Halls/14.8s Stairs Mid Level-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/03 Indoor Spaces/01.6s Big Cave Entrance-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/03 Indoor Spaces/01.7s Big Cave Entrance-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/03 Indoor Spaces/02.3s Tiled Room-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/03 Indoor Spaces/02.5s Big Cave One-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/03 Indoor Spaces/02.6s Tiled Room-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/03 Indoor Spaces/02.8s Big Cave One-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/03 Indoor Spaces/02.9s Tiled Room-CBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/03 Indoor Spaces/03.3s Big Cave Two-OSD .SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/03 Indoor Spaces/03.5s Big Cave Two-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/03 Indoor Spaces/10.1s Hangar One-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/03 Indoor Spaces/10.4s Hangar One-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/04 Outdoor Spaces/02.0s Amphitheater-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/04 Outdoor Spaces/02.5s Amphitheater-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/04 Outdoor Spaces/08.2s Soccer Field-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/04 Outdoor Spaces/09.0s Soccer Field-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/04 Outdoor Spaces/09.4s Upper Echelons-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/04 Outdoor Spaces/09.4s Upper Echelons-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/05 Warped Spaces/03.2s Prison Small Hall-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/05 Warped Spaces/03.2s Prison Small Hall-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/05 Warped Spaces/03.9s Salt Mine One-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/05 Warped Spaces/03.9s Salt Mine Two-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/05 Warped Spaces/03.9s Salt Mine Two-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/05 Warped Spaces/04.0s Prison Med Hall-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/05 Warped Spaces/04.0s Prison Med Hall-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/05 Warped Spaces/04.2s Salt Mine One-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/05 Warped Spaces/14.3s Dam Level One-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/05 Warped Spaces/14.5s Dam Level One-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/05 Warped Spaces/18.7s Castle Lobby-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/05 Warped Spaces/18.7s Castle Lobby-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/05 Warped Spaces/19.2s Dam Level Two-OSD.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/04 Surround Spaces/05 Warped Spaces/20.2s Dam Level Two-OBF.SDIR",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/03.8s Grand Hall One.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/00.4s Drum Booth Three.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/00.5s Drum Booth Two.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/00.7s Drum Booth Four.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/00.9s Hard Studio.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/01.0s Drum Booth One.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/01.0s Recording Room +.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/01.0s Villa Office.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/01.1s Live Stage.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/01.1s Villa Living Room.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/01.2s Recording Room.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/01.2s Villa Bathroom.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/01.3s Villa Parlor.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/01.6s Villa Stairway.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/01.7s Villa Kitchen.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/01.9s Prince Hall Two.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/02.0s Villa Lobby.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/02.4s Prince Hall One.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/02.4s Villa Wine Cellar.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/02.6s Archaic Courtroom.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/02.7s Hansa Studio.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/02.8s Michaelis Abbey.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/02.9s Hansa Studio +.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/03.1s Aranno Sacristy.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/03.2s Michaelis Chapel.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/03.3s Chamber Four.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/03.4s Chamber Three.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/03.5s Chamber Two.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/03.6s Grand Hall Three.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/03.8s Grand Hall One SR.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/04.1s Grand Hall Two.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/01 Surround Rooms/05.7s Chamber One SR.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/02.8s TV Studio.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/03.2s Prison Small Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/03.9s Prince Hall Three.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/04.0s Prison Med Hall SR.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/04.4s Ulm Chapel.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/05.0s Church Tower.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/05.3s Aranno Chapel.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/05.3s Prison Main Floor.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/05.3s Sound Stage 12 +.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/05.4s Sound Stage 12.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/06.4s Ancient Church +.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/06.8s Ancient Church.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/06.9s Opulent Ballroom.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/06.9s Ulm Lobby.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/07.2s Michaelis Nave.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/07.3s Barracks Two.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/07.4s Botta Church.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/07.9s Marble Church.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/08.9s Bottom of Stairs.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/10.3s Church Balcony.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/10.4s Abbey.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/10.4s Barracks One.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/11.2s Conservatory.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/11.9s Ulm Nave.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/12.0s Conservatory +.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/13.9s Stairs Top Floor.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/02 Surround Halls/14.3s Stairs Mid Level.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/03 Surround Indoor/01.7s Big Cave Entrance.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/03 Surround Indoor/02.5s Big Cave One.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/03 Surround Indoor/02.6s Tiled Room.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/03 Surround Indoor/02.9s Tiled Room +.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/03 Surround Indoor/03.5s Big Cave Two.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/03 Surround Indoor/03.9s Salt Mine Two SR.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/03 Surround Indoor/04.2s Salt Mine One.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/03 Surround Indoor/10.4s Hangar One.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/03 Surround Indoor/18.7s Castle Lobby SR.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/04 Surround Outdoor/02.5s Amphitheater.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/04 Surround Outdoor/09.0s Soccer Field SR.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/04 Surround Outdoor/09.4s Upper Echelons.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/04 Surround Outdoor/14.5s Dam Level One.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/10 Surround Spaces/04 Surround Outdoor/20.2s Dam Level Two.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/00.3s Drum Booth Three HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/00.6s Drum Booth Four HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/00.7s Drum Booth Two HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/00.8s Drum Booth One HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/00.8s Hard Studio HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/01.0s Live Stage HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/01.0s Villa Office HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/01.1s Recording Room HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/01.1s Villa Bathroom HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/01.3s Villa Parlor HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/01.4s Villa Living Room HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/01.6s Villa Kitchen HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/01.7s Prince Hall Two HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/01.7s Villa Stairway HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/02.0s Villa Lobby HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/02.1s Prince Hall One HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/02.2s Michaelis Abbey HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/02.3s Archaic Courtroom HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/02.3s Villa Wine Cellar HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/02.8s Aranno Sacristy HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/02.8s Hansa Studio HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/03.0s Chamber Three HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/03.1s Chamber Four HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/03.1s Michaelis Chapel HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/03.6s Chamber Two HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/03.6s Grand Hall Three HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/03.8s Grand Hall One HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/04.2s Grand Hall Two HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/01 HD Surround Rooms/05.5s Chamber One HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/02.6s TV Studio HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/03.2s Prison Small Hall HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/03.9s Prince Hall Three HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/04.0s Prison Med Hall HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/04.0s Ulm Chapel HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/05.0s Aranno Chapel HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/05.0s Church Tower HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/05.3s Prison Main Floor HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/05.9s Sound Stage 12 HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/06.4s Barracks Two HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/06.5s Ancient Church HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/06.8s Opulent Ballroom HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/06.9s Ulm Lobby HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/07.0s Michaelis Nave HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/07.2s Botta Church HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/07.4s Marble Church HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/09.0s Bottom of Stairs HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/09.6s Abbey HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/10.1s Barracks One HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/10.3s Church Balcony HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/10.8s Conservatory HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/11.2s Ulm Nave HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/13.0s Stairs Top Floor HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/02 HD Surround Halls/14.8s Stairs Mid Level HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/03 HD Surround Indoor/01.6s Big Cave Entrance HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/03 HD Surround Indoor/02.3s Tiled Room HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/03 HD Surround Indoor/02.8s Big Cave One HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/03 HD Surround Indoor/03.3s Big Cave Two HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/03 HD Surround Indoor/03.9s Salt Mine One HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/03 HD Surround Indoor/03.9s Salt Mine Two HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/03 HD Surround Indoor/10.1s Hangar One HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/03 HD Surround Indoor/18.7s Castle Lobby HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/04 HD Surround Outdoor/02.0s Amphitheater HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/04 HD Surround Outdoor/08.2s Soccer Field HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/04 HD Surround Outdoor/09.4s Upper Echelons HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/04 HD Surround Outdoor/14.3s Dam Level One HD.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/11 HD Surround Spaces/04 HD Surround Outdoor/19.2s Dam Level Two HD.pst",
  ]
end
