cask "ml-0045-modularmelodies" do
  version "770ae9cbda220503e5b10e8ad8b1623f-20"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0045_modularmelodies/ml_0045_modularmelodies.aar"
  name "ModularMelodies"
  desc "SynthPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0045_modularmelodies/ml_0045_modularmelodies.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0045_modularmelodies.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/360 Blazing Clusters 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/360 Blazing Clusters 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Afterlife Bouncing Tines.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Afterlife Chordal Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Afterlife Percussive Glitches.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Air Tanks Synth Percussion.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Air Tanks Synth Pulse.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Air Tanks Synth Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Antiquated Memories Mallets.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Automaton Drum Circle.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Bell Tree Fragments.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Binary Streams Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Biosynthesis Bass Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Biosynthesis Bowed Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Biosynthesis Chordal Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Blue Shades Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Blue Shades Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Bubble Transmissions.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Bug Chirps Synth Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Bug Chirps Synth Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Bug Chirps Synth Percussion.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Butterfly House.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Butterfly Wheel Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Butterfly Wheel Bass Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Butterfly Wheel Pulsing Pad.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Butterfly Wheel Synth Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Butterfly Wheel Synth Chords.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Butterfly Wheel Synth Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Cannot Compute Synth FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Cave Dweller Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Cave Dweller Synth Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Cave Dweller Synth Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Cembalo Cables Synth High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Cembalo Cables Synth Low.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Cembalo Cables Synth Noise.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Chattering Circuits Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Chiming Partials Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Chiming Partials Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Cirrus Clouds Synth Chords.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Comic Hops.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Crossed Wires Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Crossed Wires Synth Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Crossed Wires Synth Flute.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Crossed Wires Synth FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Crossed Wires Synth Percussion.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Crystalline Synth Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Cybernetic March.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Cypher Signals Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Dark Depths Synth Bells.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Dark Depths Synth Pad.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Dark Modular Dub.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Dendritic Synth Percussion.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Dendritic Synth Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Diamond Drops Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Diamond Drops Synth Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Diamond Drops Synth Percussion.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Diamond Drops Synth Pulse.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Digital Whispers Synth FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Drinking Drops Arp 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Drinking Drops Arp 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Dystopian Frequencies Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Dystopian Frequencies Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Dystopian Frequencies Chords.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Ebb and Flow Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Evolving Materials.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Fading Fragments Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Filtered Metal Noise Synth.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Filtered Metal Synth.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Flexibuzz Bass Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Flexibuzz Synth Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Flexibuzz Synth Percussion.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Flexibuzz Synth Pulse.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Flexibuzz Synth Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Flooded Warehouse Bass 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Flooded Warehouse Bass 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Fluttering Resonances 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Fluttering Resonances 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Fractured FM Bells.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Fragmented Echo Pluck.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Future Past Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Future Past Clav.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Future Past Percussion.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Future Past Toppings.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Get To Work.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Glass Ripples Synth FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Glass Ripples Synth Pulse.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Glass Ripples Synth Swells.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Growling Metal Synth Pulse.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Hesitant.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Homeworld Synth Bell Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Homeworld Synth Lead 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Homeworld Synth Lead 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Homeworld Synth Sequence 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Homeworld Synth Sequence 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Hyperbaric Synth Swells.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/In The Fold Synth Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/In The Fold Synth FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Interdimensional Contact Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Interlinked Synth Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Intersections Synth Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Intersections Synth Bells.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Intersections Synth Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Intersections Synth Percussion.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Intersections Synth Pulse.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Light Array Synth Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Locomotion Synth Pulse.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Lonely Planet Chordal Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Lonely Planet Keyboard Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Machine Mind Synth FX 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Machine Mind Synth FX 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Machine Mind Synth Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Magic Hour Bass Pad.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Magic Hour Blip Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Magic Hour Stutter Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Magic Hour Synth Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Mangling Jangling Keys.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Mangling Jangling Synth High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Mangling Jangling Synth Low.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Mars Walk Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Mars Walk Synth Percussion.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Mars Walk Synth String Pad.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Martian Dewdrops Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Metallic Forest Bass Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Metallic Forest Chordal Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Micro Organism Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Modular Mechanics.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Mounting Tension.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Neon Wires Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Neon Wires Bass Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Neon Wires Chordal Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Neon Wires Synth Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Neon Wires Synth Lead 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Neon Wires Synth Lead 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Neon Wires Synth Pulse.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/New Frontiers Chordal Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Nucleoid Bass Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Nucleoid Synth Percussion.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Odd Anomalies Synth Bass 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Odd Anomalies Synth Bass 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Old Paths Synth Percussion 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Old Paths Synth Percussion 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Old Paths Synth Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Orbital Eye Synth Chords.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Planetary Ring Bass Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Planetary Ring Bass Pad.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Planetary Ring Filtered Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Planetary Ring Metallic Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Planetary Ring Rising Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Planetary Ring Simple Pad.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Planetary Ring Synth Bells.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Planetary Ring Synth Chords.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Planetary Ring Synth Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Planetary Ring Synth Plucks.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Pleasant Ones Chordal Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Pleasant Zeros Chordal Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Polygons Arp 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Polygons Arp 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Polygons Synth FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Pondering Squares Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Pulsing Breath Synth FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Pulsing Grids Synth Bass 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Pulsing Grids Synth Bass 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Pulsing Grids Synth Bass FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Pulsing Grids Synth Pulse.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Pulsing Grids Synth Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Punch It Synth Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Purple Gems Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Purple Gems Synth Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Purple Gems Synth Pad.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Push and Pull Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Push and Pull Bells.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Push and Pull Synth.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Quantum Foam Synth Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Retrofuture Bell Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Retrofuture Pluck Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Retrofuture Synth Chords 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Retrofuture Synth Chords 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Retrofuture Synth Pulse.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Rolled Diamonds.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Rolling Gates Bass Arp 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Rolling Gates Bass Arp 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Rolling Gates Layered Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Rolling Pinball Synth Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Rolling Pulses Synth Chords.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Rustic Machine Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Shattered Sky Bells.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Shimmering Sun Synth Bells.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Sky Flight Chordal Arp 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Sky Flight Chordal Arp 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Space Race Arp 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Space Race Arp 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Space Race Synth Bells.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Space Race Synth Chords.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Space Race Synth Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Space Race Synth Percussion 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Space Race Synth Percussion 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Space Walk Bass Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Space Walk Bell Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Spitballing.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Staccato Wires Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Staccato Wires Synth 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Staccato Wires Synth 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Staccato Wires Synth 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Staggering Bones Bells.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Staggering Bones Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Staggering Bones Synth.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Star Harps Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Star Harps Bell Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Star Harps Synth Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Star Harps Synth Chords.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Star Rise Bass Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Star Rise Chordal Pad.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Star Rise Metal Percussion Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Star Rise Rolling Triplet Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Star Rise Synth Bell Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Steel Drum Modular 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Steel Drum Modular 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Struck Brass 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Struck Brass 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Sulfur Skies Pluck Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Sulfur Skies Pulse Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Sulfur Skies Synth Chords.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Sun Drops Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Swinging Glass Droplets.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Tangerine Sky Chordal Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Teleidoscope Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Teleidoscope Pluck Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Teleidoscope Synth Chords.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Teleidoscope Synth Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Tesseract Synth Sequence 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Tesseract Synth Sequence 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Textural Collapse Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Textural Collapse Bells.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Textural Collapse Glitches.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Textural Collapse Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Time Tomb Synth Sequence 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Time Tomb Synth Sequence 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Trellis Synth Percussion.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Trellis Synth Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Tube Runner Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Tube Runner Bass Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Tube Runner Bell Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Tube Runner Synth Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Tube Runner Synth Lead 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Tube Runner Synth Lead 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Unplug Debug Bass.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Unplug Debug Clav.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Unplug Debug Filter High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Unplug Debug Filter Low.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Unplug Debug Noise Lead.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Unplug Debug Noise Synth.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Wave Motion Synth Chords.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Whimsical Whirligig Ambiance.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Whimsical Whirligig Bells.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Whimsical Whirligig Chimes.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Whisper Rise String Riser.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Modular Melodies/Wild Robots Synth Sequence.caf",
    "～/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0045_modularmelodies.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Cosmic Dust Arp.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Cosmic Dust Arp.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Cosmic Dust Arp.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Cosmic Dust Arp.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Glass Echoes Arp.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Glass Echoes Arp.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Glass Echoes Arp.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Glass Echoes Arp.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Resistance Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Resistance Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Resistance Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Resistance Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Surge Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Surge Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Surge Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Surge Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Circuit Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Circuit Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Circuit Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Circuit Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Stochastic Horizons.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Stochastic Horizons.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Stochastic Horizons.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Stochastic Horizons.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/String Theory Pulse.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/String Theory Pulse.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/String Theory Pulse.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/String Theory Pulse.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Subwave Dragon Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Subwave Dragon Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Subwave Dragon Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Subwave Dragon Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Vox Voltage Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Vox Voltage Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Vox Voltage Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Vox Voltage Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Analog Lullaby.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Analog Lullaby.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Analog Lullaby.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Analog Lullaby.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Pulse Nexus.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Pulse Nexus.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Pulse Nexus.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Pulse Nexus.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Quantum Grains.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Quantum Grains.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Quantum Grains.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Quantum Grains.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Effervescent Lead.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Effervescent Lead.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Effervescent Lead.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Effervescent Lead.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Midnight Mallets.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Midnight Mallets.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Midnight Mallets.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Midnight Mallets.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Orbital Chimes.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Orbital Chimes.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Orbital Chimes.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Orbital Chimes.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Voltage Waves.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Voltage Waves.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Voltage Waves.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Voltage Waves.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Tides.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Tides.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Tides.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Tides.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Bent Beyond.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Bent Beyond.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Bent Beyond.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Bent Beyond.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Icicle Plucks.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Icicle Plucks.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Icicle Plucks.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Icicle Plucks.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Interrupted Transmission.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Interrupted Transmission.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Interrupted Transmission.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Interrupted Transmission.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Modular Math Beats.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Modular Math Beats.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Modular Math Beats.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Modular Math Beats.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Entropy Fields.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Entropy Fields.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Entropy Fields.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Entropy Fields.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Cosmic Dust Arp.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Glass Echoes Arp.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Analog Resistance Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Analog Surge Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Deep Circuit Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Stochastic Horizons.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/String Theory Pulse.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Subwave Dragon Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Vox Voltage Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Analog Lullaby.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Icicle Plucks.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Pulse Nexus.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Quantum Grains.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Lead/Effervescent Lead.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Mallets/Midnight Mallets.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Mallets/Orbital Chimes.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Voltage Waves.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Warm Tides.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Plucked/Bent Beyond.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Rhythmic/Interrupted Transmission.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Rhythmic/Modular Math Beats.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Entropy Fields.acp",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Rhythmic/Custom/Modular Drum loop-001-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Orbital ChimesA0000-A.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Orbital ChimesB0000-A.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Pulse NexusA0000-A.aaz",
  ]
end
