cask "ml-0051-irs-stereo" do
  version "2b4d33d00c964da87d34c6759a302c03-66"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0051_irs_stereo/ml_0051_irs_stereo.aar"
  name "StereoIRs"
  desc "ImpulseResponsePack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0051_irs_stereo/ml_0051_irs_stereo.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0051_irs_stereo.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0051_irs_stereo.plist",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/01 Rooms",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/03.7s Ulm Chapel-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/03.9s Prince Hall One-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/04.7s Prison Hall-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/04.7s Prison Main Floor-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/04.7s Sound Stage 12-CTS.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/04.9s Aranno Chapel-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/04.9s Church Tower-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/05.9s Ancient Church-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/05.9s Sound Stage 12-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/06.1s Ancient Chuch-CTS.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/06.2s Ulm Lobby-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/06.4s Barracks Two-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/06.5s Opulent Ballroom-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/06.6s Botta Church-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/06.7s Marble Church-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/07.1s Michaelis Nave-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/09.0s Abbey-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/09.0s Bottom of Stairs-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/09.6s Barracks One-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/09.9s Conservatory-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/1.3s_Choir Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/10.6s_Long Dream.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/10.7s Ulm Nave-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/11.7s Conservatory-CTS.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/11.9s Church Balcony-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/12.0s Stairs Top Floor-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/14.8s Stairs Mid Level-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/2.2s_Large Choir.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/2.3s_Piano Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/2.4s_String Reverb.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/2.5s_Soft Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/2.7s_Smooth Vocal Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/2.8s_Nice Vocal Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/2.9s_Vintage Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/2.9s_Vocal Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/3.0s_Long Reverb.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/3.1s_Modulating Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/3.1s_Reflective Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/3.2s_Male Vox Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/3.3s_Stone Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/3.3s_Warm Vocal Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/3.4s_Warm Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/3.5s_Large Hall D.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/3.6s_Guitar Hall Large.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/3.6s_String Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/3.7s_Concert Hall B.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/4.4s_Dream Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/4.5s_Fine Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/5.0s_Dark.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/6.8s_Spendid Verb.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/03 Plate Reverbs",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/03.3s Rack Spring Flat.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/03.5s LoFi Amp LoMid.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/03.6s Grey Amp Spring.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/03.8s LoFi Amp Mid A.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/04.0s Cheap Spring Flat.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/04.0s Guitar Spring Bright.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/04.0s LoFi Amp Bass.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/04.0s LoFi Amp Mid B.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/04.4s Cheap Spring Bright.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/04.5s Guitar Spring Mellow.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/04.9s Petaluma Spring.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/3.0s_Amp Spring.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/3.0s_Old Amp Spiral.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/4.5s_Moog Spring.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/03.0s Big Cave One-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/09.7s Hangar One-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/1.9s_Plane Hangar.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/12.2s_Grand Church.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/14.0s_Dome.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.1s_Concert Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.1s_Gymnasium.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.1s_On Stage.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.1s_Storage Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.2s_Concert.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.3s_At The Opera.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.4s_High School Gym.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.4s_Stage Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.5s_Clear Space.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.6s_Big Bathroom.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.6s_Bright Staircase 3D.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.6s_Medium Church.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.7s_Arena.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.7s_Public Swimming Pool.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.9s_In Concert.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.9s_Neo Church.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.0s_Boat Hangar.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.0s_Large Pub.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.0s_Mountain Chapel.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.0s_Passage B.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.1s_Empty Conference Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.2s_Empty Church.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.3s_Auditorium.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.3s_Concrete Basement.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.3s_Large Cathedral.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.4s_Cathedral.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.4s_Empty Club.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.4s_Swimming Pool.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.7s_Subway.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.8s_Parking Garage.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.9s_Train Station.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/4.0s_Swimming Pool.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/4.2s_Central Station.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/4.3s_In the Subway.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/4.9s_Large Empty Pool.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/5.6s_Gothic Church.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/6.2s_Ambient Church.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/6.6s_Big Old Church.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/6.6s_Palace.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/7.0s_Cathedral C.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/8.7s_Big Gothic Church.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/09.0s Soccer Field-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/09.2s Upper Echelons-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/2.4s_City Street C.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/2.4s_Seashore.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/2.4s_Tunnel.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/2.5s_Tunnel B.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/2.9s_On the Field Natural.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/3.1s_Natural Reflect Short.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/3.1s_Thomb Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/3.5s_Natural Reflect Med.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/4.0s_Old Forest Long.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/4.0s_On The Field Long+.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/4.4s_Natural Reflect Long.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/5.2s_Barrel Verb.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/5.2s_Deep Canon.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/5.4s_Echoing Mountains.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/8.0s_Thunderstruck.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/8.5s_Big Cave.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/9.1s_Ungerground Tunnel.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/03.0s Prison Sm Hall-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/03.4s Salt Mine One-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/03.9s Salt Mine Two-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/04.0s Prison Med Hall-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/1.9s_Bomb Tail.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/10.0s_Weird FX.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/10.5s_Fractal Impulse.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/10.9s Dam Level One-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/16.3s Dam Level Two-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/18.7s Castle Lobby-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/2.3s_Shot.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/2.4s_Drum Roll.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/2.6s_Guitar Space.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/2.8s_Modula B.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/3.0s_Shadows.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/3.1s_Deep Verb.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/3.1s_Weird Echo.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/3.6s_Deep Space.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/3.7s_Non Linear.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/3.8s_Underground B.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/4.1s_Thunder B.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/4.2s_Black Hole.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/4.3s_Deep Rotor.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/4.8s_Space Modulation B.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/5.2s_Long and Dark.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/5.2s_Smooth.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/5.3s_Long Vocals.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/5.6s_Thunder Wave A.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/5.9s_Rotor Gate.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/6.3s_Formant Shift.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/6.3s_Warp.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/6.5s_Iron Engine.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/7.0s_Space Com.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/7.1s_Weird Delay.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/7.8s_Laserfire.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/02.0s Prince Hall One-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/02.0s Villa Lobby-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/02.0s Villa Wine Cellar-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/02.2s Michaelis Abbey-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/02.3s Archaic Courtroom-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/02.4s Chamber Three-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/02.6s Hansa Studio-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/02.7s Aranno Sacristy-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/02.7s Chamber Four-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/02.8s Michaelis Chapel-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/03.0s Chamber Two-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/03.0s Hansa Studio-CTS.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.0s_Brite Chamber.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.1s_Live Chamber B.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.2s_Echo Place.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.3s_Horn Chamber.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.4s_Nice Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.4s_Piano Reflection.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.5s_Perc Room A.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.5s_Pianowarmth.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.5s_String Chamber.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.6s_Bight & Empty.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.6s_Tile Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.7s_Green Chamber.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.7s_Medium Sweet.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.8s_Ambience.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.8s_Stonewall Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.9s_Skindrum Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/1.9s_Smaller Brite.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/2.0s_Sax Reverb.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/2.0s_Studio Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/2.0s_Tight Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/2.1s_Pyramid Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/02 Halls",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/03 Plate Reverbs/1.2s_Tabla Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/03 Plate Reverbs/1.3s_Horn Section Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/03 Plate Reverbs/1.3s_Soft Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/03 Plate Reverbs/1.4s_Ice Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/03 Plate Reverbs/1.7s_Blue Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/03 Plate Reverbs/1.8s_Drum Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/05 Gated Reverbs",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/06 Spring Reverbs",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/07 Indoor Spaces",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/08 Outdoor Spaces",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/09 Warped Reverb",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.03s_Room Vocals.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.2s_Small Wet Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.2s_Strings Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.2s_Tom  Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.3s_Jazz Guitar.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.3s_Wooden Booth.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.4s_Little Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.4s_Live Chamber.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.4s_Reflexion Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.4s_Snare Chamber.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.4s_Wide & Small.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.5s_Drum Chamber.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.5s_Wooden Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.6s_Wooden Studio.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.7s_Empty Room A.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.7s_Realistic Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.7s_Recording Room A.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.7s_Small Studio.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.8s_Boom Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.9s_Blue Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.9s_Slap Chamber.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.9s_Wet Small Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/00.3s Drum Booth Three-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/00.6s Drum Booth Four-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/00.6s Drum Booth Two-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/00.8s Drum Booth One-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/00.8s Hard Studio-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/00.9s Recording Room-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/00.9s Villa Office-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/01.0s Live Stage-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/01.0s Villa Bathroom-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/01.2s Recording Room-CTS.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/01.2s Villa Parlor-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/01.3s Villa Living Room-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/01.3s Villa Stairway-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/01.6s Prince Hall Two-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/01.6s Villa Kitchen-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/1.0s_Hard Ambience.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/1.0s_Sloppy Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/1.0s_Vibes FX.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/1.1s_Cello Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/1.6s_Breeze Vocals.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/1.6s_Multi Vocals.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/02 Halls",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/03 Plate Reverbs",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/05 Gated Reverbs",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/06 Spring Reverbs",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/07 Indoor Spaces",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/08 Outdoor Spaces",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/09 Warped Reverb",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/01 Drone Tones",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/02 Moving Spaces",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/03 Textures",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/04 Drum Transformers",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/05 Ghost Rhythms/100 BPM",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/05 Ghost Rhythms/120 BPM",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/05 Ghost Rhythms/125 BPM",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/05 Ghost Rhythms/130 BPM",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/05 Ghost Rhythms/140 BPM",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/05 Ghost Rhythms/80 BPM",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/06 Speakers",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/07 Analog Circuits",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/01 Rooms",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/0.6s Short Snare Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/01.3s Choir Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/02.2s Large Choir Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/02.3s Dark Piano Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/02.4s Big String Reverb.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/02.5s Soft Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/02.7s Smooth Vocal Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/02.8s Nice Vocal Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/02.9s Vintage Gear Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/02.9s Vocal Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/03.0s Long Reverb.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/03.1s Bright Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/03.1s Reflective Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/03.2s Male Vox Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/03.3s Stone Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/03.3s Warm Vocal Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/03.4s Warm Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/03.5s Large Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/03.6s Guitar Hall Large.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/03.6s String Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/03.7s Dark Concert Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/03.7s Ulm Chapel.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/03.9s Prince Hall One.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/04.4s Dream Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/04.5s Fine Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/04.7s Prison Main Floor.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/04.7s Sound Stage 12 +.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/04.9s Aranno Chapel.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/04.9s Church Tower.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/05.0s Dark Rising Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/05.9s Ancient Church.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/05.9s Sound Stage 12.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/06.1s Ancient Church +.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/06.2s Ulm Lobby.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/06.4s Barracks Two.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/06.5s Opulent Ballroom.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/06.6s Botta Church.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/06.7s Marble Church.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/06.8s Splendid Verb.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/07.1s Michaelis Nave.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/09.0s Abbey.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/09.0s Bottom of Stairs.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/09.6s Barracks One.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/09.9s Conservatory.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.0s Dynamic Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.0s Small Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.3s Ambience Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.3s Compressed Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.3s Diffuse Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.3s Medium Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.4s Bright Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.5s Plasterhall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.6s Diffusion Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.6s Short Vocal Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.6s Small Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.7s Nice Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.7s Small Guitar Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.8s Midnight Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/1.8s Narrow Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/10.6s Long Dream.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/10.7s Ulm Nave.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/11.7s Conservatory +.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/11.9s Church Balcony.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/12.0s Stairs Top Floor.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/14.8s Stairs Mid Level.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/2.0s Medium Hall.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/2.0s Space Reverb.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/02 Halls/2.6s TV Studio.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/03 Plate Reverbs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/04 Gated Reverbs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/04 Spring Reverbs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/06 Indoor Spaces",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/07 Outdoor Spaces",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/08 Warped Spaces",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/09 Warped Effects/01 Drone Tones",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/09 Warped Effects/02 Moving Spaces",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/09 Warped Effects/03 Textures",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/09 Warped Effects/04 Drum Transformers",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/09 Warped Effects/05 Ghost Rhythms",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/09 Warped Effects/06 Speakers",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Space Designer/09 Warped Effects/07 Analog Circuits",
  ]
end
