cask "ml-0037-studiohorns" do
  version "e96805a511072fb9fa511f264dc1f18f-225"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0037_studiohorns/ml_0037_studiohorns.aar"
  name "StudioHorns"
  desc "InstrumentPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0037_studiohorns/ml_0037_studiohorns.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0037_studiohorns.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Bottom Dollar Horn Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Bottom Dollar Horn Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Bottom Dollar Horn Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Bottom Dollar Horn Stabs 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Bottom Dollar Horn Stabs 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Bottom Dollar Horn Stabs 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Bounce Back Horn Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Bounce Back Horn Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Bounce Back Horn Chords 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Championship Horn Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Championship Horn Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Classic Tracks Ascending Horns.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Classic Tracks Horn Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Classic Tracks Horn Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Classic Tracks Horn Stabs.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Grand Stand Horn Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Grand Stand Horn Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Grand Stand Horn Lead 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Gray Day Descending Horns.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Gray Day Horn Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Gray Day Horn Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Gray Day Horn Lead 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Gray Day Horn Lead 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Gray Day Horn Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Gray Day Horn Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Gray Day Horn Pad 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Lioness Horn Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Lioness Horn Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Lioness Horn Stabs 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Lioness Horn Stabs 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Marching On Horn Accent 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Marching On Horn Accent 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Marching On Horn Accent 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Marching On Horn Accent 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Marching On Horn Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Marching On Horn Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Marching On Horn Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Marching On Horn Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Much Praise Horn Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Much Praise Horn Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Reflective Soul Horn Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Reflective Soul Horn Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Reflective Soul Horn Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Reflective Soul Horn Lead 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Reflective Soul Horn Lead 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Reflective Soul Horn Stabs.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Rolling River Horn Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Rolling River Horn Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Rolling River Horn Lead 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Rolling River Horn Lead 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Rolling River Horn Stabs.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Sneaking Round Horn Stabs 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Horns/Sneaking Round Horn Stabs 02.caf",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0037_studiohorns.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Chicago Street.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Chicago Street.patch/ChicagoStreet.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Chicago Street.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Chicago Street.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Chicago Street.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Chicago Street.patch/TenorSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Chicago Street.patch/Trombone1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Chicago Street.patch/Trumpet1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Elements Section.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Elements Section.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Elements Section.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Elements Section.patch/ElementsSection.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Elements Section.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Elements Section.patch/TenorSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Elements Section.patch/Trombone1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Elements Section.patch/Trumpet1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Hell's Kitchen.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Hell's Kitchen.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Hell's Kitchen.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Hell's Kitchen.patch/HellsKitchen.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Hell's Kitchen.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Hell's Kitchen.patch/TenorSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Hell's Kitchen.patch/Trombone1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Hell's Kitchen.patch/Trumpet1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Strivers' Row.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Strivers' Row.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Strivers' Row.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Strivers' Row.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Strivers' Row.patch/StriversRow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Strivers' Row.patch/TenorSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Strivers' Row.patch/Trombone.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/3-Piece Section/Strivers' Row.patch/Trumpet.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Funkhouse.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Funkhouse.patch/AltoSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Funkhouse.patch/BaritonSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Funkhouse.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Funkhouse.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Funkhouse.patch/Funkhouse.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Funkhouse.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Funkhouse.patch/TenorSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Funkhouse.patch/Trombone1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Funkhouse.patch/Trumpet1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Funkhouse.patch/Trumpet2.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Little Brazil.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Little Brazil.patch/AltoSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Little Brazil.patch/BaritonSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Little Brazil.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Little Brazil.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Little Brazil.patch/LittleBrazil.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Little Brazil.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Little Brazil.patch/TenorSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Little Brazil.patch/Trombone.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Little Brazil.patch/Trumpet1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Little Brazil.patch/Trumpet2.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Memphis Blast.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Memphis Blast.patch/AltoSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Memphis Blast.patch/BaritonSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Memphis Blast.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Memphis Blast.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Memphis Blast.patch/MemphisBlast.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Memphis Blast.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Memphis Blast.patch/TenorSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Memphis Blast.patch/Trombone.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Memphis Blast.patch/Trumpet1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Memphis Blast.patch/Trumpet2.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/6-Piece Section/Memphis Blast.patch/VintageHall.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Mississippi Joint.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Mississippi Joint.patch/AltoSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Mississippi Joint.patch/BaritonSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Mississippi Joint.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Mississippi Joint.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Mississippi Joint.patch/MississippiJoint.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Mississippi Joint.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Mississippi Joint.patch/TenorSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Mississippi Joint.patch/Trombone1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Mississippi Joint.patch/Trombone2.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Mississippi Joint.patch/Trumpet1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Mississippi Joint.patch/Trumpet2.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Sugar Hill.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Sugar Hill.patch/AltoSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Sugar Hill.patch/BaritonSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Sugar Hill.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Sugar Hill.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Sugar Hill.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Sugar Hill.patch/SugarHill.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Sugar Hill.patch/TenorSax.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Sugar Hill.patch/Trombone1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Sugar Hill.patch/Trombone2.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Sugar Hill.patch/Trumpet1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/7-Piece Section/Sugar Hill.patch/Trumpet2.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Alto Sax 1.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Alto Sax 1.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Alto Sax 1.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Alto Sax 1.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Alto Sax 2.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Alto Sax 2.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Alto Sax 2.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Alto Sax 2.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Baritone Sax.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Baritone Sax.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Baritone Sax.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Baritone Sax.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Bass Trombone.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Bass Trombone.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Bass Trombone.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Bass Trombone.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Tenor Sax 1.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Tenor Sax 1.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Tenor Sax 1.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Tenor Sax 1.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Tenor Sax 2.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Tenor Sax 2.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Tenor Sax 2.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Tenor Sax 2.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trombone 1.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trombone 1.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trombone 1.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trombone 1.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trombone 2.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trombone 2.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trombone 2.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trombone 2.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trombone 3.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trombone 3.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trombone 3.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trombone 3.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 1.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 1.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 1.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 1.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 2.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 2.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 2.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 2.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 3.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 3.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 3.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 3.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 4.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 4.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 4.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Brass & Woodwind/Studio Horns/Single Instruments/Studio Trumpet 4.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Section Instruments/Studio Horns - 3 piece - RnB Section.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Section Instruments/Studio Horns - 6 piece - Soul Section.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Section Instruments/Studio Horns - 7 piece - Jazz Section.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Single Instruments/Studio Alt Sax 1.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Single Instruments/Studio Alt Sax 2.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Single Instruments/Studio Baritone Sax.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Single Instruments/Studio Bass Trombone.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Single Instruments/Studio Tenor Sax 1.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Single Instruments/Studio Tenor Sax 2.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Single Instruments/Studio Trombone 1.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Single Instruments/Studio Trombone 2.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Single Instruments/Studio Trombone 3.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Single Instruments/Studio Trumpet 1.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Single Instruments/Studio Trumpet 2.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Single Instruments/Studio Trumpet 3.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Horns/Single Instruments/Studio Trumpet 4.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Experimental/80s Brass Stab.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Experimental/Brass Pad.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Experimental/Breath Controlled Alto Sax.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Experimental/Expressive Trumpet.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Experimental/Jazz Section (Start by Key Split).pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Experimental/Jazz Section (Start with Bass Voice).pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Experimental/Simple Tenor Sax.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Experimental/Trombone Pad.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Lead Instruments/Studio Alto Sax 1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Lead Instruments/Studio Tenor Sax 1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Lead Instruments/Studio Trombone 1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Lead Instruments/Studio Trumpet 1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Secondary Instruments/Studio Alto Sax 2.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Secondary Instruments/Studio Baritone Sax.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Secondary Instruments/Studio Bass Trombone.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Secondary Instruments/Studio Tenor Sax 2.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Secondary Instruments/Studio Trombone 2.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Secondary Instruments/Studio Trombone 3.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Secondary Instruments/Studio Trumpet 2.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Secondary Instruments/Studio Trumpet 3.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Secondary Instruments/Studio Trumpet 4.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Sections/Jazz Section.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Sections/R&B Section.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Horns/Sections/Soul Section.pst",
    "~/Music/Logic Pro Library.bundle/Samples/Brass/Studio Horns/Studio Alt Sax 1_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Brass/Studio Horns/Studio Alt Sax 2_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Brass/Studio Horns/Studio Baritone Sax_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Brass/Studio Horns/Studio Bass Trombone_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Brass/Studio Horns/Studio Tenor Sax 1_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Brass/Studio Horns/Studio Tenor Sax 2_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Brass/Studio Horns/Studio Trombone 1_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Brass/Studio Horns/Studio Trombone 2_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Brass/Studio Horns/Studio Trombone 3_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Brass/Studio Horns/Studio Trumpet 1_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Brass/Studio Horns/Studio Trumpet 2_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Brass/Studio Horns/Studio Trumpet 3_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Brass/Studio Horns/Studio Trumpet 4_consolidated.caf",
  ]
end
