cask "ml-0046-magneticimperfections" do
  version "cc8eb8c6dfbaa30023c28adfa94bb3e9-75"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0046_magneticimperfections/ml_0046_magneticimperfections.aar"
  name "MagneticImperfections"
  desc "VintageTexturesPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0046_magneticimperfections/ml_0046_magneticimperfections.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0046_magneticimperfections.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "～/Music/Logic Pro Library.bundle/Apple Loops/Magnetic Imperfections",
    "～/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0046_magneticimperfections.plist",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/07 Analog Circuits/Clean Limit Amp.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/07 Analog Circuits/Tape Saturator.SDIR",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/BoomFXLoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/ClapLoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Cowbell1LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Cowbell2LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Delay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/HiHat1LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/HiHat2LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/HiHatOpenLoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Kick1LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Kick2LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/KickSubLoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/KnockLoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Reverb.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Rim1LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Rim2LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Shaker1LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Shaker2LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Shaker3LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Snare1LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Snare2LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Snare3LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Snare4LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Snare5LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Snare6LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/Snare7LoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/TomHighLoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/TomLowLoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/TomMidLoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Cassette.patch/TriangleLoFiCassette.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/Clave1NoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/Clave2NoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/Clave3NoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/CowbellNoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/Delay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/HiHat1NoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/HiHat2NoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/HiHatOpenNoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/Kick1NoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/Kick2NoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/KnockNoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/Reverb.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/RimNoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/ShakerNoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/Snare1NoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/Snare2NoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/TomHigh1NoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/TomHigh2NoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/TomLowNoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Noise Reduction.patch/TomMidNoiseReduction.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/BoomFXSoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/Clap1SoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/Clap2SoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/CrashSoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/Delay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/HiHat1SoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/HiHat2SoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/HiHat3SoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/HiHatOpenSoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/KickSoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/Reverb.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/Snare1SoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/Snare2SoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/Snare3SoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/Snare4SoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/TomHighSoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/TomLowSoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soft Decay.patch/TomMidSoftDecay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/BoomFXTapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/Clap1TapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/Clap2TapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/CrashTapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/Delay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/HiHat1TapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/HiHat2TapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/HiHatOpenTapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/KickTapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/Reverb.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/Rim1TapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/Rim2TapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/Snare1TapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/Snare2TapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/Snare3TapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/Snare4TapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/TomHighTapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/TomLowTapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Tape Deck.patch/TomMidTapeDeck.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick Sub - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick Sub - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick Sub - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick Sub - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 5 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 5 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 5 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 5 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 6 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 6 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 6 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 6 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 7 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 7 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 7 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 7 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High 1 - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High 1 - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High 1 - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High 1 - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High 2 - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High 2 - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High 2 - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High 2 - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 3 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 3 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 3 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 3 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave 1 - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave 1 - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave 1 - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave 1 - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave 2 - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave 2 - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave 2 - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave 2 - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave 3 - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave 3 - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave 3 - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave 3 - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 1 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 1 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 1 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 1 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 2 - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 2 - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 2 - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 2 - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Knock - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Knock - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Knock - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Knock - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Knock - Noise Reduction.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Knock - Noise Reduction.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Knock - Noise Reduction.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Knock - Noise Reduction.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Triangle - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Triangle - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Triangle - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Triangle - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Boom FX - Lo-Fi Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Boom FX - Lo-Fi Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Boom FX - Lo-Fi Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Boom FX - Lo-Fi Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Boom FX - Soft Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Boom FX - Soft Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Boom FX - Soft Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Boom FX - Soft Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Boom FX - Tape Deck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Boom FX - Tape Deck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Boom FX - Tape Deck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Boom FX - Tape Deck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Capstan Piano.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Capstan Piano.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Capstan Piano.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Capstan Piano.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Ferrous Wurli.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Ferrous Wurli.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Ferrous Wurli.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Ferrous Wurli.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Ferrite Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Ferrite Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Ferrite Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Ferrite Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Flutter Reel Brass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Flutter Reel Brass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Flutter Reel Brass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Flutter Reel Brass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Azimuth Dream.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Azimuth Dream.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Azimuth Dream.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Azimuth Dream.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Capstan Drift.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Capstan Drift.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Capstan Drift.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Capstan Drift.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Empty Spool.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Empty Spool.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Empty Spool.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Empty Spool.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Escape The Grid.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Escape The Grid.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Escape The Grid.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Escape The Grid.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Faulty Memory.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Faulty Memory.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Faulty Memory.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Faulty Memory.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Ferrous Glow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Ferrous Glow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Ferrous Glow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Ferrous Glow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Flywheel Flutter.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Flywheel Flutter.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Flywheel Flutter.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Flywheel Flutter.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Nostalgic Noise.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Nostalgic Noise.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Nostalgic Noise.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Nostalgic Noise.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Off Bias Blues.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Off Bias Blues.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Off Bias Blues.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Off Bias Blues.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Oxide Haze.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Oxide Haze.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Oxide Haze.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Oxide Haze.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Portable Player.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Portable Player.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Portable Player.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Portable Player.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Print Through.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Print Through.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Print Through.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Print Through.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Return To Zero.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Return To Zero.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Return To Zero.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Return To Zero.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Warbling Hearts Decay.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Warbling Hearts Decay.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Warbling Hearts Decay.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Warbling Hearts Decay.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Deep Space Tape.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Deep Space Tape.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Deep Space Tape.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Deep Space Tape.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Video Cassette.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Video Cassette.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Video Cassette.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Video Cassette.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Worn Motor.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Worn Motor.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Worn Motor.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Worn Motor.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Fragile Sines.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Fragile Sines.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Fragile Sines.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Fragile Sines.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Lo-Fi Plucks.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Lo-Fi Plucks.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Lo-Fi Plucks.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Lo-Fi Plucks.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Pinch Roller Plucks.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Pinch Roller Plucks.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Pinch Roller Plucks.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Pinch Roller Plucks.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Plucky Patina.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Plucky Patina.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Plucky Patina.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Plucky Patina.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Iron Atmosphere.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Iron Atmosphere.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Iron Atmosphere.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Iron Atmosphere.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Brass/Ferrite Decay.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Azimuth Dream.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Capstan Piano.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Empty Spool.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Ferrous Wurli.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Nostalgic Noise.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Off Bias Blues.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Oxide Haze.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Return To Zero.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Warbling Hearts Decay.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Flutter Reel Brass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Plucked/Fragile Sines.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Plucked/Pinch Roller Plucks.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Plucked/Plucky Patina.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Capstan Drift.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Faulty Memory.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Ferrous Glow.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Portable Player.exs",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Flywheel Flutter",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Cassette Hiss.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Dusty Reel.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Worn Tape.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Erase Signal.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Signal Counter.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Cassette Kit",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Noise Reduction Kit",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Soft Decay Kit",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Tape Deck Kit",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Azimuth Dream_consolidated.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Capstan Drift.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Capstan Piano_consolidated.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Empty Spool-1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Empty Spool-2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Faulty Memory.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Ferrite Decay-1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Ferrite Decay-2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Ferrous Glow.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Ferrous Wurli_consolidated.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Flutter Reel Brass-1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Flutter Reel Brass-2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Off Bias Blues-1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Off Bias Blues-2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Oxide Haze-1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Oxide Haze-2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Pinch Roller Plucks-1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Pinch Roller Plucks-2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Portable Player.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Return To Zero-1.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Return To Zero-2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Tape Flutter Decay_consolidated.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Warbling Hearts Decay_consolidated.caf",
  ]
end
