cask "ml-0006-reggaetonpop" do
  version "de4a78e6dda63e6391be21459b1a1368-15"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0006_reggaetonpop/ml_0006_reggaetonpop.aar"
  name "GozaderaLatina"
  desc "ReggaetonPopPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0006_reggaetonpop/ml_0006_reggaetonpop.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0006_reggaetonpop.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "～/Music/Logic Pro Library.bundle/Apple Loops/Gozadera Latina",
    "～/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0006_reggaetonpop.plist",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/04.7s Prison Main Floor-OST.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.9s_Train Station.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/02 Halls/1.6s_Small Hall.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/06 Spring Reverbs/02.9s Combo Spring .SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.3s_Wooden Booth.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.5s_Wooden Room.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/1.0s_Vibes FX.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/03 Plate Reverbs/0.7s_Drum Plate.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/06 Speakers/Amp Cabinet Speaker 9.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/06 Speakers/Transistor Radio Speaker 1.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/06 Speakers/Transistor Radio Speaker 2.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/07 Analog Circuits/Clean Console.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/07 Analog Circuits/Tape Saturator.SDIR",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/BongoHighDembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/BongoLowDembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/CastanetsDembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/Clap1Dembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/Clap2Dembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/CongaHighDembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/CongaLowDembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/CrashDembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/Delay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/HiHatDembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/HiHatOpenDembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/Kick1Dembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/Kick2Dembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/PercFXDembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/Reverb.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/RideDembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/RimDembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/Shaker1Dembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/Shaker2Dembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/Shaker3Dembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/SnapDembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/Snare1Dembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/Snare2Dembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/Snare3Dembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dembow.patch/WhistleDembow.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Dembow.patch/com.apple.musicapps.intermediate.cache.zxml",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Dembow.patch/com.apple.musicapps.intermediate.cache.zxml",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 3 - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 3 - Dembow.patch/com.apple.musicapps.intermediate.cache.zxml",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 3 - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 3 - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 3 - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo High - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo High - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo High - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo High - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo Low - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo Low - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo Low - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo Low - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Castanets - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Castanets - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Castanets - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Castanets - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga High - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga High - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga High - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga High - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga Low - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga Low - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga Low - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga Low - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Whistle - Dembow.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Whistle - Dembow.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Whistle - Dembow.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Whistle - Dembow.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Dark Heavy Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Dark Heavy Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Dark Heavy Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Dark Heavy Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Solid Body Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Solid Body Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Solid Body Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Solid Body Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Synth Upright Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Synth Upright Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Synth Upright Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Synth Upright Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Brassy Ensemble.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Brassy Ensemble.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Brassy Ensemble.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Brassy Ensemble.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dirty Pulse.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dirty Pulse.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dirty Pulse.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dirty Pulse.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Hammered Mallets.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Hammered Mallets.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Hammered Mallets.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Hammered Mallets.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mutant Keys.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mutant Keys.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mutant Keys.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mutant Keys.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Short Swell Synth.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Short Swell Synth.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Short Swell Synth.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Short Swell Synth.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Small Metal Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Small Metal Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Small Metal Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Small Metal Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Synth Piano.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Synth Piano.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Synth Piano.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Synth Piano.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Time Warp Synth.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Time Warp Synth.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Time Warp Synth.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Time Warp Synth.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Chimera Hammer.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Chimera Hammer.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Chimera Hammer.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Chimera Hammer.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Hammered Wood.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Hammered Wood.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Hammered Wood.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Hammered Wood.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Wooden Keys.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Wooden Keys.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Wooden Keys.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Wooden Keys.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Synth Pad.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Synth Pad.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Synth Pad.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Synth Pad.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Main Room Pluck Lead.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Main Room Pluck Lead.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Main Room Pluck Lead.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Main Room Pluck Lead.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Pensive Pluck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Pensive Pluck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Pensive Pluck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Pensive Pluck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Simple Short Pluck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Simple Short Pluck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Simple Short Pluck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Simple Short Pluck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Sticky Percussion.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Sticky Percussion.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Sticky Percussion.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Sticky Percussion.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Synth Woodwind.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Synth Woodwind.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Synth Woodwind.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Synth Woodwind.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Tuned Metallic Click.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Tuned Metallic Click.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Tuned Metallic Click.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Tuned Metallic Click.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Bright Plucked String.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Bright Plucked String.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Bright Plucked String.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Bright Plucked String.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Percussive Pluck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Percussive Pluck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Percussive Pluck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Percussive Pluck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Short Synth Patterns.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Short Synth Patterns.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Short Synth Patterns.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Short Synth Patterns.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Noise Sweep.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Noise Sweep.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Noise Sweep.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Noise Sweep.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Bright Plucked String.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Percussive Pluck.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Short Synth Patterns.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Dark Heavy Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Solid Body Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Synth Upright Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Dirty Pulse.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Mutant Keys.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Short Swell Synth.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Synth Piano.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Time Warp Synth.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Wooden Keys.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Lead/Main Room Pluck Lead.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Mallets/Chimera Hammer.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Mallets/Hammered Mallets.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Mallets/Hammered Wood.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Mallets/Small Metal Box.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Mallets/Sticky Percussion.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Brassy Ensemble.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Warm Synth Pad.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Plucked/Pensive Pluck.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Plucked/Simple Short Pluck.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Plucked/Synth Woodwind.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Plucked/Tuned Metallic Click.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Noise Sweep.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Dembow Kit.exs",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Gozadera Latina.logicx/Alternatives/000/DisplayState.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Gozadera Latina.logicx/Alternatives/000/DisplayStateArchive",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Gozadera Latina.logicx/Alternatives/000/MetaData.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Gozadera Latina.logicx/Alternatives/000/ProjectData",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Gozadera Latina.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Gozadera Latina.logicx/Contents/Resources/template.tif",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Gozadera Latina.logicx/Contents/Resources/template_ios.png",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Gozadera Latina.logicx/Resources/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Gozadera Latina.logicx/Resources/ProjectInformation.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Reggaeton Pop Masher.logicx/Alternatives/000/DisplayState.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Reggaeton Pop Masher.logicx/Alternatives/000/DisplayStateArchive",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Reggaeton Pop Masher.logicx/Alternatives/000/MetaData.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Reggaeton Pop Masher.logicx/Alternatives/000/ProjectData",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Reggaeton Pop Masher.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Reggaeton Pop Masher.logicx/Contents/Resources/template.tif",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Reggaeton Pop Masher.logicx/Contents/Resources/template_ios.png",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Reggaeton Pop Masher.logicx/Resources/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Reggaeton Pop Masher.logicx/Resources/ProjectInformation.plist",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Abandoned Piano A#1-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/036_C1KM56_S-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/048_C2KM56_M-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Mutant KeysA0000-A.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Custom/Kal layer F d#3-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Custom/Marimba ln f l1x  4 d-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Custom/Sticky PercussionA0000-A.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Kalimba/Kalimba D2-ASF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Brassy EnsembleC0000-A.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Brassy EnsembleD0000-A.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Toy Percussion/Kitchen Sink 3-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Pensive PluckA0000-A.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Piano Egrand C1-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dembow Kit",
  ]
end
