cask "ml-0010-toybox" do
  version "38f2f1c232c3f15d52a8ae42913b5f3d-20"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0010_toybox/ml_0010_toybox.aar"
  name "ToyBox"
  desc "SoundEffectsPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0010_toybox/ml_0010_toybox.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0010_toybox.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "～/Music/Logic Pro Library.bundle/Apple Loops/Toy Box",
    "～/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0010_toybox.plist",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/03 Plate Reverbs/0.7s_Drum Plate.SDIR",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/Bongo170sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/Bongo270sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/CongaHigh170sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/CongaHigh270sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/CongaLow70sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/Crash70sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/Delay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/HiHat70sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/HiHatOpen70sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/Kick70sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/Reverb.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/Ride70sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/Rim170sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/Rim270sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/Snare170sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/Snare270sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/TomHigh70sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/70s Rhythm Box.patch/TomLow70sRhythmBox.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/BellKnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/BoomFXKnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/CrashKnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/Delay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/HiHat1KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/HiHat2KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/HiHatOpenKnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/Kick1KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/Kick2KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/PercFX1KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/PercFX2KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/PercFX3KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/PercFX4KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/PercFX5KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/PercFX6KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/PercFX7KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/Reverb.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/RimKnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/Shaker1KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/Shaker2KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/Snare1KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/Snare2KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/Snare3KnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/TomHighKnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/TomLowKnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Knick Knack.patch/TomMidKnickKnack.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Knick Knack.patch/com.apple.musicapps.intermediate.cache.zxml",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Knick Knack.patch/com.apple.musicapps.intermediate.cache.zxml",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bell - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bell - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bell - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bell - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo 1 - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo 1 - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo 1 - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo 1 - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo 2 - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo 2 - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo 2 - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo 2 - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga High 1 - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga High 1 - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga High 1 - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga High 1 - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga High 2 - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga High 2 - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga High 2 - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga High 2 - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga Low - 70s Rhythm Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga Low - 70s Rhythm Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga Low - 70s Rhythm Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga Low - 70s Rhythm Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 1 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 1 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 1 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 1 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 2 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 2 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 2 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 2 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 3 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 3 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 3 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 3 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 4 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 4 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 4 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 4 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 5 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 5 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 5 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 5 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 6 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 6 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 6 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 6 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 7 - Knick Knack.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 7 - Knick Knack.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 7 - Knick Knack.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 7 - Knick Knack.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pots and Pans.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pots and Pans.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pots and Pans.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pots and Pans.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Toy Piano.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Toy Piano.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Toy Piano.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Toy Piano.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Cheap Organ.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Cheap Organ.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Cheap Organ.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Cheap Organ.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Toy Melodica.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Toy Melodica.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Toy Melodica.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Toy Melodica.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Mini Marimba.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Mini Marimba.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Mini Marimba.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Mini Marimba.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Music Box.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Music Box.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Music Box.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Music Box.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Toy Celesta.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Toy Celesta.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Toy Celesta.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Toy Celesta.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Toy Glockenspiel.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Toy Glockenspiel.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Toy Glockenspiel.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Toy Glockenspiel.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Xylo Keyboard.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Xylo Keyboard.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Xylo Keyboard.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Xylo Keyboard.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Simple Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Simple Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Simple Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Simple Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Plastic Keys.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Plastic Keys.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Plastic Keys.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Plastic Keys.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/70s Rhythm Box.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Knick Knack Kit.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Percussion/Pots and Pans Kit.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Other/Toy Melodica.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Other/Toy Piano.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Mallet/Mini Marimba.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Mallet/Music Box.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Mallet/Toy Celesta.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Mallet/Toy Glockenspiel.exs",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Mallet/Xylo Keyboard.exs",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/70s Rhythm Box_consolidated.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Knick Knack Kit",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Pots and Pans Kit_consolidated.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Keyboard/Other/Toy Melodica_consolidated.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Keyboard/Other/Toy Piano_consolidated.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Mallet/Mini Marimba_consolidated.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Mallet/Music Box_consolidated.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Mallet/Toy Celesta_consolidated.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Mallet/Toy Glockenspiel_consolidated.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Mallet/Xylo Keyboard_consolidated.caf",
  ]
end
