cask "ml-0036-studiostrings" do
  version "3f6fe8ed789b5db63b67de7a26c38405-175"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0036_studiostrings/ml_0036_studiostrings.aar"
  name "StudioStrings"
  desc "InstrumentPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0036_studiostrings/ml_0036_studiostrings.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0036_studiostrings.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Closing Fast Strings 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Closing Fast Strings 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Closing Fast Strings 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Deep Undertone String Ensemble 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Deep Undertone String Ensemble 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Deep Undertone String Ensemble 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Disco Heat Descending Strings.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Disco Heat Rising Strings.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Disco Heat Staccato Strings 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Disco Heat Staccato Strings 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Disco Heat Staccato Strings 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Disco Heat String Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Disco Heat String Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Eastern Sun Staccato Strings.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Eastern Sun String Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Eastern Sun String Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Eastern Sun String Lead 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Eastern Sun String Lead 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Eastern Sun String Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Eastern Sun String Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Gaining Ground Staccato Strings 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Gaining Ground Staccato Strings 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Gaining Ground String Arp 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Gaining Ground String Arp 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Gaining Ground String Arp 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Gaining Ground String Arp 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Gaining Ground String Arp 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Gaining Ground String Arp 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Gaining Ground String Arp 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Gaining Ground String Run 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Gaining Ground String Run 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Gaining Ground String Run 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Gaining Ground String Run 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Hidden Clues Staccato Strings 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Hidden Clues Staccato Strings 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Hidden Clues String Arp 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Hidden Clues String Arp 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/High Hopes Pizzicato Strings 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/High Hopes Pizzicato Strings 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/High Hopes Pizzicato Strings 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/High Hopes Pizzicato Strings 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/High Hopes Pizzicato Strings 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/High Hopes String Ensemble.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/High Society Descending Strings.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/High Society String Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/High Society String Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/High Society String Lead 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/High Society String Lead 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/High Society String Trill 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/High Society String Trill 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/In a World Strings 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/In a World Strings 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Last Summer Staccato Strings.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Last Summer String Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Last Summer String Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Last Summer String Chords 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Last Summer String Chords 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Last Summer String Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Last Summer String Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Last Summer String Lead 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Last Summer String Lead 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Last Summer String Lead 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Last Summer String Sweep.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Midnight Disco String Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Midnight Disco String Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Midnight Disco String Lead 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Midnight Disco String Lead 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Midnight Disco String Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Midnight Disco String Trill.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Mischievous String Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Mischievous String Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Night Shimmer String Swell 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Night Shimmer String Swell 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Night Shimmer String Swell 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Night Shimmer String Swell 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Pensive Flow String Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Pensive Flow String Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Proving Ground Strings 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Proving Ground Strings 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Pure Drama String Ensemble.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Pure Drama String Trill 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Pure Drama String Trill 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Spirited Pizzicato Strings 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Spirited Pizzicato Strings 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Spirited Pizzicato Strings 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Spirited Pizzicato Strings 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Spirited Pizzicato Strings 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Spirited Pizzicato Strings 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Spirited Pizzicato Strings 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Suspended String Trill 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Suspended String Trill 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Suspended String Trill 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Suspended String Trill 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Studio Strings/Suspended String Trill 05.caf",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0036_studiostrings.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Abbey Wood.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Abbey Wood.patch/AbbeyWood.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Abbey Wood.patch/Cellos.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Abbey Wood.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Abbey Wood.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Abbey Wood.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Abbey Wood.patch/Violins1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Abbey Wood.patch/Violins2.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Bloomsbury.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Bloomsbury.patch/Bloomsbury.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Bloomsbury.patch/Cellos.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Bloomsbury.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Bloomsbury.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Bloomsbury.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Bloomsbury.patch/Violas.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Bloomsbury.patch/Violins1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Bloomsbury.patch/Violins2.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Eden Park.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Eden Park.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Eden Park.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Eden Park.patch/EdenPark.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Eden Park.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Eden Park.patch/Violins1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Eden Park.patch/Violins2.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Kensington.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Kensington.patch/Cellos.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Kensington.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Kensington.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Kensington.patch/Kensington.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Kensington.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Kensington.patch/Violins1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/Kensington.patch/Violins2.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/King's Cross.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/King's Cross.patch/Cellos.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/King's Cross.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/King's Cross.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/King's Cross.patch/DoubleBasses.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/King's Cross.patch/KingsCross.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/King's Cross.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/King's Cross.patch/Violas.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/King's Cross.patch/Violins1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Section Instruments/King's Cross.patch/Violins2.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Cellos.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Cellos.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Cellos.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Cellos.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Double Basses.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Double Basses.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Double Basses.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Double Basses.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Violas.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Violas.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Violas.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Violas.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Violins 1.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Violins 1.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Violins 1.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Violins 1.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Violins 2.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Violins 2.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Violins 2.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Strings/Studio Strings/Studio Violins 2.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Strings/Section Instruments/Disco Strings.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Strings/Section Instruments/Singer Songwriter.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Strings/Section Instruments/Small Section.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Strings/Section Instruments/String Ensemble.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Strings/Single Instruments/Studio Cellos.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Strings/Single Instruments/Studio Double Basses.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Strings/Single Instruments/Studio Violas.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Strings/Single Instruments/Studio Violins 1.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Strings/Single Instruments/Studio Violins 2.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Experimental/Expression Controlled Violin.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Experimental/Full Strings for Layers.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Experimental/Reverse Strings.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Experimental/Soft String Pad.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Experimental/Songwriter (Start with Bass Voice).pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Experimental/Songwriter (Start with Lead Voice).pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Experimental/String Machine.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Sections/Disco Strings.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Sections/Singer Songwriter.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Sections/Small Section.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Sections/String Ensemble.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Single Instruments/Studio Cellos.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Single Instruments/Studio Double Basses.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Single Instruments/Studio Violas.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Single Instruments/Studio Violins 1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Strings/Single Instruments/Studio Violins 2.pst",
    "~/Music/Logic Pro Library.bundle/Samples/Strings/Studio Strings/Studio Cellos_2_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Strings/Studio Strings/Studio Cellos_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Strings/Studio Strings/Studio Double Basses_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Strings/Studio Strings/Studio Violas_2_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Strings/Studio Strings/Studio Violas_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Strings/Studio Strings/Studio Violins 1_2_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Strings/Studio Strings/Studio Violins 1_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Strings/Studio Strings/Studio Violins 2_consolidated.caf",
  ]
end
