cask "ml-0039-quickalchemy" do
  version "1e45fbc0ca18bb46bc080f116409934e-18"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0039_quickalchemy/ml_0039_quickalchemy.aar"
  name "HybridTextures"
  desc "SampleAlchemyPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0039_quickalchemy/ml_0039_quickalchemy.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0039_quickalchemy.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/Hybrid Textures",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Ad Lib 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Oh Ah 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Ice Chill One Shot 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Sunbreak Oh Ah.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/z_Legacy/12 Chinese Traditional/Chinese Traditional Pipa 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/z_Legacy/12 Chinese Traditional/Guqin Tension.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/z_Legacy/12 Chinese Traditional/Storyteller Memories Daruan 01.caf",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0039_quickalchemy.plist",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/06 Spring Reverbs/02.8s Rack Spring Bright.SDIR",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Glass Bottle Arp.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Glass Bottle Arp.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Glass Bottle Arp.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Glass Bottle Arp.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Natural Pluck Arp.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Natural Pluck Arp.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Natural Pluck Arp.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Natural Pluck Arp.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Singing Bell Arp.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Singing Bell Arp.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Singing Bell Arp.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Singing Bell Arp.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Soft Metals.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Soft Metals.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Soft Metals.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Soft Metals.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Thought Patterns.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Thought Patterns.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Thought Patterns.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Thought Patterns.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Atmospheric Rhodes.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Atmospheric Rhodes.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Atmospheric Rhodes.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Atmospheric Rhodes.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Breathy Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Breathy Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Breathy Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Breathy Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Clicky Bowed Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Clicky Bowed Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Clicky Bowed Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Clicky Bowed Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dancing Tines.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dancing Tines.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dancing Tines.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dancing Tines.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fragile Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fragile Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fragile Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fragile Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Ghost Guitar Organ.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Ghost Guitar Organ.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Ghost Guitar Organ.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Ghost Guitar Organ.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Glass Harmonium.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Glass Harmonium.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Glass Harmonium.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Glass Harmonium.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Grainy Xylo Organ.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Grainy Xylo Organ.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Grainy Xylo Organ.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Grainy Xylo Organ.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Icicle Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Icicle Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Icicle Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Icicle Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Jitter Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Jitter Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Jitter Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Jitter Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Kalimba Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Kalimba Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Kalimba Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Kalimba Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Lo-Fi Land Vibes.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Lo-Fi Land Vibes.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Lo-Fi Land Vibes.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Lo-Fi Land Vibes.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Paper Pluck Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Paper Pluck Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Paper Pluck Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Paper Pluck Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Piano Air Curls.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Piano Air Curls.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Piano Air Curls.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Piano Air Curls.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Piano Fragments.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Piano Fragments.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Piano Fragments.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Piano Fragments.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Picked Organ.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Picked Organ.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Picked Organ.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Picked Organ.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Pseudo Octave Tines.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Pseudo Octave Tines.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Pseudo Octave Tines.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Pseudo Octave Tines.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Sand Dune Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Sand Dune Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Sand Dune Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Sand Dune Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Shaky Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Shaky Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Shaky Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Shaky Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Soft Tines.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Soft Tines.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Soft Tines.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Soft Tines.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Tine Tonespace.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Tine Tonespace.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Tine Tonespace.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Tine Tonespace.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Unsettled Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Unsettled Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Unsettled Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Unsettled Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Vibe Tines.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Vibe Tines.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Vibe Tines.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Vibe Tines.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Water Jug Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Water Jug Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Water Jug Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Water Jug Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Wooden Plank Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Wooden Plank Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Wooden Plank Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Wooden Plank Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Burnt Vox Lead.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Burnt Vox Lead.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Burnt Vox Lead.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Burnt Vox Lead.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Pots and Pans Lead.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Pots and Pans Lead.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Pots and Pans Lead.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Pots and Pans Lead.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Granular Kalimba Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Granular Kalimba Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Granular Kalimba Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Granular Kalimba Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Pensive Meditation Bell.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Pensive Meditation Bell.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Pensive Meditation Bell.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Pensive Meditation Bell.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Rattling Bell Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Rattling Bell Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Rattling Bell Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Rattling Bell Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Shimmering Star Chimes.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Shimmering Star Chimes.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Shimmering Star Chimes.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Shimmering Star Chimes.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Active Piano Rolls.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Active Piano Rolls.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Active Piano Rolls.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Active Piano Rolls.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Airy Vocal Shimmer.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Airy Vocal Shimmer.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Airy Vocal Shimmer.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Airy Vocal Shimmer.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Bowed Vocal Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Bowed Vocal Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Bowed Vocal Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Bowed Vocal Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Creaky Daruan Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Creaky Daruan Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Creaky Daruan Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Creaky Daruan Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Echoing Swarms Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Echoing Swarms Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Echoing Swarms Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Echoing Swarms Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Guitar Orchestra Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Guitar Orchestra Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Guitar Orchestra Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Guitar Orchestra Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Rattling Piano Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Rattling Piano Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Rattling Piano Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Rattling Piano Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Stepped Octave Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Stepped Octave Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Stepped Octave Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Stepped Octave Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Subtle Friction Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Subtle Friction Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Subtle Friction Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Subtle Friction Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Swelling Steam Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Swelling Steam Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Swelling Steam Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Swelling Steam Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Unstable Machine Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Unstable Machine Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Unstable Machine Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Unstable Machine Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Air Brakes Pluck.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Air Brakes Pluck.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Air Brakes Pluck.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Air Brakes Pluck.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Chattering Bells.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Chattering Bells.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Chattering Bells.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Chattering Bells.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Dark Gate Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Dark Gate Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Dark Gate Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Dark Gate Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Grain Silo.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Grain Silo.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Grain Silo.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Grain Silo.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Granular Shaker Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Granular Shaker Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Granular Shaker Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Granular Shaker Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Hammered Octaves.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Hammered Octaves.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Hammered Octaves.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Hammered Octaves.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Mixed Up Voices.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Mixed Up Voices.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Mixed Up Voices.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Mixed Up Voices.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Resonant Guqin Ostinato.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Resonant Guqin Ostinato.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Resonant Guqin Ostinato.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Resonant Guqin Ostinato.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Tuned Hydraulics.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Tuned Hydraulics.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Tuned Hydraulics.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Tuned Hydraulics.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Caffeinated Wurli.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Caffeinated Wurli.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Caffeinated Wurli.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Caffeinated Wurli.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Distorted Whoops.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Distorted Whoops.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Distorted Whoops.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Distorted Whoops.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Marble Drops.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Marble Drops.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Marble Drops.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Marble Drops.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Piano Crumbles.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Piano Crumbles.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Piano Crumbles.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Piano Crumbles.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Whimsical Tines Improv.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Whimsical Tines Improv.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Whimsical Tines Improv.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Whimsical Tines Improv.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Glacial Pressure.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Glacial Pressure.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Glacial Pressure.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Glacial Pressure.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Micro Organisms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Micro Organisms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Micro Organisms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Micro Organisms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Palpable Tension.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Palpable Tension.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Palpable Tension.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Palpable Tension.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Peaceful Anticipation.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Peaceful Anticipation.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Peaceful Anticipation.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Peaceful Anticipation.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Pipa Spider Drone.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Pipa Spider Drone.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Pipa Spider Drone.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Pipa Spider Drone.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Radiant Aftermath Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Radiant Aftermath Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Radiant Aftermath Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Radiant Aftermath Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Radioactive Decay.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Radioactive Decay.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Radioactive Decay.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Radioactive Decay.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Sheet Metals.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Sheet Metals.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Sheet Metals.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Sheet Metals.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Well Rested Chimes.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Well Rested Chimes.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Well Rested Chimes.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Well Rested Chimes.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Arpeggiated/Custom/Glass Bottle Arp",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Arpeggiated/Custom/Singing Bell Arp",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Arpeggiated/Custom/Soft Metals",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Arpeggiated/Custom/Thought Patterns",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Single Samples/Banjo Octave Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Single Samples/Funk Pluck 03.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Single Samples/Guitar Note 02.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Single Samples/Muted Guitar Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Single Samples/Noisy Guitar Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Acoustic Pianos/Deep Piano Harmonic.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Acoustic Pianos/Deep Piano Octaves.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Acoustic Pianos/Dune Piano C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Acoustic Pianos/Ebow Piano 04.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Acoustic Pianos/Piano Air Curls C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Acoustic Pianos/Piano Fragments C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Acoustic Pianos/Piano Harmonic 02.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Acoustic Pianos/Piano Harmonic 06.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Acoustic Pianos/Piano Hit 02.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Acoustic Pianos/Piano Octaves.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Acoustic Pianos/Piano Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Acoustic Pianos/Piano Soft Hit 03.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Acoustic Pianos/Ring Piano C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Acoustic Pianos/Soft Piano Octaves.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Breathy Keys",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Clicky Bowed Keys",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Dancing Tines",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Fragile Keys",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Ghost Guitar Organ",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Glass Harmonium",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Grainy Xylo Organ",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Lo-Fi Land Vibes",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Paper Pluck Keys",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Piano Air Curls",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Picked Organ",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Pseudo Octave Tines",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Soft Tines",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Unsettled Keys",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Vibe Tines",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Wooden Plank Keys",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Electric Pianos/Noisy EPiano.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Electric Pianos/Tine Tonespace C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Electric Pianos/Whurli Improv 07.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Electric Pianos/Whurli Improv 13.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Dark Piano.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Leads/Custom/Burnt Vox Lead",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Leads/Custom/Pots and Pans Lead",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Custom/Pensive Meditation Bell",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Custom/Rattling Bell Pad",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Bellrack Dissonance.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Indian Bell.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Noise Chimes.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Singing Bowl Ringing.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Soft Heliopan 05.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Soft Heliopan 06.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Xylo Dirty C3 03.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Xylo Dirty C3 24.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Xylo Dirty C3 32.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Kalimba Space C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Mini Kalimba 03.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Star Chimes.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Airy Vocal Shimmer/Airy Vocal ShimmerA0000-Ruby No Fight Oh Ah 02-SF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Bowed Vocal Pad/Bowed Vocal PadC0000-Zoe Sunbreak Oh Ah-SF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Creaky Daruan Pad/Creaky Daruan PadB0000-Storyteller Memories Daruan 01-SF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Creaky Daruan Pad/Creaky Daruan PadC0000-Storyteller Memories Daruan 01-A.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Echoing Swarms Pad/Echoing Swarms PadB0000-Funk Pluck 03-SF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Guitar Orchestra Pad/Guitar Orchestra PadC0000-Noisy Guitar Plucks-SF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Stepped Octave Piano/Stepped Octave PianoA0000-Piano Octaves-A.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Subtle Friction Pad/Subtle Friction PadB0000-Metal Friction 05-A.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Swelling Steam Pad/Swelling Steam PadA0000-Xylo Dirty C3 32-SF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Unstable Machine Pad/Unstable Machine PadB0000-Metal Resonance-A.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Rhythmic/Custom/Resonant Guqin Ostinato/Resonant Guqin OstinatoB0000-Guqin Tension-SF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Ambience City/Train Brakes Passing.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Distorted Whoops",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Marble Drops",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Custom/Piano Crumbles",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Foley/Bouncing Glass.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Foley/Metal Friction 05.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Foley/Metal Resonance.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Foley/Metal Scraping 01.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Foley/Water Cooler 05.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Foley/Water Flask Hit.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Instruments/Chime Grain Texture 02.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Instruments/Granular Chimes 07.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Instruments/Granular Chimes 08.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Instruments/Granular Chimes 09.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Natural/Hydrophone Fizzing.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Natural/Hydrophone Melting Ice.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Circuit Coil Disc Player 11.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Toy Percussion/Distorted Tambourine.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Toy Percussion/Sleigh Bell.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Toy Percussion/Toy Rattle Shaker.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Glacial Pressure",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Pipa Spider Drone",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Radiant Aftermath Pad",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Radioactive Decay",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Sheet Metals",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Well Rested Chimes",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Real Strings/Bowed Dulcimer 01.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Real Strings/Bowed Dulcimer 03.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Real Strings/Bowed Sitar FX 02.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Real Strings/Cello A C# D E.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Delicate Synth 03.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Synth Leaking Pipe.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Synth Plucked Tension.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal FX And Noises/Ruby Word Chop Ab.caf",
  ]
end
