cask "ml-0041-sessionplayersbass" do
  version "8bba4fdad12786ba6ed2e15225c2f2ab-559"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0041_sessionplayersbass/ml_0041_sessionplayersbass.aar"
  name "StudioBasses"
  desc "SessionPlayerPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0041_sessionplayersbass/ml_0041_sessionplayersbass.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0041_sessionplayersbass.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/60s Songwriter Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/60s Songwriter Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/60s Songwriter Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/60s Songwriter Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Always the Same Bridge Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Always the Same Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Always the Same Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Brighter Illusion Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Brighter Illusion Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/By the Fire Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Candy Coupe Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Central Park Bass Solo.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Central Park Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Central Park High Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Concrete Below Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Intro Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desperate Love Bridge Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desperate Love Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desperate Love Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Dreams of Neon Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Echo Chamber Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Echo Chamber Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/End of the Road Bridge Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/End of the Road Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/End of the Road Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Experimental Songwriter Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Experimental Songwriter Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Experimental Songwriter Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Experimental Songwriter Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Experimental Songwriter Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Falling Fast Bridge Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Falling Fast Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Falling Fast Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Flying Beyond Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Forever Disco Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Friday Night Drive Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Friday Night Drive Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funk Rock Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funk Rock Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funk Rock Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funk Rock Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funk Rock Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funk Rock Bass 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Bass 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Bass 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Funky Songwriter Bass 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Galactic Guide Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Garage Rock Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Garage Rock Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Garage Rock Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Garage Rock Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Garage Rock Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Garage Rock Bass 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Gliding Away Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Gliding Away Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Hard Rock Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Hard Rock Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Hard Rock Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Bass 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Bass 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Bass 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Disco Bass 09.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Pop Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Pop Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Pop Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Pop Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Pop Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Rock Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Rock Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Rock Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Indie Rock Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Inline Skates Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Inline Skates Synth Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Just What You Needed Bridge Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Just What You Needed Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Just What You Needed Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lets Go Tonight Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lo-Fi Summer Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lo-Fi Summer Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lost and Found Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lost and Found Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Mean Streets Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern Motown Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern Motown Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern Motown Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern Motown Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern Motown Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern R&B Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern R&B Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern R&B Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern R&B Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern R&B Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern R&B Bass 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modern R&B Bass 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Bass 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Bass 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Bass 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neo Soul Bass 09.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/New York Nights Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Notes on Top Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Notes on Top Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Paint it Blue Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Paint it Blue Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Rock Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Rock Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Rock Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Rock Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Songwriter Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Songwriter Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Songwriter Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Songwriter Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Upright Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Upright Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Upright Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Upright Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pop Upright Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Psychedelic Rock Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Psychedelic Rock Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Psychedelic Rock Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Psychedelic Rock Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Punk Rock Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Punk Rock Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Punk Rock Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Retro Rock Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Retro Rock Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Retro Rock Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Retro Rock Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Retro Rock Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Retro Rock Bass 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Songwriter Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Songwriter Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Songwriter Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Songwriter Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Songwriter Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Upright Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Upright Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Upright Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Upright Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Upright Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Upright Bass 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Roots Upright Bass 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sixties Nostalgia Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/SoCal Sun Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Summertime Breeze Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Summertime Breeze Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Switching Lights Upright Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Thick Syrup Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Turned Around Bridge Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Turned Around Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Turned Around Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Twilight Rising Bridge Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Twilight Rising Bridge Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Twilight Rising Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Twilight Rising Chorus Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Twilight Rising Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Twilight Rising Verse Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Velvet Dreams Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Velvet Dreams Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Vision of Beauty Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Vision of Beauty Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Wilted Roses Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Witty Vibes Bridge Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Witty Vibes Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Witty Vibes Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0041_sessionplayersbass.plist",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/03 Plate Reverbs/2.3s_Nice Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/02.6s Hansa Studio-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/07 Indoor Spaces/1.1s_Big Club Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.4s_Little Room.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.4s_Snare Chamber.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/00.6s Drum Booth Four-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Club Ambience Upright.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Club Ambience Upright.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Club Ambience Upright.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Club Ambience Upright.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Coffee Shop Monstera.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Coffee Shop Monstera.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Coffee Shop Monstera.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Coffee Shop Monstera.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Contemporary Soul.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Contemporary Soul.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Contemporary Soul.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Contemporary Soul.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Crunchy Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Crunchy Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Crunchy Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Crunchy Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Crunchy Vintage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Crunchy Vintage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Crunchy Vintage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Crunchy Vintage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dance Clean.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dance Clean.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dance Clean.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dance Clean.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dance Swirls.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dance Swirls.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dance Swirls.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dance Swirls.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dancefloor.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dancefloor.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dancefloor.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dancefloor.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dark Soul.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dark Soul.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dark Soul.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Dark Soul.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Distant Vibe.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Distant Vibe.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Distant Vibe.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Distant Vibe.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Envelope.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Envelope.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Envelope.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Envelope.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Focused Sixties.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Focused Sixties.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Focused Sixties.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Focused Sixties.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Fuzzy.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Fuzzy.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Fuzzy.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Fuzzy.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Lo-Fi Tape Upright.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Lo-Fi Tape Upright.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Lo-Fi Tape Upright.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Lo-Fi Tape Upright.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Psychedelic Rock.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Psychedelic Rock.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Psychedelic Rock.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Psychedelic Rock.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Punchy Bottom.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Punchy Bottom.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Punchy Bottom.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Punchy Bottom.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Retro Crunch.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Retro Crunch.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Retro Crunch.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Retro Crunch.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Retro Radio.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Retro Radio.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Retro Radio.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Retro Radio.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Rock Growl.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Rock Growl.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Rock Growl.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Rock Growl.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Rock Legend.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Rock Legend.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Rock Legend.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Rock Legend.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Roots Upright.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Roots Upright.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Roots Upright.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Roots Upright.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Simple Foundation.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Simple Foundation.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Simple Foundation.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Simple Foundation.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Slap & Pop Dark.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Slap & Pop Dark.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Slap & Pop Dark.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Slap & Pop Dark.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Slap & Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Slap & Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Slap & Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Slap & Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Swirling.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Swirling.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Swirling.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Swirling.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Vintage Soul.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Vintage Soul.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Vintage Soul.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Vintage Soul.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Warm & Clear.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Warm & Clear.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Warm & Clear.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Warm & Clear.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Wide Rock.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Wide Rock.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Wide Rock.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Wide Rock.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Studio Bass",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Studio Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Bass/Studio Bass/American Upright",
    "~/Music/Logic Pro Library.bundle/Samples/Bass/Studio Bass/Classic Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Bass/Studio Bass/Modern Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Bass/Studio Bass/Rock Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Bass/Studio Bass/Session Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Bass/Studio Bass/Sixties Bass",
  ]
end
