cask "ml-0020-keyboardcollection" do
  version "f29d89e6972bff1a250a3373647da12a-24"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0020_keyboardcollection/ml_0020_keyboardcollection.aar"
  name "KeyboardCollection"
  desc "KeyboardSoundPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0020_keyboardcollection/ml_0020_keyboardcollection.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0020_keyboardcollection.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/80s Ballad Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/80s Ballad Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/80s Ballad Chords 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Angel Ballet Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Anthemic Keys 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Anthemic Keys 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Anthemic Keys 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Aqua Shimmer Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Around the Bend Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Ballpark Jam Organ.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Blue Hour Keys 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Blue Hour Keys 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Bookstore Browse Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Born Brave Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Born Brave Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Bradbury Building Hotel Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Bright Pop Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Brilliant Rain Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Careful Calculations Organ.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Challenging Level Organ.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Changing Tide Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Charming Recital Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Check and Balance Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Chicago House Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Chorused Tines.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/City Trail Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Comb The World Clav.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Confident Pop Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Confident Progression Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Contemplation Bells.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Counteract Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Dancing Pulse Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Dependable Chord Marimba 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Dependable Chord Marimba 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Dependable Chord Marimba 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Dependable Chord Marimba 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Dependable Chord Marimba 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Dependable Chord Marimba 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Detuned Progression Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Dirty Backbeat Clav.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Electromagnetic Keys 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Electromagnetic Keys 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Elegant Spin Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Elegant Spin Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/End of the Tunnel Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Endless Lullaby Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Endless Memories Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Epic Ballad Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Epic Pop Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Evening Stroll Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Familiar Changes Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Fast Forward Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Festive Bazaar Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Fleeting Moment Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Garden Party Keys 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Garden Party Keys 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Granular Chord Vibraphone.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Growing Up Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Hard to Find Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Hard to Find Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Hard to Find Piano 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Hard to Find Piano 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Hard to Hold Clav.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Higher Calling Marimba.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Honest Intention Electric Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Honest Intention Electric Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Idea Forming Clav 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Idea Forming Clav 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/In Alignment Electric Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/In Alignment Electric Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Instant Hit Chord Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Lavender Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Like Clockwork Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Lofty Goals Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Lost In Thought Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Lost In Thought Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Lost Time Synth Melody 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Lost Time Synth Melody 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Lost Time Synth Melody 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Lost Time Synth Melody 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Lost Time Synth Melody 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Magic Motif Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Magical Glissando Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Make History Electric Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Make History Electric Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Mechanized Motion Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Mellow Clav Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Mellow Clav Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Midnight Lounge Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Midnight Thoughts Electric Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Midnight Thoughts Electric Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Mix and Serve Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Mood Lighting Keys 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Mood Lighting Keys 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Mood Lighting Keys 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Morning Dew Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Moving On Electric Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Moving On Electric Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Moving On Electric Piano 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Moving Up Vibes.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Night Vision Synth 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Night Vision Synth 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Old Documentary Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Open Road Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Open Road Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Optical Illusion Organ 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Optical Illusion Organ 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Optical Illusion Organ 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Optical Illusion Organ 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Origin Story Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Passing By Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Passing Fancy Vibes.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Passion for Groove Clav.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Passive Glow Melody Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Perfect Intro Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Pop Sensibility Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Positive Thinking Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Practised Scale Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Premonitions Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Progressive Pop Keys 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Progressive Pop Keys 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Reflection Synth Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Retrospective Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Retrospective Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Right Vibe Wah Clav 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Right Vibe Wah Clav 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Roller Rink Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Rolling Right Synth Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Ruminating Pattern Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Savanna Sun Mallet 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Savanna Sun Mallet 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Sentimental Journey Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Simple Minor Drip Keys 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Simple Minor Drip Keys 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Simple Staccato Clav.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Slow Descent Organ.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Snuck Up Chord Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Snuck Up Chord Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Staccato Pop Organ.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Stay a While Synth Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Stay a While Synth Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Stepping It Up Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Summer Breeze Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Sunrise Keys 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Sunrise Keys 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Supergroup Riff Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Suspense in Motion Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Swinging Sine Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Tears In Rain Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Top-line Ready Vibes.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Troubled Waters Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Trusted Friend Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Uplifting Spirit Keys 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Uplifting Spirit Keys 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Uplifting Spirit Keys 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Uplifting Spirit Keys 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Watercolor Paint Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Waterpark Fun Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/What's Good Xylophone 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/What's Good Xylophone 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Without Question Organ.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Won't Give Up Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Won't Give Up Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Keyboard Collection/Younger Days Synth.caf",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0020_keyboardcollection.plist",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/03.9s Prince Hall One-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/02.6s Hansa Studio-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/01.0s Villa Bathroom-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/03 Plate Reverbs/1.3s_Nice Small Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Pop Producer Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Pop Producer Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Pop Producer Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Pop Producer Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Amplified Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Amplified Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Amplified Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Amplified Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Below The Surface Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Below The Surface Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Below The Surface Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Below The Surface Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Boogie Man Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Boogie Man Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Boogie Man Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Boogie Man Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Learner's Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Learner's Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Learner's Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Learner's Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Mellow Vibe Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Mellow Vibe Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Mellow Vibe Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Mellow Vibe Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Muted Clank Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Muted Clank Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Muted Clank Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Muted Clank Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Old-Time Recording Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Old-Time Recording Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Old-Time Recording Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Old-Time Recording Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Parallel Earth Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Parallel Earth Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Parallel Earth Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Parallel Earth Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Record Collection Grand.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Record Collection Grand.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Record Collection Grand.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Record Collection Grand.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Rise Above Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Rise Above Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Rise Above Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Rise Above Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Subtle Dynamics Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Subtle Dynamics Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Subtle Dynamics Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Subtle Dynamics Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Worn Tape Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Worn Tape Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Worn Tape Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Worn Tape Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Chilled Clav.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Chilled Clav.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Chilled Clav.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Chilled Clav.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Digging Deeper Clav.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Digging Deeper Clav.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Digging Deeper Clav.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Digging Deeper Clav.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Guitar vs Clav.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Guitar vs Clav.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Guitar vs Clav.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Guitar vs Clav.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Muted Clav.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Muted Clav.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Muted Clav.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Muted Clav.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Nice Dream Clav.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Nice Dream Clav.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Nice Dream Clav.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Nice Dream Clav.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Novel Approach Clav.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Novel Approach Clav.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Novel Approach Clav.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Novel Approach Clav.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Processed/Claverotor.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Processed/Claverotor.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Processed/Claverotor.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Processed/Claverotor.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Processed/Different Phases Clav.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Processed/Different Phases Clav.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Processed/Different Phases Clav.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Processed/Different Phases Clav.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Wah-Wah Clav.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Wah-Wah Clav.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Wah-Wah Clav.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Wah-Wah Clav.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Double Tracked Wurli.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Double Tracked Wurli.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Double Tracked Wurli.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Double Tracked Wurli.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Electromagnetic Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Electromagnetic Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Electromagnetic Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Electromagnetic Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Flea Market Wurli.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Flea Market Wurli.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Flea Market Wurli.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Flea Market Wurli.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Flying Circus Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Flying Circus Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Flying Circus Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Flying Circus Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Phasing Bells.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Phasing Bells.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Phasing Bells.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Phasing Bells.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Powered Tube Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Powered Tube Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Powered Tube Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Powered Tube Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/80s Signature Keyboard.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/80s Signature Keyboard.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/80s Signature Keyboard.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/80s Signature Keyboard.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Feedback Rhodes.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Feedback Rhodes.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Feedback Rhodes.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Feedback Rhodes.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Instant Hook Wurli.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Instant Hook Wurli.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Instant Hook Wurli.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Instant Hook Wurli.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Pure Digital Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Pure Digital Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Pure Digital Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Pure Digital Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Supporting Cast Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Supporting Cast Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Supporting Cast Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Supporting Cast Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Synthetic Wurli.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Synthetic Wurli.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Synthetic Wurli.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Synthetic Wurli.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Blips Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Blips Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Blips Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Blips Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Fixer Upper Organ.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Fixer Upper Organ.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Fixer Upper Organ.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Fixer Upper Organ.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Gamer's Organ.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Gamer's Organ.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Gamer's Organ.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Gamer's Organ.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Industrial Design Organ.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Industrial Design Organ.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Industrial Design Organ.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Industrial Design Organ.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Lullaby Vibes.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Lullaby Vibes.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Lullaby Vibes.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Lullaby Vibes.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Processed/80s Chime Vibe.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Processed/80s Chime Vibe.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Processed/80s Chime Vibe.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Processed/80s Chime Vibe.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Processed/Hit Record Marimba.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Processed/Hit Record Marimba.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Processed/Hit Record Marimba.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Processed/Hit Record Marimba.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Taped Marimba.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Taped Marimba.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Taped Marimba.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Taped Marimba.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/80s Bitrate Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/80s Bitrate Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/80s Bitrate Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/80s Bitrate Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/80s Sine Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/80s Sine Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/80s Sine Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/80s Sine Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/80s Wave Bells.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/80s Wave Bells.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/80s Wave Bells.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/80s Wave Bells.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Big Dripper.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Big Dripper.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Big Dripper.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Big Dripper.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Electric Sheep Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Electric Sheep Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Electric Sheep Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Electric Sheep Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fairytales Bells.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fairytales Bells.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fairytales Bells.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fairytales Bells.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Granular Vibraphone.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Granular Vibraphone.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Granular Vibraphone.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Granular Vibraphone.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Liquid Synth Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Liquid Synth Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Liquid Synth Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Liquid Synth Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/More Modulation Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/More Modulation Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/More Modulation Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/More Modulation Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/New Carnival Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/New Carnival Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/New Carnival Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/New Carnival Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Old VHS Tape Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Old VHS Tape Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Old VHS Tape Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Old VHS Tape Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Perfect Mix Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Perfect Mix Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Perfect Mix Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Perfect Mix Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Reversing Mood Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Reversing Mood Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Reversing Mood Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Reversing Mood Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Rusty Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Rusty Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Rusty Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Rusty Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Simple Physics Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Simple Physics Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Simple Physics Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Simple Physics Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Other/Pop Producer Keys.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Amplified Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Below The Surface Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Boogie Man Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Learner's Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Mellow Vibe Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Muted Clank Keys.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Old-Time Recording Keys.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Parallel Earth Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Record Collection Grand.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Rise Above Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Subtle Dynamics Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Worn Tape Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Clavinet/Processed/Claverotor.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Clavinet/Processed/Different Phases Clav.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Electric Piano/Other/Double Tracked Wurli.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Electric Piano/Other/Electromagnetic Keys.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Electric Piano/Other/Flea Market Wurli.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Electric Piano/Other/Powered Tube Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Electric Piano/Other/Pure Digital Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Electric Piano/Other/Supporting Cast Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Electric Piano/Processed/80s Signature Keyboard.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Electric Piano/Processed/Feedback Rhodes.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Organ/Processed/Gamer's Organ.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Organ/Processed/Industrial Design Organ.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Mallet/Other/Lullaby Vibes.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Mallet/Other/Taped Marimba.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Mallet/Processed/80s Chime Vibe.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Mallet/Processed/Hit Record Marimba.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/80s Bitrate Synth.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Electric Sheep Synth.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Fairytales Bells.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Granular Vibraphone.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Liquid Synth Keys.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/More Modulation Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/New Carnival Synth.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Old VHS Tape Synth.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Perfect Mix Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Reversing Mood Keys.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Rusty Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Simple Physics Piano.exs",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Classical Grand_consolidated_h.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Grand Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Amplified Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Below The Surface Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Boogie Man Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Learner's Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Mellow Vibe Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Muted Clank Keys_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Old-Time Recording Keys_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Parallel Earth Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Rise Above Piano/Rise Above Click.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Rise Above Piano/Rise Above Pluck.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Subtle Dynamics Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Worn Tape Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Clavinet/Processed/Claverotor_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Clavinet/Processed/Different Phases Clav_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Electric Piano/Other/Electromagnetic Keys_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Electric Piano/Other/Flea Market Wurli_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Electric Piano/Other/Powered Tube Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Electric Piano/Other/Pure Digital Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Electric Piano/Other/Supporting Cast Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Electric Piano/Processed/80s Signature Keyboard_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Electric Piano/Processed/Feedback Rhodes_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Organ/Processed/Gamer's Organ_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Organ/Processed/Industrial Design Organ_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Mallet/Other/Lullaby Vibes_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Mallet/Other/Taped Marimba_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Mallet/Processed/80s Chime Vibe_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Mallet/Processed/Hit Record Marimba_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/80s Bitrate Synth_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Electric Sheep Synth_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Fairytales Bells_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Granular Vibraphone_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Liquid Synth Keys_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/More Modulation Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/New Carnival Synth_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Old VHS Tape Synth_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Perfect Mix Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Reversing Mood Keys_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Rusty Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Simple Physics Piano_2_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Simple Physics Piano_consolidated.caf",
  ]
end
