cask "ml-0005-futurebass" do
  version "1bd82424b1a30ce22c25a70b4ae79b88-14"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0005_futurebass/ml_0005_futurebass.aar"
  name "EdgesandAngles"
  desc "FutureBassPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0005_futurebass/ml_0005_futurebass.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0005_futurebass.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "～/Music/Logic Pro Library.bundle/Apple Loops/Edges and Angles",
    "～/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0005_futurebass.plist",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/03 Plate Reverbs/2.2s_Ramp Plate.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/6.6s_Palace.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/03 Plate Reverbs/0.7s_Drum Plate.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/02 Moving Spaces/Moving Space 32.aif",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/06 Speakers/Amp Cabinet Speaker 16.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/07 Analog Circuits/Clean Console.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/07 Analog Circuits/Vintage Semi Modular.SDIR",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/ClapInfinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/CrashInfinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/Delay.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/HiHat1Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/HiHat2Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/HiHatOpenInfinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/Kick1Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/Kick2Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/Perc1Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/Perc2Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/Perc3Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/Reverb.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/RideInfinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/Shaker1Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/Shaker2Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/Snare1Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/Snare2Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/Snare3Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/Snare4Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/Snare5Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/TomHighInfinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/TomLowInfinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/TomMidInfinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/WoodblockInfinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/ZoneFX1Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Infinity.patch/ZoneFX2Infinity.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 5 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 5 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 5 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 5 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Infinity.patch/com.apple.musicapps.intermediate.cache.zxml",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Infinity.patch/com.apple.musicapps.intermediate.cache.zxml",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 3 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 3 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 3 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 3 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Zone FX 1 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Zone FX 1 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Zone FX 1 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Zone FX 1 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Zone FX 2 - Infinity.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Zone FX 2 - Infinity.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Zone FX 2 - Infinity.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Zone FX 2 - Infinity.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Blooming Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Blooming Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Blooming Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Blooming Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Thump Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Thump Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Thump Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Thump Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Heavy Buzz Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Heavy Buzz Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Heavy Buzz Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Heavy Buzz Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Massive Wobble Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Massive Wobble Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Massive Wobble Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Massive Wobble Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Talking Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Talking Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Talking Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Talking Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Thick Liquid Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Thick Liquid Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Thick Liquid Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Thick Liquid Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Classic Super Saw.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Classic Super Saw.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Classic Super Saw.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Classic Super Saw.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/7th Player.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/7th Player.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/7th Player.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/7th Player.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Anthemic Lead.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Anthemic Lead.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Anthemic Lead.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Anthemic Lead.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Bending Lead.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Bending Lead.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Bending Lead.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Bending Lead.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Crackling Lead.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Crackling Lead.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Crackling Lead.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Crackling Lead.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Hard Metal Lead.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Hard Metal Lead.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Hard Metal Lead.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Hard Metal Lead.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/High Energy Lead.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/High Energy Lead.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/High Energy Lead.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/High Energy Lead.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Tight Punchy Lead.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Tight Punchy Lead.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Tight Punchy Lead.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Tight Punchy Lead.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Future Strings.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Future Strings.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Future Strings.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Future Strings.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Rising Waves.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Rising Waves.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Rising Waves.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Rising Waves.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Mech Riser.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Mech Riser.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Mech Riser.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Mech Riser.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Swirling Riser.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Swirling Riser.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Swirling Riser.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Swirling Riser.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Blooming Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Deep Thump Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Heavy Buzz Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Massive Wobble Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Sub Dropper.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Talking Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Thick Liquid Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Classic Super Saw.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Lead/7th Player.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Lead/Anthemic Lead.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Lead/Bending Lead.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Lead/Crackling Lead.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Lead/Hard Metal Lead.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Lead/High Energy Lead.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Lead/Massive Glide Lead.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Lead/Tight Punchy Lead.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Rhythmic/Rising Waves.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Mech Riser.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Swirling Riser.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Strings/Future Strings.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Infinity Kit.exs",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Edges and Angles.logicx/Alternatives/000/DisplayState.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Edges and Angles.logicx/Alternatives/000/DisplayStateArchive",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Edges and Angles.logicx/Alternatives/000/MetaData.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Edges and Angles.logicx/Alternatives/000/ProjectData",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Edges and Angles.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Edges and Angles.logicx/Contents/Resources/template.tif",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Edges and Angles.logicx/Contents/Resources/template_ios.png",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Edges and Angles.logicx/Resources/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Edges and Angles.logicx/Resources/ProjectInformation.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Future Bass Masher.logicx/Alternatives/000/DisplayState.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Future Bass Masher.logicx/Alternatives/000/DisplayStateArchive",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Future Bass Masher.logicx/Alternatives/000/MetaData.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Future Bass Masher.logicx/Alternatives/000/ProjectData",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Future Bass Masher.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Future Bass Masher.logicx/Contents/Resources/template.tif",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Future Bass Masher.logicx/Contents/Resources/template_ios.png",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Future Bass Masher.logicx/Resources/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Future Bass Masher.logicx/Resources/ProjectInformation.plist",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Formant Sweep Slow C1-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Formant Sweep Slow C1-AF_1.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Wrong C1-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Clap_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Crash_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Foley_1_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Foley_2_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Foley_3_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Hi-Hat_1_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Hi-Hat_2_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Hi-Hat_3_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Kick_1_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Kick_2_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Perc_1_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Perc_2_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Ride_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Rim_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Shaker_1_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Shaker_2_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Snare_1_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Snare_2_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Snare_3_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Snare_4_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Snare_5_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Tom_High_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Tom_Low_Infinity.aif",
    "～/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Infinity Kit/Tom_Mid_Infinity.aif",
  ]
end
