cask "ml-0024-modernambient" do
  version "fa940bc7cd9cbda443e3afb66a62023f-38"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0024_modernambient/ml_0024_modernambient.aar"
  name "AlphaWaves"
  desc "ModernAmbientPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0024_modernambient/ml_0024_modernambient.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0024_modernambient.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Abstract Memories 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Abstract Memories 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Analog Infinity 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Analog Infinity 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Analog Infinity 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Autumn Brushes.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Beckoning Bells 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Beckoning Bells 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Bedtime Stories.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Billowing Breeze.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Brain Waves.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Breathless Speech.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Calming Noise 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Calming Noise 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Calming Thoughts.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Cassette Waves.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Chaos Theory.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Chaotic Shifting Arp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Charm Lights.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Chimes of Utopia.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Chrome Bubbles.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/City Glow.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Cityscape Time-lapse.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Clatter Rattle 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Clatter Rattle 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Clockwork Clank 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Clockwork Clank 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Cloud Cumulus.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Cloud Pulses.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Complex Web.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Contemplative Phase.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Cycling Thoughts 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Cycling Thoughts 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Dark Sparks 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Dark Sparks 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Deep Movements 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Deep Movements 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Distant Drama.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Dream State Alpha 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Dream State Alpha 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Drifting Out.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Drones of Delight.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Evening Thoughts.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Falling Away.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Falling Bells 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Falling Bells 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Finding Equilibrium.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Fireflies At Dusk.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Flow States 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Flow States 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Folding Space.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Gentle Cadence 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Gentle Cadence 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Ghostly Gallop.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Glass Waves.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Glittering Lights.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Grand Views.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Haunted Bows 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Haunted Bows 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Heavy Thoughts 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Heavy Thoughts 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Hidden Origins 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Hidden Origins 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Lakeside Reflections.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Liquid Concrete.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Luminous Weave.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Lunar Lander.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Machine Melody.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Meandering Mind.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Melting Mountain 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Melting Mountain 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Meson Meditation.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Metal Jitter 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Metal Jitter 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Midnight Glow.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Moonlight Walk.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Morning Sun.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Move Into The Void 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Move Into The Void 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Mysterious Tines.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Nighttime Prelude.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Noise Waves Crashing 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Noise Waves Crashing 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Ocean Memories.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Ocean Voyager.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Path of Enlightenment.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Permutation Pattern.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Phasing Marimbas 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Phasing Marimbas 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Pizzicato Chaos 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Pizzicato Chaos 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Planet Moon.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Plucks in Space.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Popping Plucks 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Popping Plucks 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Puddle Pattern.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Pulsating Snowflakes.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Reverse Beta Waves.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Reverse Theta Waves.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Round in Fours.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Running The Clock Out.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Rush Hours.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Scraping Spaces.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Several Weeks 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Several Weeks 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Shifting Glaciers.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Short Winded.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Simply Stated.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Slow Descent.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Small Lights.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Snow Blind Sweeps 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Snow Blind Sweeps 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Sparkling Lights.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Star Gazer.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Starship Docking 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Starship Docking 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Stochastic Harp.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Stories Unfold.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Stranger Kindness.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Stumbling Down.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Submerged Mind 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Submerged Mind 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Summer Skies.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Suspended Motion.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Symphonic Squeeze 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Symphonic Squeeze 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Taking Flight.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Tapping Strings.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Tempting Times 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Tempting Times 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Tempting Times 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Time Eternal.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Twilight Time.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Twinkling Stars.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Ultraviolet Flight 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Ultraviolet Flight 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Unfolding Light.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Vast Canyons.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Vintage Tapes.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Void Adrift.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Waiting Cycles 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Waiting Cycles 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Warm Fanfares 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Warm Fanfares 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Where It Falls.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Where It Rises.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Winter Nights.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Wintery Wanderlust 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Alpha Waves/Wintery Wanderlust 02.caf",
    "～/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0024_modernambient.plist",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/01 Rooms/2.0s_Dark Chamber.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/01 Rooms/2.5s_Large & Dark.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/01 Rooms/4.3s_Concrete Room.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/01 Rooms/4.5s_Huge Room.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/07.1s Michaelis Nave-OST.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/2.4s_String Reverb.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/2.5s_Soft Hall.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/3.1s_Modulating Hall.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/4.4s_Dream Hall.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/06 Spring Reverbs/03.3s Rack Spring Flat.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/1.9s_Plane Hangar.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/14.0s_Dome.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.1s_Gymnasium.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.0s_Boat Hangar.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/3.4s_Swimming Pool.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/5.6s_Gothic Church.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/09.0s Soccer Field-OST.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/2.4s_Tunnel.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/2.9s_On the Field Natural.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/4.0s_Old Forest Long.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/4.4s_Natural Reflect Long.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/5.2s_Deep Canon.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/5.4s_Echoing Mountains.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/8.0s_Thunderstruck.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/4.2s_Black Hole.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.2s_Tom  Room.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.3s_Jazz Guitar.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/01.2s Villa Parlor-OST.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/1.0s_Sloppy Room.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/05 Gated Reverbs/0.3s_Another Drum Verb.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/09 Warped Reverb/2.1s_Mystic Vocals.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/02 Moving Spaces/Moving Space 2.aif",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/02 Moving Spaces/Moving Space 45.aif",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/06 Speakers/Amp Cabinet Speaker 13.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/06 Speakers/Amp Cabinet Speaker 3.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/06 Speakers/Mini Cassette Speaker.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/07 Analog Circuits/Clean Console.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/07 Analog Circuits/Fixed Classic Flanger.SDIR",
    "～/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/07 Analog Circuits/Morph Filter.SDIR",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Curious Hammers.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Curious Hammers.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Curious Hammers.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Curious Hammers.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Blinking Lights.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Blinking Lights.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Blinking Lights.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Blinking Lights.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Dew Drops.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Dew Drops.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Dew Drops.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Dew Drops.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Icy Caverns.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Icy Caverns.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Icy Caverns.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Icy Caverns.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Clockwork Melodies.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Clockwork Melodies.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Clockwork Melodies.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Clockwork Melodies.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Constellation Map.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Constellation Map.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Constellation Map.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Constellation Map.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Glow Worms.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Glow Worms.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Glow Worms.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Glow Worms.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Star Arp.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Star Arp.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Star Arp.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Star Arp.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Moonlight Glimmer.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Moonlight Glimmer.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Moonlight Glimmer.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Moonlight Glimmer.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Polymetric Structures.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Polymetric Structures.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Polymetric Structures.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Polymetric Structures.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Sleep Pulse.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Sleep Pulse.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Sleep Pulse.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Sleep Pulse.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Warm 70s Bass.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Warm 70s Bass.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Warm 70s Bass.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Warm 70s Bass.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Charm Bells.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Charm Bells.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Charm Bells.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Charm Bells.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Dreamy Dulcet Bells.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Dreamy Dulcet Bells.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Dreamy Dulcet Bells.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Dreamy Dulcet Bells.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Ethereal Bells.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Ethereal Bells.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Ethereal Bells.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Ethereal Bells.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Clouds Of Mercury.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Clouds Of Mercury.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Clouds Of Mercury.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Clouds Of Mercury.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dreamy Air Guitar.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dreamy Air Guitar.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dreamy Air Guitar.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dreamy Air Guitar.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Glitter Noise.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Glitter Noise.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Glitter Noise.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Glitter Noise.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Ice Blinks.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Ice Blinks.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Ice Blinks.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Ice Blinks.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mountain Rain.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mountain Rain.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mountain Rain.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mountain Rain.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Repetition Of Thought.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Repetition Of Thought.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Repetition Of Thought.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Repetition Of Thought.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Soft Keys.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Soft Keys.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Soft Keys.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Soft Keys.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Summer Tines.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Summer Tines.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Summer Tines.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Summer Tines.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Aurora Waves.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Aurora Waves.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Aurora Waves.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Aurora Waves.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Beyond Deep Skies.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Beyond Deep Skies.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Beyond Deep Skies.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Beyond Deep Skies.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Cinematic Suspense.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Cinematic Suspense.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Cinematic Suspense.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Cinematic Suspense.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crystal Spheres.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crystal Spheres.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crystal Spheres.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crystal Spheres.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crystalline Structures.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crystalline Structures.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crystalline Structures.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crystalline Structures.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Distant Memories.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Distant Memories.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Distant Memories.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Distant Memories.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Endless Stratosphere.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Endless Stratosphere.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Endless Stratosphere.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Endless Stratosphere.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Final Twilight.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Final Twilight.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Final Twilight.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Final Twilight.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Hexagon Space.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Hexagon Space.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Hexagon Space.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Hexagon Space.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Lo-Fi Voices.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Lo-Fi Voices.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Lo-Fi Voices.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Lo-Fi Voices.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Long Forgotten.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Long Forgotten.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Long Forgotten.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Long Forgotten.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Lustrous Nightfall.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Lustrous Nightfall.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Lustrous Nightfall.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Lustrous Nightfall.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Morning Meditation.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Morning Meditation.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Morning Meditation.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Morning Meditation.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Mystic Timepiece.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Mystic Timepiece.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Mystic Timepiece.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Mystic Timepiece.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Rapid Eye Movement.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Rapid Eye Movement.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Rapid Eye Movement.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Rapid Eye Movement.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Slow Breaths.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Slow Breaths.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Slow Breaths.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Slow Breaths.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Vintage Dreamscape.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Vintage Dreamscape.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Vintage Dreamscape.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Vintage Dreamscape.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Dust.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Dust.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Dust.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Dust.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Flutters.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Flutters.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Flutters.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Flutters.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Winter Day.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Winter Day.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Winter Day.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Warm Winter Day.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Sparkling Fireflies.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Sparkling Fireflies.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Sparkling Fireflies.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Sparkling Fireflies.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Vintage Pluck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Vintage Pluck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Vintage Pluck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Vintage Pluck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Warped Pluck.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Warped Pluck.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Warped Pluck.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Warped Pluck.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Carbon Particles.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Carbon Particles.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Carbon Particles.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Carbon Particles.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Distant Harp Echoes.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Distant Harp Echoes.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Distant Harp Echoes.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Distant Harp Echoes.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Texture Machine.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Texture Machine.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Texture Machine.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Texture Machine.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Thunderous Ambience.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Thunderous Ambience.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Thunderous Ambience.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Thunderous Ambience.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Adrift In The Void.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Adrift In The Void.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Adrift In The Void.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Adrift In The Void.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/After The Rain.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/After The Rain.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/After The Rain.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/After The Rain.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Arctic Breeze.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Arctic Breeze.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Arctic Breeze.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Arctic Breeze.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Atmosphere At Dusk.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Atmosphere At Dusk.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Atmosphere At Dusk.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Atmosphere At Dusk.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Dark Choral Soundscape.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Dark Choral Soundscape.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Dark Choral Soundscape.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Dark Choral Soundscape.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Enchanted Soundscape.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Enchanted Soundscape.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Enchanted Soundscape.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Enchanted Soundscape.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Glacial Forms.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Glacial Forms.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Glacial Forms.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Glacial Forms.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Warm Rain.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Warm Rain.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Warm Rain.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Warm Rain.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Strings/Dusty Strings.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Strings/Dusty Strings.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Strings/Dusty Strings.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Strings/Dusty Strings.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Strings/Snow Drift.patch/#Root.cst",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Strings/Snow Drift.patch/com.apple.musicapps.tags.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Strings/Snow Drift.patch/data.plist",
    "～/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Strings/Snow Drift.patch/prelisten.caf",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Blinking Lights.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Clockwork Melodies.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Constellation Map.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Dew Drops.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Glow Worms.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Icy Caverns.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Moonlight Glimmer.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Polymetric Structures.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Sleep Pulse.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Star Arp.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Bass/Warm 70s Bass.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Clouds of Mercury.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Curious Hammers.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Dreamy Air Guitar.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Glitter Noise.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Ice Blinks.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Mountain Rain.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Repetition of Thought.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Soft Keys.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Summer Tines.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Mallets/Charm Bells.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Mallets/Dreamy Dulcet Bells.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Mallets/Ethereal Bells.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Aurora Waves.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Beyond Deep Skies.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Cinematic Suspense.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Crystalline Structures.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Distant Memories.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Endless Stratosphere.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Final Twilight.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Hexagon Space.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Lo-Fi Voices.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Long Forgotten.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Lustrous Nightfall.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Slow Breaths.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Vintage Dreamscape.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Warm Flutters.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Warm Winter Day.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Plucked/Sparkling Fireflies.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Plucked/Vintage Pluck.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Plucked/Warped Pluck.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Rhythmic/Carbon Particles.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Rhythmic/Distant Harp Echoes.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Rhythmic/Mystic Timepiece.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Texture Machine.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Sound Effects/Thunderous Ambience.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Soundscape/Adrift In The Void.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Soundscape/After The Rain.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Soundscape/Arctic Breeze.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Soundscape/Atmosphere At Dusk.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Soundscape/Crystal Spheres.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Soundscape/Dark Choral Soundscape.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Soundscape/Enchanted Soundscape.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Soundscape/Glacial Forms.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Soundscape/Morning Meditation.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Soundscape/Rapid Eye Movement.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Soundscape/Warm Dust.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Soundscape/Warm Rain.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Strings/Dusty Strings.acp",
    "～/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Strings/Snow Drift.acp",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Arpeggiated/Custom/3_Forest Birds-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Arpeggiated/Custom/A1-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Arpeggiated/Custom/Ah1-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Arpeggiated/Custom/E2-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Arpeggiated/Custom/Frozen Ocean C2-S.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Arpeggiated/Custom/Trad Harp G#5-S.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Arpeggiated/Custom/Vowel-O1-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/1974 Ambient Solo C4-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Electronic Drums/Dubstep 1/Dubstep Kick 0018.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Unusual Drums/Ice FX Drums/Ice FX Long Snare.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Acoustic Guitars/Acc Guit/Acc Guit C2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Acoustic Guitars/Acc Guit/Acc Guit C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Acoustic Guitars/Acoustic Guitar 4 Gliss/Acoustic Guitar 4 Gliss C2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Acoustic Guitars/Trad Classical Guitar/Trad Classical Guitar C4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Custom/Iceland Cafe Gig Hang 3-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Electric Guitars/12 String Pluck R/12 String Pluck 1 E2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/Dulcimar2/Dulcimar 2 C4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/Forgotten Harp Gu/Forgotten Harp Gu C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/Trad Harp/Trad Harp C4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Abandoned Piano A1-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Abandoned Piano C1-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Abandoned Piano C2-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Abandoned Piano E1-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Abandoned Piano F1-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Guitar Harmonics C3-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Electric Pianos/Foreign Matter/Foreign Matter C2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Electric Pianos/Synth Tines/Synth Tines 05.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Loops/Melodic Loops/Max Key Kit Maj.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Custom/Bellmorph C4-S.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Custom/Glass Xylophone C5-S.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Synthetic Mallets/FM Tinker Bell/FM Tinker Bell C4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/10CC 45A1-left-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Ambient Drift C3-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Ambistack60-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Ambistack60-AF_2.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Autoharp Binaural C3-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Col-8PhonemeSeq-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Dark Background C3-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Formant Coaster A2-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Grand Pluck C#3-AF_2.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/High Granular Harmonic C3-AF_2.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Iceland Cafe Gig Hang 3-A.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/SuGrC03-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Awaken C2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Formant Atmo C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Rhythmic/Custom/Mystic TimepieceA0000-A.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Ambience Nature/Cabin Rain Rumbling.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Instruments/Cymbal Knocks Tr 9.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Radiostatic 004.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Vinyl Noise 7 Long.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/White Noise.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/1974 Ambient Solo C3-ASF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/6_tiny rowing boat-AF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Cabin Rain Rumbling-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Cherry Improv Phrases 1 0023-ASF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Dreamstealer C6-AS.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Forest Surroundings-ASF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Icelandic Choir Phrases 0050-S.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Max Mirage Min 16bts-AS.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Rapid Eye MovementA0000-A.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Rapid Eye MovementB0000-A.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Orange Dirt/Orange Dirt 127 C6.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Single Samples/Fractal Piano.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Single Samples/Fractured Signal.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Single Samples/Ideas As Opiates C2.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Single Samples/The Bell Tree.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Custom/Mellotron Violins C3-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Vintage String Synth/Vintage String Synth C4.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Analog Hishimmer-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Music Box C6-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Noise Bright Soft-SF.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Repetition of ThoughtA0000-A.aaz",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digitalis Pad/Digitalis Pad C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Rack Chord/Rack Chord C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Star Pluck/Star Pluck C3.caf",
    "～/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Choir/Choir Female Ah pp2/Choir Female Ah pp 2 D4.caf",
  ]
end
