cask "ml-0054-sessionplayerssynth" do
  version "ccee002ec819b6fa6f3537a60fb268aa-98"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0054_sessionplayerssynth/ml_0054_sessionplayerssynth.aar"
  name "Synths"
  desc "SessionPlayerPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0054_sessionplayerssynth/ml_0054_sessionplayerssynth.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0054_sessionplayerssynth.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Atlanta Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Bass 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Bass 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Bass 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Bass 09.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Bass 10.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Cloud Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Drill Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Heavy EDM Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Latin Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Latin Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Miami Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 Sliding Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 UK Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/808 UK Drill Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Acid Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Acid Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Acid Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Acid Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Acid Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Acid Bass 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Acid Bass 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Acid Bass 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Acid Bass 09.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Acid Bass 10.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Ancient History Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Ancient History Strings.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Ancient History Sub Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Call Your Bluff Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Call Your Bluff Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Call Your Bluff Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Call Your Bluff Sub Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Call Your Bluff Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Changing Guard Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Changing Guard Bells.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Changing Guard Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Changing Guard Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Changing Guard Vox.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Cold Springs Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Cold Springs Chorus Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Cold Springs Chorus Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Cold Springs Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Cold Springs Chorus Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Cold Springs Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Cold Springs Verse Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Cold Springs Verse Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Chorus Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Chorus Pulsing Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Intro Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Verse Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Verse Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Verse Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Verse Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Verse Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Verse Pulsing Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Verse Pulsing Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Cosmic Union Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Cosmic Union Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Cosmic Union Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Cosmic Union Synth Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Crystal Floors Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Crystal Floors Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Crystal Floors Chorus Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Crystal Floors Chorus Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Crystal Floors Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Crystal Floors Verse Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Crystal Floors Verse Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Dance Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Dance Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Dance Piano 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Dance Piano 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Dance Piano 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Dance Piano 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Dance Piano 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Dance Piano 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Dance Piano 09.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Dance Piano 10.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep Glow Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep Glow Chorus Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep Glow Chorus Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep Glow Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep Glow Chorus Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep Glow Chorus Synth Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep Glow Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep Glow Verse Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep Glow Verse Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep Glow Verse Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep In Thought Chorus Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep in Thought Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep in Thought Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep In Thought Verse Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep in Thought Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deep in Thought Verse Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deeper Rumble Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deeper Rumble Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deeper Rumble Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deeper Rumble Synth Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Deeper Rumble Synth Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Chorus Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Chorus Noise FX.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Chorus Synth Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Intro Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Intro Synth Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Verse Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Verse Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desert Mirage Verse Synth Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Easy Street Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Easy Street Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Easy Street Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Easy Street Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Echoes From Below Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Echoes From Below Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Echoes From Below Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Echoes From Below Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Echoes From Below Synth Organ.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Feel This Way Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Feel This Way Organ Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Feel This Way Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Finding Balance Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Finding Balance Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Finding Balance Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Finding Balance Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Forever Dreaming Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Forever Dreaming Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Forever Dreaming Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Forever Dreaming Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Fourth Dimension Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Fourth Dimension Lead Harmony.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Fourth Dimension Lead Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Fourth Dimension Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Fourth Dimension Sub Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Fourth Dimension Vox FX.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Fractal Room Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Fractal Room Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Fractal Room Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Fractal Room Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Full Bloom Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Full Bloom Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Full Bloom Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Giant's Entry Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Giant's Entry Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Giant's Entry Clav 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Giant's Entry Clav 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Giant's Entry Synth Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Giant's Entry Synth Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Glass Shards Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Glass Shards Chorus Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Glass Shards Chorus Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Glass Shards Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Glass Shards Chorus Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Glass Shards Chorus Synth Organ.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Glass Shards Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Glass Shards Verse Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Glass Shards Verse Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Golden Dream Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Golden Dream Chorus Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Golden Dream Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Golden Dream Intro Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Golden Dream Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Golden Dream Verse Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Green Mascara Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Green Mascara Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Green Mascara Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Green Mascara Synth Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Green Mascara Synth Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Green Mascara Synth Chords 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Head Movements Breakdown Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Head Movements Breakdown Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Head Movements Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Head Movements Chorus Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/House Organ 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/House Organ 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/House Organ 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/House Organ 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/House Organ 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/House Organ 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/House Organ 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/House Organ 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/House Organ 09.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/House Organ 10.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Inner Ring Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Inner Ring Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Inner Ring Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Keep It Going Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Keep It Going Chorus Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Keep It Going Chorus Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Keep It Going Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Keep It Going Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Keep It Going Verse Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Keep It Going Verse Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Keep Me Waiting Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Keep Me Waiting Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Keep Me Waiting Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Keep Me Waiting Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Keep Me Waiting Vox.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lucid Dreaming Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lucid Dreaming Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lucid Dreaming Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lucid Dreaming Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lunar Glow Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lunar Glow Synth Brass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Lunar Glow Synth Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Melting Pot Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Melting Pot Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Melting Pot Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Melting Pot Sub Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midday Bloom Arp 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midday Bloom Arp 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midday Bloom Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midday Bloom Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midtown Crew Bridge Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midtown Crew Bridge Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midtown Crew Bridge Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midtown Crew Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midtown Crew Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midtown Crew Chorus Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midtown Crew Chorus Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midtown Crew Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midtown Crew Verse Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midtown Crew Verse Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Missing Me Bridge Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Missing Me Chorus Synth Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Missing Me Chorus Synth Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modulated Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modulated Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modulated Pad 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modulated Pad 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modulated Pad 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modulated Pad 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modulated Pad 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modulated Pad 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modulated Pad 09.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Modulated Pad 10.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Morning Bloom Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Morning Bloom Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Morning Bloom Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Morning Bloom Keys 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Morning Bloom Keys 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Morning Bloom Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neon Nights Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neon Nights Chorus Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neon Nights Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neon Nights Chorus Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neon Nights Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neon Nights Verse Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Neon Nights Verse Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Never Alone Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Never Alone Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Never Alone Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Never Alone Synth Brass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Never Alone Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Night Chase Chorus Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Night Chase Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Night Chase Chorus Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Night Chase Chorus Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Night Chase Intro Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Night Chase Intro Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Night Chase Intro Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Night Chase Verse Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Night Chase Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Night Chase Verse Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Night Chase Verse Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Nighttime Bounce Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Nighttime Bounce Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Nighttime Bounce Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Nighttime Bounce Mallets 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Nighttime Bounce Mallets 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Nighttime Bounce Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Nighttime Bounce Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/No Tomorrow Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/No Tomorrow Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/No Tomorrow Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/No Tomorrow Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Nocturnal Bliss Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Nocturnal Bliss Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Nocturnal Bliss Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Over the Moon Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Over the Moon Deep Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Over the Moon Pulsing Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Over the Moon Synth Organ.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Over the Moon Synth Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Past Curfew Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Past Curfew Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Past Curfew Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Past Curfew Verse Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pedal Down Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pedal Down Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pedal Down Chorus Synth Brass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pedal Down Chorus Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pedal Down Intro Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pedal Down Intro Synth Brass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pedal Down Intro Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Phantom Signals Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Phantom Signals Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Phantom Signals FX 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Phantom Signals FX 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Phantom Signals Pulsing Synth 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Phantom Signals Pulsing Synth 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Phantom Signals Pulsing Synth 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Phantom Signals Synth Plucks 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Phantom Signals Synth Plucks 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pressure Point Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pressure Point Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pressure Point Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pressure Point Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pump Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pump Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pump Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pump Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pump Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pump Bass 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pump Bass 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pump Bass 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pump Bass 09.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pump Bass 10.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pure Determination Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pure Determination Chorus Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pure Determination Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pure Determination Chorus Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pure Determination Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pure Determination Verse Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pure Determination Verse Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Pure Determination Verse Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Queens Bridge Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Queens Bridge FX.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Queens Bridge Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Queens Bridge Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Queens Bridge Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Queens Bridge Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Reasons to Change Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Reasons to Change Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Reasons to Change FX.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Reasons to Change Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Reasons to Change Synth Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Reasons to Change Synth Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Reasons to Change Synth Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Reasons to Change Vox.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Remember the Day Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Remember the Day Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Remember the Day Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Remember the Day Synth Flute.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Rhythmic Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Rhythmic Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Rhythmic Chords 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Rhythmic Chords 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Rhythmic Chords 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Rhythmic Chords 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Rhythmic Chords 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Rhythmic Chords 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Rhythmic Chords 09.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Rhythmic Chords 10.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Save the Day Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Save the Day Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Save the Day Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Save the Day Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sequenced Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sequenced Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sequenced Bass 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sequenced Bass 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sequenced Bass 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sequenced Bass 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sequenced Bass 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sequenced Bass 08.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sequenced Bass 09.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sequenced Bass 10.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Shining Bright Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Shining Bright FX.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Shining Bright Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Shining Bright Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Shining Bright Vox.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Simple Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Simple Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Simple Pad 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Simple Pad 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Simple Pad 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Simple Pad 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Slow Fire Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Slow Fire Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Slow Fire Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Slow Fire Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Something More Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Something More Chorus Pulsing Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Something More Chorus Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Something More Chorus Synth Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Something More Verse Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Something More Verse Pulsing Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Something More Verse Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sunset Rifts Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sunset Rifts FM Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sunset Rifts FM Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sunset Rifts Keys 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sunset Rifts Keys 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Sunset Rifts Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Times Past Chorus Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Times Past Chorus Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Times Past Chorus Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Times Past Chorus Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Times Past Chorus Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Times Past Intro Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Times Past Intro Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Times Past Intro Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Times Past Intro Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Wait and See Arp 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Wait and See Arp 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Wait and See Arp 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Wait and See Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Wait and See Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Wait and See Synth 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Wait and See Synth 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Hook 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Ad Lib 01.caf",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0054_sessionplayerssynth.plist",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/2.7s_Smooth Vocal Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/07 Indoor Spaces/2.1s_Gymnasium.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/08 Outdoor Spaces/2.4s_Tunnel.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/09 Warped Reverb/4.2s_Black Hole.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/09 Warped Reverb/2.6s_Jasmine.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/07 Indoor Spaces/0.4s_Music Club.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/03 Textures/Texture 10.aif",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/07 Analog Circuits/Clean Console.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/07 Analog Circuits/Tape Saturator.SDIR",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Acid Wash Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Acid Wash Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Acid Wash Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Acid Wash Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Big Stadium Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Big Stadium Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Big Stadium Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Big Stadium Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Chrome 808 Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Chrome 808 Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Chrome 808 Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Chrome 808 Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Class Act Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Class Act Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Class Act Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Class Act Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Classic Connection Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Classic Connection Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Classic Connection Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Classic Connection Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Clean Cut Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Clean Cut Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Clean Cut Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Clean Cut Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Close Call Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Close Call Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Close Call Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Close Call Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Impact Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Impact Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Impact Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Impact Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Edge of Breaking Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Edge of Breaking Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Edge of Breaking Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Edge of Breaking Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/FM Trunk Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/FM Trunk Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/FM Trunk Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/FM Trunk Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Heavy Hands Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Heavy Hands Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Heavy Hands Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Heavy Hands Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Iron Grip Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Iron Grip Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Iron Grip Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Iron Grip Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Laser Strike Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Laser Strike Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Laser Strike Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Laser Strike Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Liquid Fire Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Liquid Fire Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Liquid Fire Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Liquid Fire Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Mystic Caution Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Mystic Caution Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Mystic Caution Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Mystic Caution Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Organ Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Organ Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Organ Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Organ Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Renegade Party.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Renegade Party.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Renegade Party.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Renegade Party.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Rubber Band Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Rubber Band Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Rubber Band Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Rubber Band Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Thin Wave Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Thin Wave Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Thin Wave Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Thin Wave Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Tin Roof Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Tin Roof Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Tin Roof Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Tin Roof Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Torch Bearer Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Torch Bearer Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Torch Bearer Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Torch Bearer Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Transistor Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Transistor Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Transistor Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Transistor Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Wide Angle Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Wide Angle Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Wide Angle Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Wide Angle Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Analog Brass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Analog Brass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Analog Brass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Analog Brass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Dancing Sprites.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Dancing Sprites.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Dancing Sprites.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Dancing Sprites.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Saw Prism.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Saw Prism.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Saw Prism.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Saw Prism.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dance Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dance Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dance Piano.patch/DancePiano.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dance Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dance Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dance Piano.patch/SteinwayPiano.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dream Walker.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dream Walker.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dream Walker.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Dream Walker.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/House Drawbars.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/House Drawbars.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/House Drawbars.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/House Drawbars.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Magic Box.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Magic Box.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Magic Box.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Magic Box.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Soft Hills.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Soft Hills.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Soft Hills.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Soft Hills.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Wet Streets.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Wet Streets.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Wet Streets.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Wet Streets.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Crystal Shells.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Crystal Shells.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Crystal Shells.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Crystal Shells.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Deep Majesty.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Deep Majesty.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Deep Majesty.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Deep Majesty.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Distant Dawn.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Distant Dawn.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Distant Dawn.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Distant Dawn.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Odd Movements.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Odd Movements.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Odd Movements.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Odd Movements.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Plucked Away.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Plucked Away.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Plucked Away.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Plucked Away.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Sprouting Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Sprouting Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Sprouting Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Sprouting Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Parallel Earth Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Subtle Dynamics Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Steinway Piano 2.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Electric Piano/Other/Double Tracked Wurli.exs",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Ring Mod",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Sub Sonic Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Arpy Bass/Arpy Bass F0.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini M Attack Sust Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Classic Slap House BassC0000-A.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Heavy 808 BassA0000-808 Kick Attack-001-S.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Hype Kick-010-SF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Metal Waves C1-AF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Round House BassB0000-A.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Rage/CBass Rage A0.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Rage/CBass Rage A1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Rage/CBass Rage A2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Rage/CBass Rage A3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Rage/CBass Rage C0.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Rage/CBass Rage C1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Rage/CBass Rage D2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Rage/CBass Rage D3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Rage/CBass Rage D4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Rage/CBass Rage F0.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Rage/CBass Rage F1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/Dark FM Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/XBass Phat",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Electronic Drums/Micro/Micro Kick 01.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Electronic Drums/Miner/Miner Tom 03.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Single Samples/Chill Kick.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Single Samples/Dark Secrets Transient.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Single Samples/Modulated Sine SW.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Single Samples/Slap House Attack 02.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Single Samples/Slap House Attack 05.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Single Samples/Sub Kick 3_5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Unusual Drums/Cup of Tea/Cup Of Tea Kit 0007 127.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/FM Classic Koto/FM Classic Koto C3-AF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/Masterpiece Pluck/Masterpiece Pluck C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Single Samples/Noisy Guitar Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Breathy Keys",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Custom/Smashed Piano.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Electric Pianos/Epiano FM Hard",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Electric Pianos/EPiano FM Synth",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Electric Pianos/EPiano Mrk II/EPiano Mrk II F#2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Electric Pianos/EPiano Mrk II/EPiano Mrk II F#3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Autoharp/Autoharp Mute C5-AF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Cheap Bell",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Musical Box/Musical Box E3-AF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Singing Bowl Ringing.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Synthetic Mallets/Chrono Chime/Chrono Chime pp C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Kalimba/Kalimba G3-AF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/Kingdom Of The Sun/Kingdom Of The Sun C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/Kingdom Of The Sun/Kingdom Of The Sun C4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/Kingdom Of The Sun/Kingdom Of The Sun C5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/Kingdom Of The Sun/Kingdom Of The Sun C6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/Kingdom Of The Sun/Kingdom Of The Sun C7.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/Kingdom Of The Sun/Kingdom Of The Sun C8.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/Kingdom Of The Sun/Kingdom Of The Sun G3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/Kingdom Of The Sun/Kingdom Of The Sun G4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/Kingdom Of The Sun/Kingdom Of The Sun G5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/Kingdom Of The Sun/Kingdom Of The Sun G6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/Kingdom Of The Sun/Kingdom Of The Sun G7.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/Lush Bright Pad",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/1974 Sawtooth C3-AF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/1974 Triangle C3-AF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Ambient Drift C3-SF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Brassy EnsembleC0000-A.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Brassy EnsembleD0000-A.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Dark Background C3-AF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Guitar Orchestra Pad/Guitar Orchestra PadC0000-Noisy Guitar Plucks-SF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Guitar Wave 02-SF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Iceland Cafe Gig Hang 3-A.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/PAD Ripples E3-SF_1.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Endless/Endless A#3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Endless/Endless B0.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Endless/Endless C#2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Endless/Endless C5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Endless/Endless D#3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Endless/Endless D6.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Endless/Endless F#1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Endless/Endless F4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Endless/Endless G#2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Endless/Endless G5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Ether Drone/Ether Drone A#3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Ether Drone/Ether Drone A6.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Ether Drone/Ether Drone B0.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Ether Drone/Ether Drone C#2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Ether Drone/Ether Drone C5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Ether Drone/Ether Drone D#3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Ether Drone/Ether Drone D6.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Ether Drone/Ether Drone F#1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Ether Drone/Ether Drone F4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Ether Drone/Ether Drone G#2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Ether Drone/Ether Drone G5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/FM Voice Nearly Vocal/FM Voice Nearly Vocal C3-A-AS01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Sighpad C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Strings C5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Ambience Nature/Cabin Rain Rumbling.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Impacts/Cloud01.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Impacts/EkoFX11.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Circuit Bent/CB Tand 19.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Vinyl Noise 1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Vinyl Noise 3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Vinyl Noise 7 Long.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Custom/Cabin Rain Rumbling-SF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Single Samples/Black Grotto.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Single Samples/Dark String Sweep.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Single Samples/Modular Other World Aug C0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Water Harp Bowed/Water Harp Bowed 2 D#4-SF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Single Samples/Violin Pizz G#5.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Retro Synth Strings 3",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Synth Strings AM",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Vocoder Bright Strings/Vocoder Bright Strings G2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Vocoder Bright Strings/Vocoder Bright Strings G3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Vocoder Bright Strings/Vocoder Bright Strings G4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C7.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C8.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Triangle",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Big Multi Layer",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Pulse Ninety Five",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Resonant Sequence",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Retro Modular Rich Pulse",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Analog Hishimmer-SF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Chordal Perks-D-S-2.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Noise Bright Soft-SF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Metallic Vox Strings/Metallic Vox Strings C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Daytrip Alchemy Synth_4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Daytrip Alchemy Synth_5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Daytrip Alchemy Synth_6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Erase Signal.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Choir/Choir Female Ah ff2/Choir Female Ah ff 2 F2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Choir/Choir Female Ah pp1",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Choir/Single Samples/Classical Choir.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Morphs/Anastacia Morph/Anastacia Aa Ee Ay Oh/Anastacia Aa Ee Ay Oh 1 A3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Single Samples",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Staccato/Cherry Staccato/Cherry Stacc Oh/Cherry Stacc Oh 1 C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Anastacia Sustain/Anastacia Aa",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Tom Sustain/Solo Tom Ahh",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal FX And Noises/Beatbox FX/Beatbox FX 14-C-AS-1.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal FX And Noises/Beatbox FX/Beatbox FX 14-D-AS-1.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal FX And Noises/Beatbox FX/Vox Bass FX 059.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal Instruments/Vox Busty/Vox Busty 1 mf F#1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal Instruments/Vox Dusty Sust/Vox Dusty Sus mf B0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal Instruments/Vox Dusty Sust/Vox Dusty Sus mf C1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal Phrases/Amanda Improv Phrases/Amanda Improv Phrases2/Amanda Improv Phrases 2 0007.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Double Vision/Kick 3 Sub - Double Vision.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Future Flex/Kick 3 Sub - Future Flex.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Grand Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Other/Thick Antique Piano.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Old-Time Recording Keys_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Parallel Earth Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Rise Above Piano",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Subtle Dynamics Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Steinway Piano 2_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Electric Piano/Other/Electric Tines Piano 02.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Electric Piano/Other/Flea Market Wurli_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Azimuth Dream_consolidated.caf",
  ]
end
