cask "ml-0032-modernsynth" do
  version "1ab403c23de512a338deee71d30c060b-24"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0032_modernsynth/ml_0032_modernsynth.aar"
  name "ModernSynths"
  desc "SynthPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0032_modernsynth/ml_0032_modernsynth.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0032_modernsynth.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/z_Legacy/01 Hip Hop/Be Together Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/z_Legacy/01 Hip Hop/Dub Deep Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/z_Legacy/02 Electro House/Americana Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/z_Legacy/02 Electro House/Better Late Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/z_Legacy/02 Electro House/Marching Drum Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/z_Legacy/04 Modern RnB/All Hours Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/z_Legacy/07 Chillwave/Brooklyn Nights Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/z_Legacy/07 Chillwave/Brooklyn Nights Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/z_Legacy/07 Chillwave/End Credits Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/z_Legacy/08 Indie Disco/Chopping Block Synth.caf",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0032_modernsynth.plist",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/03 Plate Reverbs/2.6s_Vocal Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/03 Plate Reverbs/5.1s_New Age Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/02.6s Hansa Studio-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/05 Gated Reverbs/1.4s_Percussion.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/02 Halls/1.6s_Short Vocal Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/03 Plate Reverbs/0.7s_Drum Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Pitched Vocals Organ.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Pitched Vocals Organ.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Pitched Vocals Organ.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Pitched Vocals Organ.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Bass/Italo Disco Patterns.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Bass/Italo Disco Patterns.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Bass/Italo Disco Patterns.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Bass/Italo Disco Patterns.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Bass/Modern Acid Patterns.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Bass/Modern Acid Patterns.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Bass/Modern Acid Patterns.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Bass/Modern Acid Patterns.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Bleep City.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Bleep City.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Bleep City.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Bleep City.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Catch This.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Catch This.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Catch This.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Catch This.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Childish Movement.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Childish Movement.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Childish Movement.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Childish Movement.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Chords/Deep Techno Chords.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Chords/Deep Techno Chords.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Chords/Deep Techno Chords.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Chords/Deep Techno Chords.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Chords/Echo Chords.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Chords/Echo Chords.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Chords/Echo Chords.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Chords/Echo Chords.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Chords/Single Digit Story.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Chords/Single Digit Story.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Chords/Single Digit Story.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Chords/Single Digit Story.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Comb Groover.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Comb Groover.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Comb Groover.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Comb Groover.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Digital Cascades.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Digital Cascades.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Digital Cascades.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Digital Cascades.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Erratic Motion.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Erratic Motion.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Erratic Motion.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Erratic Motion.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Groovy Synth Pattern.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Groovy Synth Pattern.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Groovy Synth Pattern.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Groovy Synth Pattern.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Hybrid Dancer.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Hybrid Dancer.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Hybrid Dancer.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Hybrid Dancer.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Jittery Pulses.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Jittery Pulses.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Jittery Pulses.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Jittery Pulses.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Bright Majestic Waves.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Bright Majestic Waves.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Bright Majestic Waves.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Bright Majestic Waves.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Getting The Jitters.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Getting The Jitters.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Getting The Jitters.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Getting The Jitters.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Juicy Arp.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Juicy Arp.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Juicy Arp.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Juicy Arp.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Warm Arp Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Warm Arp Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Warm Arp Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Layers/Warm Arp Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Meteor Shower.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Meteor Shower.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Meteor Shower.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Meteor Shower.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Night Magic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Night Magic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Night Magic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Night Magic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Replicant Arp.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Replicant Arp.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Replicant Arp.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Replicant Arp.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Resonant Waves.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Resonant Waves.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Resonant Waves.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Resonant Waves.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Single Digit Drama.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Single Digit Drama.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Single Digit Drama.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Single Digit Drama.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Synth Skin Drum.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Synth Skin Drum.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Synth Skin Drum.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Synth Skin Drum.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/808 Mutation Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/808 Mutation Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/808 Mutation Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/808 Mutation Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Acid Etched Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Acid Etched Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Acid Etched Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Acid Etched Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Agile Synth Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Agile Synth Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Agile Synth Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Agile Synth Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Breathless Pumping.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Breathless Pumping.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Breathless Pumping.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Breathless Pumping.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Colossal Synth Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Colossal Synth Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Colossal Synth Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Colossal Synth Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Dirty Planet.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Dirty Planet.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Dirty Planet.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Dirty Planet.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Edgy Synth Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Edgy Synth Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Edgy Synth Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Edgy Synth Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Enigma Bass Machine.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Enigma Bass Machine.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Enigma Bass Machine.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Enigma Bass Machine.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Filthy Slap Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Filthy Slap Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Filthy Slap Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Filthy Slap Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Future Wobble Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Future Wobble Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Future Wobble Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Future Wobble Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Massive Grime Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Massive Grime Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Massive Grime Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Massive Grime Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Mega Wobble Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Mega Wobble Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Mega Wobble Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Mega Wobble Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Pulse Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Pulse Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Pulse Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Pulse Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Pumping Synth Waves.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Pumping Synth Waves.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Pumping Synth Waves.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Pumping Synth Waves.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Robot Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Robot Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Robot Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Robot Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Scream Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Scream Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Scream Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Scream Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Solar Eclipse.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Solar Eclipse.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Solar Eclipse.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Solar Eclipse.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Space Dance Octaves.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Space Dance Octaves.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Space Dance Octaves.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Space Dance Octaves.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Styrofoam Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Styrofoam Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Styrofoam Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Styrofoam Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Torn Up Wobble Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Torn Up Wobble Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Torn Up Wobble Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Torn Up Wobble Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Wobble Fade Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Wobble Fade Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Wobble Fade Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Wobble Fade Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Zap Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Zap Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Zap Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Zap Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Bell Designer.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Bell Designer.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Bell Designer.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Bell Designer.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Liquid Crystal.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Liquid Crystal.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Liquid Crystal.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Liquid Crystal.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Liquid Wires.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Liquid Wires.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Liquid Wires.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Liquid Wires.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Sweet Bells.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Sweet Bells.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Sweet Bells.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Sweet Bells.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Slide Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Slide Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Slide Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Slide Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Arcturus.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Arcturus.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Arcturus.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Arcturus.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Beautiful Melody.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Beautiful Melody.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Beautiful Melody.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Beautiful Melody.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Cavernous Chords.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Cavernous Chords.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Cavernous Chords.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Cavernous Chords.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Electro Sweeper.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Electro Sweeper.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Electro Sweeper.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Electro Sweeper.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Elements.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Elements.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Elements.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Elements.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fast Vox.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fast Vox.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fast Vox.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fast Vox.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fifth Formant Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fifth Formant Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fifth Formant Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fifth Formant Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Hold And Dissolve.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Hold And Dissolve.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Hold And Dissolve.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Hold And Dissolve.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Low Sweeper.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Low Sweeper.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Low Sweeper.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Low Sweeper.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Paris.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Paris.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Paris.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Paris.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Punchy Drama.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Punchy Drama.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Punchy Drama.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Punchy Drama.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Vox Lead.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Vox Lead.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Vox Lead.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Vox Lead.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Chicago Stack.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Chicago Stack.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Chicago Stack.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Chicago Stack.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Detroit Chords.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Detroit Chords.patch/ChordLayer.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Detroit Chords.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Detroit Chords.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Detroit Chords.patch/DetroitChords.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Detroit Chords.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Fuzzy Minor Stab.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Fuzzy Minor Stab.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Fuzzy Minor Stab.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Fuzzy Minor Stab.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Hip Hop Block.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Hip Hop Block.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Hip Hop Block.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Hip Hop Block.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Massive Synth Hit.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Massive Synth Hit.patch/BassLayer.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Massive Synth Hit.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Massive Synth Hit.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Massive Synth Hit.patch/PadLayer.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Massive Synth Hit.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Metallic Edge Lead.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Metallic Edge Lead.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Metallic Edge Lead.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Metallic Edge Lead.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Minor Outbursts.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Minor Outbursts.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Minor Outbursts.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Minor Outbursts.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Abstract Mallets.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Abstract Mallets.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Abstract Mallets.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Abstract Mallets.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Ethereal Mallets.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Ethereal Mallets.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Ethereal Mallets.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Ethereal Mallets.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Trembles.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Trembles.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Trembles.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Mallets/Trembles.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Angelic Motion.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Angelic Motion.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Angelic Motion.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Angelic Motion.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Cosmic Ascent.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Cosmic Ascent.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Cosmic Ascent.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Cosmic Ascent.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crystal Sun.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crystal Sun.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crystal Sun.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crystal Sun.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Deeper Emotion.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Deeper Emotion.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Deeper Emotion.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Deeper Emotion.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Drifting Metals.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Drifting Metals.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Drifting Metals.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Drifting Metals.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Emotional Machines.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Emotional Machines.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Emotional Machines.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Emotional Machines.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Epic Cloud Formation.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Epic Cloud Formation.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Epic Cloud Formation.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Epic Cloud Formation.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Rhythmic Skimmer Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Rhythmic Skimmer Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Rhythmic Skimmer Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Rhythmic Skimmer Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Shifting Panels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Shifting Panels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Shifting Panels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Shifting Panels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Space Glitters.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Space Glitters.patch/Animation.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Space Glitters.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Space Glitters.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Space Glitters.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Space Glitters.patch/Glitter.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Space Glitters.patch/Pad.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Space Glitters.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Space Glitters.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Stereo Drifter.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Stereo Drifter.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Stereo Drifter.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Stereo Drifter.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Waves of Synth Pads.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Waves of Synth Pads.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Waves of Synth Pads.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Waves of Synth Pads.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Wide Swirling Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Wide Swirling Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Wide Swirling Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Wide Swirling Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Blue Cavern.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Blue Cavern.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Blue Cavern.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Blue Cavern.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Bridled.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Bridled.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Bridled.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Bridled.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Deep Plucked Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Deep Plucked Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Deep Plucked Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Deep Plucked Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Expanding Pluck.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Expanding Pluck.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Expanding Pluck.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Expanding Pluck.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Hybrid Attacker.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Hybrid Attacker.patch/Attack.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Hybrid Attacker.patch/Base.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Hybrid Attacker.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Hybrid Attacker.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Hybrid Attacker.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Pumping Pluck.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Pumping Pluck.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Pumping Pluck.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Pumping Pluck.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Animated Swirls.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Animated Swirls.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Animated Swirls.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Animated Swirls.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Crystalline Rhythms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Crystalline Rhythms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Crystalline Rhythms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Crystalline Rhythms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Digital Gate.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Digital Gate.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Digital Gate.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Digital Gate.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Groove Pattern Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Groove Pattern Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Groove Pattern Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Groove Pattern Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Harmonic Tides.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Harmonic Tides.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Harmonic Tides.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Harmonic Tides.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Scattered Rhythm.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Scattered Rhythm.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Scattered Rhythm.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Scattered Rhythm.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Swirling Flutters.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Swirling Flutters.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Swirling Flutters.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Swirling Flutters.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Echolocation.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Echolocation.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Echolocation.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Echolocation.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/FM Builder.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/FM Builder.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/FM Builder.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/FM Builder.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Gritty Riser.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Gritty Riser.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Gritty Riser.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Gritty Riser.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Pumping Pitch Riser.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Pumping Pitch Riser.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Pumping Pitch Riser.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Pumping Pitch Riser.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Zippy Build-Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Zippy Build-Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Zippy Build-Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Zippy Build-Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Burning Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Burning Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Burning Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Burning Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Flying Waves.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Flying Waves.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Flying Waves.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Flying Waves.patch/FlyingWaves1.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Flying Waves.patch/FlyingWaves2.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Flying Waves.patch/FlyingWaves3.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Flying Waves.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Synthetic Chatter.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Synthetic Chatter.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Synthetic Chatter.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Synthetic Chatter.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Arpeggiator/Futuristic Bass.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Arpeggiator/Hectic Piano Arp.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Bass/Monster Growl Bass.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Bass/Squishy Funk.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Chords/Disrupted Chords.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Chords/Panic Button.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Chords/Pitched Marching Band.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Chords/Strange Strings.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Chords/Warped Machine.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Experimental/Bending Flutters.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Experimental/Broken Signal.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Experimental/Burst Of Air.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Experimental/Chopping Block Synth.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Experimental/Circular Beat.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Experimental/Deep Space Warp.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Experimental/Quirky Pluck.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Experimental/Rewind Drums.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Keys/Muted Piano.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Pad/Magnetic Waves 01.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Pad/Pulsing Chords.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Pad/Sweeping Trance.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Vocals/Accelerating Voices.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Vocals/Baily Glide.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Vocals/Disrupted Vox.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Vocals/Pitch Up Vox.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Vocals/Plucky Vox.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Quick Sampler/Vocals/Warp Vox.pst",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Basswave",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Ring Mod",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Sub Sonic Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Arpy Bass/Arpy Bass F1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Grungy Spike",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares C3-ASF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/808 Mutation BassA0000-A.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Agile Synth Bass-A-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Custom/Mechanical Kick 8-AF.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Loki/ABass Loki A#1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Loki/ABass Loki A-1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Loki/ABass Loki A4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Loki/ABass Loki B3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Loki/ABass Loki C#3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Loki/ABass Loki C1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Loki/ABass Loki C5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Loki/ABass Loki D#2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Loki/ABass Loki D0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Loki/ABass Loki E4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Loki/ABass Loki F#3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Loki/ABass Loki F1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Loki/ABass Loki G#2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Loki/ABass Loki G0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/ABass Res",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/Black Sun/Black Sun C0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/Black Sun/Black Sun C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/Black Sun/Black Sun F#0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/Black Sun/Black Sun F#1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/Bulb Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Dope",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Rage/CBass Rage C1-SF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Sub",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/Doctor",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/FM Noise Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Real Bass/Hose Bass/Hose Bass ff-ASF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Real Bass/Hose Bass/Hose Bass mf-ASF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Real Bass/Hose Bass/Hose Bass P-ASF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Single Samples/Bass Hyped Decay C.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Single Samples/Doom Wave C1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Single Samples/Closed Analog Hi Hat.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Electric Guitars/Cheap Guitar Pluck",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/Edo/Edo 0 127 A#3-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/Edo/Edo 0 127 B0-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/Edo/Edo 0 127 C#2-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/Edo/Edo 0 127 C5-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/Edo/Edo 0 127 D#3-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/Edo/Edo 0 127 D6-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/Edo/Edo 0 127 F#1-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/Edo/Edo 0 127 F4-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/Edo/Edo 0 127 G#2-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Plucked Strings/Edo/Edo 0 127 G5-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Single Samples/12 String Strum/12 String Strum 01.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Glass Mallets/Glass Xylophone/Glass Xylophone C5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Bell1",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Cheap Bell",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Mallet/Mallet C1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Musical Box/Musical Box A#3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Musical Box/Musical Box A#4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Musical Box/Musical Box E3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Musical Box/Musical Box E4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Metal Mallets/Musical Box/Musical Box E5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Synthetic Mallets/Chrono Chime/Chrono Chime pp C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Synthetic Mallets/FM Plunck/FM Plunck C1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Synthetic Mallets/FM Zing",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Kalimba/Kalimba A2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Kalimba/Kalimba C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Kalimba/Kalimba C4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Kalimba/Kalimba D2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Kalimba/Kalimba D3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Kalimba/Kalimba D4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Kalimba/Kalimba F3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Kalimba/Kalimba F4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Kalimba/Kalimba G2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Mallets/Wooden Mallets/Kalimba/Kalimba G3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/80s Classic Synth",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/Lush Bright Pad",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Custom/Angelic Motion-A-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Beautiful Sky/Beautiful Sky C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Beautiful Sky/Beautiful Sky C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Beautiful Sky/Beautiful Sky C4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Beautiful Sky/Beautiful Sky C5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Digital/Oceaxe Pad",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Intro City C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Ambience City/Cafe Ambience.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Impacts/Rising Bubbles C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Circuit Bent/CB Tand 16.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Circuit Bent/CB Tand R25.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Circuit Bent/CB Tand R32.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Single Samples/FB01 Science C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Single Samples/Modular Other World Aug C0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Retro Synth Strings 1",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Retro Synth Strings 3",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Triangle",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Big Multi Layer",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Detuned Trance",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Hi Saw 70",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Hi Saw 90",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Huge Saw",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Modern Analog",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Polyphonic Broad Pulse",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Pulse Sixtyfivef",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Pulse Spike",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Resonant Sequence",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Spreadbox",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Sync HSaw/Sync HSaw C1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/36 BsDrum 4-SF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Catch It-A-S01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/MegaCh48-AF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice A5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice C6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice Eb5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digital Voice/Digital Voice F#5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Follower Pad/Follower Pad C1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Tass Va C6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Amanda Sustain/Amanda Aa/Amanda Aa 1 C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Amanda Sustain/Amanda Aa/Amanda Aa 1 F2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Ah/Solo Arty Ahh A2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Ah/Solo Arty Ahh A3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Ah/Solo Arty Ahh B2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Ah/Solo Arty Ahh C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Ah/Solo Arty Ahh C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Ah/Solo Arty Ahh D2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Ah/Solo Arty Ahh D3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Ah/Solo Arty Ahh E2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Ah/Solo Arty Ahh E3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Ah/Solo Arty Ahh F2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Ah/Solo Arty Ahh F3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Ah/Solo Arty Ahh G2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Ah/Solo Arty Ahh G3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Oo/Solo Arty Oo A2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Oo/Solo Arty Oo A3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Oo/Solo Arty Oo B2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Oo/Solo Arty Oo C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Oo/Solo Arty Oo C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Oo/Solo Arty Oo D2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Oo/Solo Arty Oo D3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Oo/Solo Arty Oo E2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Oo/Solo Arty Oo E3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Oo/Solo Arty Oo F2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Oo/Solo Arty Oo F3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Oo/Solo Arty Oo G2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Arty Sustain/Solo Arty Oo/Solo Arty Oo G3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Cherry Sustain/Cherry Oh/Cherry Oh 1 E3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Speech/Arty Yeah-AF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Speech/Tom Alchemy-AF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Speech/Tom Sound Word-AF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Synth Vocals/Choir Mist",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal Instruments/Vox Beeow mf/Vox Beeow mf C3-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal Instruments/Vox Beeow mf/Vox Beeow mf E3-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal Phrases/Amanda Improv Phrases/Amanda Improv Phrases1/Amanda Improv Phrases 1 0047.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal Phrases/Anastacia Improv Phrases/Anastacia Improv Phrases1/Anastacia Improv Phrases 1 0002-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal Phrases/Anastacia Improv Phrases/Anastacia Improv Phrases4/Anastacia Improv Phrases 4 0011-AF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal Phrases/Anastacia Improv Phrases/Anastacia Improv Phrases5/Anastacia Improv Phrases 5 0014-AF01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Woodwinds/Synth Woodwinds/Blown",
    "~/Music/Logic Pro Library.bundle/Samples/Guitar/Metallic Sustain Guitar 01.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Other/Airy Piano.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bass/Distorted Mod Synth Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bass/Monster Growl Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Simple Synth Intervals.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Single Cycle Waveforms/Single Cycle Modulated Square.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Textures/Drones/Burst Of Air.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Vocals/Female Vocal Ah Short.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Vocals/Female Vocal Ba Dap Bo.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Vocals/Female Vocal Relaxed Melody.caf",
  ]
end
