cask "ml-0007-percussionists" do
  version "75859c094e09e67b16d9950fbc9fbb35-28"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0007_percussionists/ml_0007_percussionists.aar"
  name "Percussion"
  desc "SessionPlayerPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0007_percussionists/ml_0007_percussionists.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0007_percussionists.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Always the Same Bridge Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Always the Same Chorus Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Always the Same Verse Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/By the Fire Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Central Park Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Chorus Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Intro Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Colors in Motion Verse Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Crystal Floors Chorus Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Crystal Floors Verse Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desperate Love Bridge Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desperate Love Chorus Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Desperate Love Verse Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Echoes From Below Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Flying Beyond Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Forever Disco Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Golden Dream Chorus Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Golden Dream Intro Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Golden Dream Verse Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Green Mascara Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Inline Skates Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Keep It Going Chorus Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Keep It Going Verse Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midtown Crew Bridge Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midtown Crew Chorus Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Midtown Crew Verse Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Morning Bloom Percussion 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Morning Bloom Percussion 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Morning Bloom Percussion 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/New York Nights Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Nocturnal Bliss Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Notes on Top Chorus Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Notes on Top Verse Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/SoCal Sun Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Wilted Roses Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Witty Vibes Chorus Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Session Player/Witty Vibes Verse Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Step Sequencer/Boyeros Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Step Sequencer/Cotorro Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Step Sequencer/Guanabacoa Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Step Sequencer/La Tela Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Step Sequencer/Playa Beat.caf",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0007_percussionists.plist",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/03.9s Prince Hall One-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/02 Halls/1.4s_Bright Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/03 Plate Reverbs/1.7s_Blue Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/03 Plate Reverbs/1.8s_Drum Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/05 Gated Reverbs/1.4s_Percussion.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/06 Spring Reverbs/02.8s Rack Spring Bright.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/07 Indoor Spaces/1.4s_Garage.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.4s_Snare Chamber.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/01.2s Recording Room-CTS.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/03 Plate Reverbs/0.5s_Bright Vocals.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/03 Plate Reverbs/1.3s_Nice Small Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/06 Spring Reverbs/1.4s_AmpSpring.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/07 Indoor Spaces/1.0s_Short Ramp.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/05 Warped/05 Ghost Rhythms/80 BPM/Ghost Rhythm 80 BPM 7.aif",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Agogo High.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Agogo High.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Agogo High.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Agogo High.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Agogo Low.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Agogo Low.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Agogo Low.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Agogo Low.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo High Stick.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo High Stick.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo High Stick.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo High Stick.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo High.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo High.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo High.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo High.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo Low Stick.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo Low Stick.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo Low Stick.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo Low Stick.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo Low.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo Low.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo Low.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Bongo Low.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cabasa.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cabasa.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cabasa.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cabasa.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cajon Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cajon Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cajon Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cajon Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cajon Snare.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cajon Snare.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cajon Snare.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cajon Snare.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Castanets.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Castanets.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Castanets.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Castanets.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Chimes.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Chimes.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Chimes.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Chimes.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Claps.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Claps.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Claps.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Claps.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Claves.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Claves.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Claves.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Claves.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga Bright High.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga Bright High.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga Bright High.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga Bright High.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga Bright Low.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga Bright Low.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga Bright Low.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga Bright Low.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga High.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga High.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga High.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga High.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga Low.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga Low.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga Low.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Conga Low.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cowbell Dry.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cowbell Dry.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cowbell Dry.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cowbell Dry.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cowbell.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cowbell.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cowbell.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Cowbell.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Jam Block High.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Jam Block High.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Jam Block High.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Jam Block High.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Jam Block Low.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Jam Block Low.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Jam Block Low.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Jam Block Low.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Maracas Dark.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Maracas Dark.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Maracas Dark.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Maracas Dark.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Maracas.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Maracas.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Maracas.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Maracas.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shaker Caxixi.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shaker Caxixi.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shaker Caxixi.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shaker Caxixi.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shaker Heavy.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shaker Heavy.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shaker Heavy.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shaker Heavy.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shaker Studio.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shaker Studio.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shaker Studio.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shaker Studio.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shekere.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shekere.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shekere.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Shekere.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Sleigh Bells Vintage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Sleigh Bells Vintage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Sleigh Bells Vintage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Sleigh Bells Vintage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Sleigh Bells.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Sleigh Bells.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Sleigh Bells.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Sleigh Bells.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Snaps.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Snaps.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Snaps.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Snaps.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Stomps.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Stomps.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Stomps.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Stomps.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Tambourine Dimple.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Tambourine Dimple.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Tambourine Dimple.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Tambourine Dimple.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Tambourine Vintage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Tambourine Vintage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Tambourine Vintage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Tambourine Vintage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Tambourine.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Tambourine.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Tambourine.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Tambourine.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Timbale High.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Timbale High.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Timbale High.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Timbale High.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Timbale Low.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Timbale Low.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Timbale Low.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Timbale Low.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Timbale Mid.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Timbale Mid.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Timbale Mid.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Timbale Mid.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Triangle Mute.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Triangle Mute.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Triangle Mute.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Triangle Mute.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Triangle.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Triangle.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Triangle.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Triangle.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Wood Block High.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Wood Block High.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Wood Block High.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Wood Block High.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Wood Block Low.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Wood Block Low.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Wood Block Low.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/10 Acoustic Percussion/Wood Block Low.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Blocks & Bells Performance.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Blocks & Bells Performance.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Blocks & Bells Performance.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Blocks & Bells Performance.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Bongos Performance.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Bongos Performance.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Bongos Performance.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Bongos Performance.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Bongos Stick Performance.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Bongos Stick Performance.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Bongos Stick Performance.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Bongos Stick Performance.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Cajon Performance.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Cajon Performance.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Cajon Performance.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Cajon Performance.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Claps & Snaps Performance.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Claps & Snaps Performance.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Claps & Snaps Performance.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Claps & Snaps Performance.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/AgogoHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/AgogoLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/BlocksBells.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/BongoHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/BongoLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Cabasa.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Cajon.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/CajonBass.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/CajonSnare.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Castanets.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Chimes.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Claps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Claves.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/CongaBongo.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/CongaHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/CongaLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Cowbell.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/JamBlockHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/JamBlockLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Shaker.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/ShakerCaxixi.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Shekere.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/SleighBells.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Snaps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Stomps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/StompsClap.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Tambourine.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/TambourineDimple.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/TimbaleHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/TimbaleLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/TimbaleMid.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/Triangle.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/TriangleMute.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/WoodBlockHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop+.patch/WoodBlockLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Coffee Shop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Conga Bright Performance.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Conga Bright Performance.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Conga Bright Performance.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Conga Bright Performance.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Conga Performance.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Conga Performance.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Conga Performance.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Conga Performance.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/1__#$!@%!#__Tambourine.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/AgogoHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/AgogoLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/BlocksBells.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/BongoHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/BongoLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Cabasa.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/CajonBass.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/CajonSnare.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Castanets.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Chimes.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Claps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Claves.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/CongaBongo.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/CongaHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/CongaLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/CowbellDry.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/JamBlockHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/JamBlockLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Maracas.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Shaker.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Shekere.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/SleighBellsVintage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Snaps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Stomps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/StompsClaps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Tambourine.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/TimbaleHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/TimbaleLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/TimbaleMid.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Timbales.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/Triangle.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/TriangleMute.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/WoodBlockHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Disco Percussion+.patch/WoodBlockLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/1__#$!@%!#__Tambourine.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/AgogoHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/AgogoLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/BlocksBells.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Bongo.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/BongoHighStick.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/BongoLowStick.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Cabasa.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/CajonBass.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/CajonSnare.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Castanets.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Chimes.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Claps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Claves.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Conga.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/CongaHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/CongaLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Cowbell.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/JamBlockHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/JamBlockLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Shaker.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/ShakerStudio.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Shekere.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/SleighBells.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Snaps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Stomps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/StompsClaps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Tambourine.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/TimbaleHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/TimbaleLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/TimbaleMid.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/Triangle.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/TriangleMute.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/WoodBlockHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Electronic Percussion+.patch/WoodBlockLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/AgogoHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/AgogoLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/BlocksBells.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/BongoHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/BongoLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Cabasa.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/CajonBass.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/CajonSnare.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Castanets.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Chimes.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Claps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Claves.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/CongaBongo.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/CongaBrightHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/CongaBrightLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/CowbellDry.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/JamBlockHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/JamBlockLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Maracas.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Shaker.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Shekere.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/SleighBellsVintage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Snaps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Stomps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/StompsClaps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Tambourine.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/TambourineVintage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/TimbaleHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/TimbaleLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/TimbaleMid.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Timbales.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/Triangle.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/TriangleMute.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/WoodBlockHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin+.patch/WoodBlockLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Latin.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/AgogoHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/AgogoLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/BlocksBells.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/BongoHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/BongoLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/Cabasa.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/CajonBass.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/CajonSnare.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/Castanets.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/Chimes.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/Claps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/Claves.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/CongaBongo.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/CongaBrightLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/CongaLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/CowbellDry.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/JamBlockHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/JamBlockLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/MaracasDark.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/Shaker.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/Shekere.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/SleighBellsVintage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/Snaps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/Stomps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/StompsClaps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/Tambourine.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/TambourineDimple.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/TimbaleHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/TimbaleLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/TimbaleMid.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/Timbales.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/Triangle.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/TriangleMute.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/WoodBlockHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Pawn Shop Percussion+.patch/WoodBlockLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/AgogoHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/AgogoLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/BlocksBells.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Bongo.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/BongoHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/BongoLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Cabasa.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/CajonBass.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/CajonSnare.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Castanets.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Chimes.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Claps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Claves.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Conga.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/CongaHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/CongaLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/CowbellDry.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/JamBlockHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/JamBlockLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/MaracasDark.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Noise.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Shaker.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Shekere.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/SleighBellsVintage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Snaps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Stomps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/StompsClaps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Tambourine.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/TambourineVintage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/TimbaleHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/TimbaleLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/TimbaleMid.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/Triangle.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/TriangleMute.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/WoodBlockHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Retro Percussion+.patch/WoodBlockLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Shaker 1 Performance.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Shaker 1 Performance.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Shaker 1 Performance.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Shaker 1 Performance.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Shaker 2 Performance.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Shaker 2 Performance.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Shaker 2 Performance.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Shaker 2 Performance.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/1__#$!@%!#__Tambourine.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/AgogoHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/AgogoLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/BlocksBells.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Bongo.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/BongoHighStick.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/BongoLowStick.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Cabasa.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/CajonBass.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/CajonSnare.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Castanets.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Chimes.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Claps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Claves.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Conga.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/CongaHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/CongaLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Cowbell.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/JamBlockHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/JamBlockLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Shaker.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/ShakerStudio.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Shekere.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/SleighBells.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Snaps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Stomps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/StompsClaps.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Tambourine.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/TimbaleHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/TimbaleLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/TimbaleMid.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/Triangle.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/TriangleMute.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/WoodBlockHigh.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio+.patch/WoodBlockLow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Studio.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Tambourines Performance.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Tambourines Performance.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Tambourines Performance.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Tambourines Performance.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Timbales Performance.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Timbales Performance.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Timbales Performance.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Percussion/Timbales Performance.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Percussion/Coffee Shop Percussion.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Percussion/Latin Percussion.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Percussion/Performance Instruments",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Percussion/Single Instruments",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Percussion/Studio Percussion.exs",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Agogo_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Bongo Stick_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Bongo_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Cabasa_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Cajon_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Castanets_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Chimes_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Claps_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Claves_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Conga Bright_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Conga_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Cowbell Dry_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Cowbell_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Jam Block_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Maracas Dark_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Maracas_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Shaker Caxixi_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Shaker Heavy_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Shaker Studio_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Shekere_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Sleigh Bells Vintage_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Sleigh Bells_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Snaps_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Stomps_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Tambourine Dimple_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Tambourine Vintage_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Tambourine_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Timbales_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Triangle_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Percussion/Wood Block_consolidated.caf",
  ]
end
