cask "ml-0040-vocalloops" do
  version "b0488af0110dbbc94ddb6a889ba66be1"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0040_vocalloops/ml_0040_vocalloops.aar"
  name "VoxMelodics"
  desc "VocalPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_0040_vocalloops/ml_0040_vocalloops.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_0040_vocalloops.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ava Heatwave Ad Lib.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ava Heatwave Hook 01 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ava Heatwave Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ava Heatwave Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ava Heatwave Oh Ah Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ava Heatwave Oh Ah.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ava Heatwave Verse.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Cole Dollars Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Cole Dollars Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Cole Dollars One Shot 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Cole Dollars One Shot 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Cole Dollars One Shot 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Cole Dollars One Shot 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Cole Dollars One Shot 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Cole Dollars Verse.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 01 Harmony High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 01 Harmony Mid Double.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 01 Harmony Mid-High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 01 Harmony Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 01 Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 02 Harmony High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 02 Harmony Mid Double.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 02 Harmony Mid-High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 02 Harmony Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 03 Harmony High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 03 Harmony Low-Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 03 Harmony Mid Double.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 03 Harmony Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 04 Harmony High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 04 Harmony Mid-High Double.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 04 Harmony Mid-High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 04 Harmony Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 05 Harmony High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 05 Harmony Mid-High Double.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 05 Harmony Mid-High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 05 Harmony Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 06 Harmony High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 06 Harmony Mid Double.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 06 Harmony Mid-High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 06 Harmony Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 06 Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 07 Harmony High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 07 Harmony Mid Double.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 07 Harmony Mid-High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 07 Harmony Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 08 Harmony Mid Double.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 08 Harmony Mid-High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 08 Harmony Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding 08 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding Ad Lib.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding Oh Ah 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding Oh Ah 02 Harmony Mid-High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding Oh Ah 02 Harmony Mid-Low.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Hiding Oh Ah 02 Harmony Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Ad Lib 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Ad Lib 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Ad Lib 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Hook 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Hook 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Hook 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Oh Ah 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Oh Ah 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Oh Ah 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Verse 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Verse 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Verse 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Verse 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Verse 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Verse 06 Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Verse 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Morning Verse 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Spin Hook.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Spin Oh Ah.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Spin Verse 01 Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Spin Verse 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Spin Verse 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Spin Verse 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Spin Verse 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Ad Lib 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Ad Lib 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Ad Lib 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Ad Lib 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Hook 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Hook 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Oh Ah 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Oh Ah 02 Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Oh Ah 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Oh Ah 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless One Shot 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless One Shot 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless One Shot 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless One Shot 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless One Shot 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless One Shot 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless One Shot 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless One Shot 08.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Verse 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Verse 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Verse 03 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Verse 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Verse 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Verse 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Verse 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Verse 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Verse 08.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Max Timeless Verse 09.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Ad Lib 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Ad Lib 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Ad Lib 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Ad Lib 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Hook 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Hook 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Hook 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Hook 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Hook 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Hook 08.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Hook 09.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Hook 10 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Hook 10.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Oh Ah 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Oh Ah 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Oh Ah 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Verse 01 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Verse 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Verse 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Verse 03 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Verse 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Verse 04 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Verse 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Automatic Verse 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Ad Lib 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Ad Lib 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Ad Lib 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Ad Lib 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Ad Lib 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Hook 02 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Hook 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Hook 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Hook 05 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Hook 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Hook 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Hook 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Hook 08.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Hook 09.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Oh Ah 01 Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Oh Ah 01 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Oh Ah 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Oh Ah 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Oh Ah 03 Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Oh Ah 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Oh Ah 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Oh Ah 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Oh Ah 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight One Shot.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Vocoder FX 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby No Fight Vocoder FX 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 01 Harmony High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 01 Harmony Low.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 01 Harmony Mid-High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 01 Harmony Mid-Low.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 01 Harmony Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 01 Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 02 Harmony High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 02 Harmony Low.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 02 Harmony Mid-High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 02 Harmony Mid-Low.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 02 Harmony Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 03 Harmony Mid-High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 03 Harmony Mid-Low.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 03 Harmony Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 03 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 04 Harmony High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 04 Harmony Low.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 04 Harmony Mid-High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 04 Harmony Mid-Low.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 04 Harmony Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 05 Harmony High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 05 Harmony Low.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 05 Harmony Mid-High.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 05 Harmony Mid-Low.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 05 Harmony Mid.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise 05 Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Ruby Sunrise Hook.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Ad Lib FX 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Ad Lib FX 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Ad Lib FX 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Ad Lib FX 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Ad Lib FX 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Ad Lib FX 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Ad Lib FX 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Ad Lib FX 08.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Ad Lib FX 09.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Ad Lib FX 10.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Ad Lib FX 11.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Ad Lib FX 12.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Ad Lib FX 13.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 08.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 09.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 10.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 11.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 12.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 13.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 14.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 15.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 16.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 17.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 18.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 19.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 20.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 21.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 22.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 23.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 24.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 25.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 26.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 27.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 28.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 29.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 30.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 31.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 32.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 33.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 34.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 35.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 36.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 37.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 38.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 39.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 40.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 41.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 42.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 43.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 44.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 45.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 46.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Chop FX 47.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Glitch FX 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Glitch FX 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Glitch FX 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Glitch FX 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Glitch FX 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Glitch FX 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Lead FX 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Lead FX 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Lead FX 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Lead FX 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Lead FX 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Lead FX 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Lead FX 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Lead FX 08.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Lead FX 09.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Lead FX 10.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Lead FX 11.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Oh Ah FX 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Oh Ah FX 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Oh Ah FX 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 08.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 09.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 10.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 11.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 12.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 13.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 14.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 15.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 16.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 17.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 18.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 19.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 20.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 21.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 22.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 23.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 24.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 25.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 26.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox One Shot FX 27.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Pad FX 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Pad FX 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Pad FX 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 08.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 09.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 10.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 11.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 12.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 13.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 14.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 15.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 16.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Rhythmic FX 17.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Riser FX 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Riser FX 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Vox Riser FX 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Calls Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Calls Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Calls Oh Ah 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Calls Oh Ah 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Calls Oh Ah 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Calls Oh Ah 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Calls Oh Ah 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Calls Verse 01 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Calls Verse 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Calls Verse 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Calls Verse 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Calls Verse 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Hook 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Hook 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Hook 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Hook 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Hook 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Hook 08.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Oh Ah 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Oh Ah 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Oh Ah 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Oh Ah 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Oh Ah 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Oh Ah 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Oh Ah 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Verse 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Verse 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Verse 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Game Plan Verse 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Ad Lib 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Ad Lib 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Ad Lib 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Ad Lib 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Ad Lib 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Ad Lib 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Ad Lib 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Ad Lib 08.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Ad Lib 09.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Ad Lib 10.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Ad Lib 11.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Ad Lib 12.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Hook 02 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Hook 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Oh Ah.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience One Shot 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience One Shot 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience One Shot 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience One Shot 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience One Shot 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience One Shot 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience One Shot 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience One Shot 08.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience One Shot 09.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience One Shot 10.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience One Shot 11.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience One Shot 12.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Verse 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Verse 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Verse 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Verse 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Verse 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Verse 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Patience Verse 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Pockets Hook.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Pockets Oh Ah.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Pockets One Shot.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Pockets Verse 01 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Pockets Verse 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zane Pockets Verse 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Heartbeat Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Heartbeat Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Heartbeat Hook 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Heartbeat Hook 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Heartbeat Hook 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Heartbeat Verse 01 Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Heartbeat Verse 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Heartbeat Verse 02 Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Heartbeat Verse 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Heartbeat Verse 03 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Heartbeat Verse 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Ice Chill Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Ice Chill Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Ice Chill Hook 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Ice Chill Hook 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Ice Chill One Shot 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Ice Chill One Shot 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Ice Chill One Shot 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Ice Chill One Shot 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Ice Chill Verse 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Ice Chill Verse 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Mind Games Ad Lib 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Mind Games Ad Lib 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Mind Games Hook Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Mind Games Hook.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Mind Games Oh Ah.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Mind Games One Shot Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Mind Games Verse.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Ad Lib 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Ad Lib 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Ad Lib 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Ad Lib 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Ad Lib 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Ad Lib 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 06 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 06.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 07.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 08 Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 08.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 09.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 10.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 11.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 12.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 13 Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 13.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Hook 14.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Oh Ah.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Verse 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Verse 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Verse 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Verse 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Nevermore Verse 05.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Ad Lib 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Ad Lib 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Ad Lib 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Hook 01 Vox FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Hook 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Oh Ah 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Oh Ah 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Oh Ah 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Oh Ah 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime One Shot.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Verse 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Verse 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Verse 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Verse 04 Vocoder FX.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Playtime Verse 04.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Story Ad Lib.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Story Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Story Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Story Hook 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Story One Shot 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Story One Shot 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Story One Shot 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Story Verse 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Story Verse 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Story Verse 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Sunbreak Hook 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Sunbreak Hook 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Sunbreak Hook 03.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Sunbreak Oh Ah.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Sunbreak Verse 01.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Sunbreak Verse 02.caf",
    "～/Music/Logic Pro Library.bundle/Apple Loops/Vox Melodics/Zoe Sunbreak Verse 03.caf",
    "～/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_0040_vocalloops.plist",
  ]
end
