cask "ml-apc0005-tommisch" do
  version "fb440d305aee93cc2541bf7ab91f3316-10"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0005_tommisch/ml_apc0005_tommisch.aar"
  name "TomMisch"
  desc "ProducerPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0005_tommisch/ml_apc0005_tommisch.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_apc0005_tommisch.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Beginning Tonight Acoustic Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Bone Dry Break 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Bone Dry Break 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Bright Tambourine Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Brush Work Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Bubble Beat Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Candlelight Glow Acoustic Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Classic Tambourine Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Clockwork Hi-Hat Topper 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Clockwork Hi-Hat Topper 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Conga Break Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Crunchy Soul Break 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Crunchy Soul Break 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Deep Feels Soul Break 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Deep Feels Soul Break 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Deep Feels Soul Break 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Deep Feels Soul Break 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Deep Feels Soul Break 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Deep Soul Acoustic Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Deep Toms Break 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Deep Toms Break 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Deep Toms Break 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Digging Deep Soul Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Downtown Sound Sax 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Downtown Sound Sax 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Downtown Sound Sax 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Downtown Sound Sax 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Downtown Sound Sax Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Downtown Sound Sax Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Easy Going Hi-Hat Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Ever Unresolved Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Feeling The Flow Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Feeling The Flow Guitar Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Feeling The Flow Guitar Double.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Feeling The Flow Guitar Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Feeling The Flow Guitar Solo.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Feeling The Flow Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Feeling The Flow Synth Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Feeling The Flow Synth Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Feeling The Flow Vocal 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Feeling The Flow Vocal 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Feeling The Flow Vocal 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Hard Knocking Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Heavy Steady Hi-Hat Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Home Sweet Home Strings.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Hopeful Look Guitar Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Hopeful Look Strings.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Knocking Congas Topper 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Knocking Congas Topper 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Knocking Congas Topper 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Laid Back Soul Break 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Laid Back Soul Break 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Lazy Turnaround Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Listen Up Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Listen Up Glockenspiel.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Listen Up Guitar Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Listen Up Picked Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Listen Up Picked Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Listen Up Picked Guitar 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Listen Up Rhythm Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Listen Up Synth Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Lo-Fi Brushes Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Lo-Fi Funk Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Lush Snare Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Meadow Glow Strings.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Midnight Moves Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Midnight Moves Guitar Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Midnight Moves Lead Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Midnight Moves Picked Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Midnight Moves Picked Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Midnight Moves Picked Guitar 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Midnight Moves Rhythm Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Midnight Moves Vocal 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Midnight Moves Vocal 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Moonlight Swoon Acoustic Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Never Miss Rhythm Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Perked Up Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Phasing Congas Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Phasing Hi-Hat Topper 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Phasing Hi-Hat Topper 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Relaxed Half Time Break 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Relaxed Half Time Break 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Relaxing House Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Rising Star Acoustic Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Rolling Hi-Hat Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Salty Popcorn Break 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Salty Popcorn Break 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Salty Popcorn Break 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Seventies Turnaround Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Shimmering Piano Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Shuffling Snare Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Shuffling Vintage Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Silver Sky Acoustic Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Silver Sky Acoustic Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Silver Sky Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Silver Sky Guitar Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Silver Sky Guitar Picking.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Silver Sky Guitar Strums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Silver Sky Sax.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Silver Sky String Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Silver Sky Strings.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Simple Steady Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Slow Vibes Break 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Slow Vibes Break 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Slow Vibes Break 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Sly Vibes Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Sly Vibes Guitar Chime.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Sly Vibes Guitar Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Sly Vibes Lead Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Sly Vibes Picked Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Sly Vibes Picked Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Sly Vibes Wah Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Smooth Turnaround Fill.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Soft Disco Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Soft Slice Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Steady Funk Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Sweet Chilled Break 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Sweet Chilled Break 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Sweet Disco String Run FX.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Sweet Disco String Slide FX.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Sweet Snare Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Swept Up Sax 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Swept Up Sax 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Swept Up Sax Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Thick Laid-back Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Thick Laid-back Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Thick Laid-back Beat 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Top Down Drive Guitar Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Top Down Drive Guitar Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Top Down Drive Guitar Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Top Down Drive Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Top Down Drive Synth Clav.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Top Down Drive Synth FX 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Top Down Drive Synth FX 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Top Down Drive Synth Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Uptempo Driving Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Uptempo Funk Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Vintage Fill Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Vintage Soul Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Vision of Beauty String Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Vision of Beauty String Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tom Misch/Warm Fireside Acoustic Piano.caf",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_apc0005_tommisch.plist",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/03 Plate Reverbs/0.7s_Drum Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/Bells1AgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/Bells2AgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/Bells3AgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/CastanetAgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/ClapAgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/Click1AgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/Click2AgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/CowbellAgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/CrashAgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/HiHatAgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/HiHatOpenAgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/Kick1AgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/Kick2AgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/Shaker1AgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/Shaker2AgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/Snare1AgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/Snare2AgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/TomLowAgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Agogo Funk.patch/WoodblockAgogoFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/ClapLoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/ClickLoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/CrashLoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/Djembe1LoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/Djembe2LoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/HiHatLoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/HiHatOpenLoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/Kick1LoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/Kick2LoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/RideLoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/RimLoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/ShakerLoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/Snare1LoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/Snare2LoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/TomLowLoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Funk.patch/TomMidLoFiFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/CabasaUptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/ClapUptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/CrashUptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/DrumstickUptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/HiHatOpenUptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/HiHatUptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/Kick1UptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/Kick2UptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/Perc1UptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/Perc2UptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/ReverseClapUptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/RideUptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/ShakerUptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/Snare1UptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/Snare2UptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/TomLowUptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Uptown Flow.patch/TomMidUptownFlow.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Reverse Clap - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Reverse Clap - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Reverse Clap - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Reverse Clap - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Cabasa - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Cabasa - Uptown Flow.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Cabasa - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Cabasa - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Cabasa - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Lo-Fi Funk.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Uptown Flow.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Agogo Funk.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Agogo Funk.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bells 1 - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bells 1 - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bells 1 - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bells 1 - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bells 2 - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bells 2 - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bells 2 - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bells 2 - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bells 3 - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bells 3 - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bells 3 - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bells 3 - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Castanet - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Castanet - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Castanet - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Castanet - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Click - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Click - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Click - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Click - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Click 1 - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Click 1 - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Click 1 - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Click 1 - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Click 2 - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Click 2 - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Click 2 - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Click 2 - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Djembe 1 - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Djembe 1 - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Djembe 1 - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Djembe 1 - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Djembe 2 - Lo-Fi Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Djembe 2 - Lo-Fi Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Djembe 2 - Lo-Fi Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Djembe 2 - Lo-Fi Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Drumstick - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Drumstick - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Drumstick - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Drumstick - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Uptown Flow.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Uptown Flow.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Uptown Flow.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Uptown Flow.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Agogo Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Agogo Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Agogo Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Agogo Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Guitar/Processed/Phasing Guitar Plucks.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Guitar/Processed/Phasing Guitar Plucks.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Guitar/Processed/Phasing Guitar Plucks.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Guitar/Processed/Phasing Guitar Plucks.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Small Amped Acoustic Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Small Amped Acoustic Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Small Amped Acoustic Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Small Amped Acoustic Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Processed/Smooth Echo Clav.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Processed/Smooth Echo Clav.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Processed/Smooth Echo Clav.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Clavinet/Processed/Smooth Echo Clav.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Deep Bass Tines Electric Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Deep Bass Tines Electric Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Deep Bass Tines Electric Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Deep Bass Tines Electric Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Deep Drive Electric Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Deep Drive Electric Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Deep Drive Electric Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Deep Drive Electric Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Dreamy Smooth Vox.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Dreamy Smooth Vox.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Dreamy Smooth Vox.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Dreamy Smooth Vox.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Ghostly Reversed Organ.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Ghostly Reversed Organ.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Ghostly Reversed Organ.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Organ/Processed/Ghostly Reversed Organ.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Processed/Sweet Overdrive Kalimba.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Processed/Sweet Overdrive Kalimba.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Processed/Sweet Overdrive Kalimba.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Mallet/Processed/Sweet Overdrive Kalimba.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Spaced Out Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Spaced Out Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Spaced Out Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Spaced Out Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/West Coast Analog Synth Lead.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/West Coast Analog Synth Lead.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/West Coast Analog Synth Lead.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/West Coast Analog Synth Lead.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Agogo Funk Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Uptown Flow Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Guitar/Processed/Phasing Guitar Plucks.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Processed/Small Amped Acoustic Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Other/Dreamy Smooth Vox.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Mallet/Processed/Sweet Overdrive Kalimba.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Other Strings/Erhu.exs",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Tom Misch.logicx/Alternatives/000/DisplayState.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Tom Misch.logicx/Alternatives/000/DisplayStateArchive",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Tom Misch.logicx/Alternatives/000/MetaData.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Tom Misch.logicx/Alternatives/000/ProjectData",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Tom Misch.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Tom Misch.logicx/Contents/Resources/template.tif",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Tom Misch.logicx/Contents/Resources/template_ios.png",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Tom Misch.logicx/Resources/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Tom Misch.logicx/Resources/ProjectInformation.plist",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Bells 1 - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Bells 2 - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Bells 3 - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Castanet - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Clap - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Click 1 - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Click 2 - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Cowbell - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Crash - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Hi-Hat Closed - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Hi-Hat Open - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Kick 1 - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Kick 2 - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Shaker 1 - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Shaker 2 - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Snare 1 - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Snare 2 - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Tom Low - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Agogo Funk Kit/Woodblock - Agogo Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Clap - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Click - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Crash - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Djembe 1 - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Djembe 2 - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Hi-Hat Closed - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Hi-Hat Open - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Kick 1 - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Kick 2 - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Ride - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Rimshot - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Shaker - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Snare 1 - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Snare 2 - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Tom Low - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Funk Kit/Tom Mid - Lo-Fi Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Cabasa - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Clap - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Crash - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Drumstick - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Hi-Hat Closed - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Hi-Hat Open - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Kick 1 - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Kick 2 - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Perc 1 - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Perc 2 - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Reverse Clap - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Ride - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Shaker - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Snare 1 - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Snare 2 - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Tom Low - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Uptown Flow Kit/Tom Mid - Uptown Flow.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Guitar/Processed/Phasing Guitar Plucks.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Processed/Small Amped Acoustic Piano.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Other/Dreamy Smooth Vox.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Mallet/Processed/Sweet Overdrive Kalimba.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Other Strings/Erhu_consolidated.caf",
  ]
end
