cask "ml-apc0012-thekount" do
  version "42cb270593a49d08b88dfcc15c0527d4-15"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0012_thekount/ml_apc0012_thekount.aar"
  name "TheKount"
  desc "ProducerPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0012_thekount/ml_apc0012_thekount.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_apc0012_thekount.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Almost Awake Tambourine.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Almost Perfect Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Altered Gravity Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Analog Dream Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Ancient Story Bass Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Ancient Story Flute.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Art From The Lab Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Autumn Sun Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Axe Heavy Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Back To The Booth Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Bamboo Hall Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Basement Vinyl Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Bass Bombshell Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Beast Mode Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Better And Better Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Beyond Claps Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Big Body Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Blackbelt Moves Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Blow Out Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Blowing Bubbles Layers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Body Language Clav.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Body Language Funk Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Body Language Synth Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Body Move Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Bounce Tight Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Bouncy Shells Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Bountiful Bounty Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Bountiful Bounty Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Bountiful Bounty Percussion 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Bountiful Bounty Percussion 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Bountiful Bounty Percussion 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Bountiful Bounty Percussion 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Brassy Science Arp Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Bring The Disco Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Bueno Space Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Business As Usual Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Buzzin Bossa Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Buzzin Bossa Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Calling From Beyond Vox.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Car Lot Heat Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Chipper Drum Machine Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Clap Clockwork Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Clap Clockwork Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Clap Disco Bop Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Claptrap Bells.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Claptrap Machine Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Classic Bossy Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Clockwork Clatter Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Cobra Subsonics Synth Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Collapsing Structure Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Come Around Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Cosmic Pothole Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Crackle'n Pop Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Crystal Sun Glow Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Curious Squares Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Dancing Triangle Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Deep Dreamtime Bass Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Deep Dreamtime Music Box.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Deep Dreamtime Synth Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Deep Dreamtime Synth Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Deep Swirls Brush Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Depth Charge Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Depth Charge Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Digital Bronze Age Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Dippin Down Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Disco Nebula Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Disco Nebula Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Distant Expedition Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Distant Music Box.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Double Shaker Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Dreaming Tonight Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Drive Through Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Driving Everyday Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Dusty Drum Machine Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Easy Lockout Glockenspiel.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Easy Lockout Glockensynth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Elevator Ride Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Endless Drive Shakers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Enigmatic Shake Tambourine.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Falling and Falling Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Fat Cabasa Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Floating Tremolo Electric Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Floating Tremolo Electric Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Fluttering Flight Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Following Flow Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Fools Flow Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/For You Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Forgotten Temple Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Full Realization Minimal Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Full Realization Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Glide On Out Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Going Deep Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Good Love Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Grimy Ride Slider Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Handy Helper Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Handy Helper Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Hard Cut Life Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Hard Cut Life Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Hardly Percussion Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Haunting Halls Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Heavy Break Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Heavy Mood Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Heavy Swing Tambourine.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Hollow Deluxe Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Hovering UFO Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Hyper Drum Circle Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Hyper Drum Circle Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Hyper Drum Circle Beat 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Ideal Intervals Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Ideal Intervals Synth 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Ideal Intervals Synth 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Ideal Intervals Synth Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Ideal Intervals Synth Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Ideal Intervals Vibraphone.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/In A Mood Layers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/In-The-Pocket Clave.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/In-The-Pocket Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Interdimensional Traveler Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Jangle Triangle Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Journey Through Feels Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Joy Decision Layers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Just Bopp'n Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Koto Strummer Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/La Bella Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Lap Of Luxury Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Lean On In Layers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Leaving You Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Little Disco Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Little Disco Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/LoFi Noisy Claps.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Loose Cabasa Percussion 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Loose Cabasa Percussion 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Lovely Shuffle Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Luminous Piano Whispers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Magical Bounce Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Monk's Focus Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Mood Swing Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/More Than Perfect Hi-Hats 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/More Than Perfect Hi-Hats 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Moving Magnitude Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Mystic Rattle Bells Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Neo Waves Arp Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Neo Waves Layers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Noisy Crickets Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Old Vinyl Discovery Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Parallel Universe Arp Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Parallel Universe Layers 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Parallel Universe Layers 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Parallel Universe Layers 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Park Street Chime Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Park Street Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Patient Anticipation Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Penny Pockets Tambourine.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Percussive Mayhem Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Perfect Claps Percussion 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Perfect Claps Percussion 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Phasing Drive Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Photogenic Knocks Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Pleased As Punch Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Pocket Full Of Change Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Pyramid Dreams Layers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Pyramid Dreams Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Raw Bounce Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Raw Bounce Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Raw Rattle Tambourine.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Ready For Battle Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Real Raw Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Rhythm of Delight Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Rhythm of Delight Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Rich Vinyl Vibe Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Rich Vinyl Vibe Layers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Roomy Ride Cymbal.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Root Down Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Root Down Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Rough and Refined Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Sampled Dreams Electric Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Sampled Dreams Electric Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Saucy Space Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Savory Vintage Clap Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Serving Braindance Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Shadow Curiosity Layers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Shaker Shockwave Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Shaker Shockwave Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Shaker Shockwave Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Shaker Shockwave Shaker.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Shrug Soul Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Silky Cascades Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Silky Stabs Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Slappin Disco Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Sleight of Hand Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Slow Down Soul Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Slow Down Soul Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Slow Down Soul Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Slow Graffiti Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Slow Love Layers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Slow Spring Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Sly Strings Shadow Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Sly Syncopation Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Smoky Disco Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Smoky Disco Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Smooth Room Tambourine.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Sneaky Sidequest Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Soaring Skywards Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Soaring Skywards Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Soaring Skywards Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Soaring Skywards Synth Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Soaring Skywards Synth Plucks.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Solid And Steady Tambourine.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Solid Slot Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Soothing Smoov Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Spicy Pickled Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Steeling The Scene.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Sticks and Stones Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Straight Up Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Subaquatic Thump Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Super Soul Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Supernatural Enigma Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Sweet Talk Synths 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Sweet Talk Synths 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Sync Attack Synth 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Sync Attack Synth 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Tapestry of Dreams Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/The Kid Synth Layers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/The Time Has Come Layers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/The Time Has Come Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Thick and Nasty Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Thick and Nasty Tambourine.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Thick Mystical Drift Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Thrift Shop Treasure Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Tight Knuckle Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Tight Knuckle Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Til Tomorrow Synth 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Til Tomorrow Synth 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Tingle Space Topper.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Trust Me Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Tunnel Vision Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Two Track Tape Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Ultimate Challenger Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Unwinding Wild Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Up Energy Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Up Energy Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Video Taped Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Vintage Ghost Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Vintage Vibe Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Warm Sunlight Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Weird Pocket Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/World's Best Handclaps.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Worldly Voyage Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Woven Dreams Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Woven Dreams Horns.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Woven Dreams Synths.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/The Kount/Zoned Incantation Beat.caf",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_apc0012_thekount.plist",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/03 Plate Reverbs/0.7s_Drum Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/Clap1AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/Clap2AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/HiHat1AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/HiHat2AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/HiHat3AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/HiHat4AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/Kick1AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/Kick2AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/PercAncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/PercFX1AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/PercFX2AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/RimAncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/Snare1AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/Snare2AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/Tambourine1AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/Tambourine2AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/Tambourine3AncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Ancient Space.patch/WoodblockAncientSpace.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/ChimesDarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/Clap1DarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/Clap2DarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/CymbalDarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/FlexatoneDarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/HiHat1DarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/HiHat2DarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/HiHatOpenDarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/Kick1DarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/Kick2DarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/Kick3DarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/RimDarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/ShakerDarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/SnapDarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/SnareDarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/SnareRollDarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/TambourineDarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Dark Mystic.patch/TomHighDarkMystic.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/Clap1ShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/Clap2ShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/ClaveShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/Cowbell1ShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/Cowbell2ShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/HiHat1ShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/HiHat2ShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/HiHatOpenShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/Kick1ShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/Kick2ShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/PercFXShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/PercShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/RideShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/RimShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/ShakerShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/Snare1ShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/Snare2ShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Shell Game.patch/TambourineShellGame.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare Roll - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare Roll - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare Roll - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare Roll - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare Roll - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 4 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 4 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 4 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 4 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Clave - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 1 - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 1 - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 1 - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 1 - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 1 - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 2 - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 2 - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 2 - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 2 - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Cowbell 2 - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Flexatone - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Flexatone - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Flexatone - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Flexatone - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Flexatone - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 1 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 1 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 1 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 1 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 2 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 2 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 2 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 2 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Dark Mystic.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Dark Mystic.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Dark Mystic.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Dark Mystic.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Dark Mystic.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Shell Game.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Shell Game.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Shell Game.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Shell Game.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Shell Game.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine 1 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine 1 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine 1 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine 1 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine 2 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine 2 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine 2 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine 2 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine 3 - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine 3 - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine 3 - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine 3 - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Ancient Space.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Ancient Space.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Ancient Space.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Woodblock - Ancient Space.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Ancient Space Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Dark Mystic Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Shell Game Kit.exs",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Clap 1 - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Clap 2 - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/FX - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Hi-Hat 1 - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Hi-Hat 2 - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Hi-Hat 3 - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Hi-Hat 4 - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Kick 1 - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Kick 2 - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Perc - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Perc FX - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Rim - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Snare 1 - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Snare 2 - Ancient Space.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Tambourine 1 - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Tambourine 2 - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Tambourine 3 - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Ancient Space Kit/Woodblock - Ancient Space.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Chimes - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Clap 1 - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Clap 2 - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Cymbal - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Flexatone - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Hi-Hat 1 - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Hi-Hat 2 - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Hi-Hat Open - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Kick 1 - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Kick 2 - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Kick 3 - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Rim - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Shaker - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Snap - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Snare - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Snare Roll - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Tambourine - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Dark Mystic Kit/Tom High - Dark Mystic.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Clap 1 - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Clap 2 - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Clave - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Cowbell 1 - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Cowbell 2 - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Hi-Hat 1 - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Hi-Hat 2 - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Hi-Hat Open - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Kick 1 - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Kick 2 - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Perc - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Perc FX - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Ride - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Rim - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Shaker - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Snare 1 - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Snare 2 - Shell Game.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Shell Game Kit/Tambourine - Shell Game.aif",
  ]
end
