cask "ml-apc0004-soulection" do
  version "ae62970f08ae3543775a61a3e023135c-20"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0004_soulection/ml_apc0004_soulection.aar"
  name "Soulection"
  desc "ProducerPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0004_soulection/ml_apc0004_soulection.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_apc0004_soulection.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/Soulection",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_apc0004_soulection.plist",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/01 Rooms/1.8s_Large & Brite.SDIR",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Solid Soul Electric Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Solid Soul Electric Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Solid Soul Electric Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Bass/Solid Soul Electric Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/ClapAmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/CymbalAmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/HiHat1AmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/HiHat2AmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/HiHatOpenAmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/Kick1AmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/Kick2AmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/Kick3AmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/Kick4AmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/Kick5AmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/Perc1AmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/Perc2AmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/Perc3AmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/RimAmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/Snare1AmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/Snare2AmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/Snare3AmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Amped Up.patch/TomLowAmpedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/FXBigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/HiHat1BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/HiHat2BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/HiHat3BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/Kick1BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/Kick2BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/Kick3BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/Kick4BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/Kick5BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/Perc1BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/Perc2BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/RimBigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/Snare1BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/Snare2BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/Snare3BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/Snare4BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bump.patch/Snare5BigBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/ClapCreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/CongaCreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/CongaSlapCreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/CrashCreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/HiHat1CreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/HiHat2CreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/HiHatOpenCreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/Kick1CreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/Kick2CreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/RideCreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/RimCreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/Shaker1CreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/Shaker2CreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/Snare1CreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/Snare2CreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/TomHighCreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/TomLowCreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Cream Soda.patch/TomMidCreamSoda.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/Clap1SoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/Clap2SoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/Clap3SoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/HiHat1SoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/HiHat2SoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/HiHatOpen1SoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/HiHatOpen2SoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/HiHatOpen3SoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/Kick1SoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/Kick2SoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/Kick3SoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/RimSoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/Snare1SoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/Snare2SoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/Snare3SoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Soul Fire.patch/TomSoulFire.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 5 - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 5 - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 5 - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 5 - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 5 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 5 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 5 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 5 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 5 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 5 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 5 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 5 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 3 - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 3 - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 3 - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 3 - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 3 - Soul Fire.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 3 - Soul Fire.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 3 - Soul Fire.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 3 - Soul Fire.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Cream Soda.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Cream Soda.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga Slap - Cream Soda.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga Slap - Cream Soda.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga Slap - Cream Soda.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Conga Slap - Cream Soda.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 3 - Amped Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 3 - Amped Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 3 - Amped Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 3 - Amped Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX - Big Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX - Big Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX - Big Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX - Big Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Shimmering Electric Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Shimmering Electric Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Shimmering Electric Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Electric Piano/Processed/Shimmering Electric Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/90s Solid Synth Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/90s Solid Synth Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/90s Solid Synth Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/90s Solid Synth Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/90s Stereo Synth Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/90s Stereo Synth Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/90s Stereo Synth Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/90s Stereo Synth Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Breathless Synth Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Breathless Synth Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Breathless Synth Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Breathless Synth Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Growling Brass Synth Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Growling Brass Synth Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Growling Brass Synth Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Growling Brass Synth Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Old School Funk Synth Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Old School Funk Synth Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Old School Funk Synth Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Old School Funk Synth Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Azure Crystal Synth Bells.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Azure Crystal Synth Bells.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Azure Crystal Synth Bells.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Azure Crystal Synth Bells.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Retro Vibes Synth Bells.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Retro Vibes Synth Bells.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Retro Vibes Synth Bells.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Retro Vibes Synth Bells.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Lime Drops Synth Pluck.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Lime Drops Synth Pluck.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Lime Drops Synth Pluck.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Lime Drops Synth Pluck.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mythic Sky Synth Lead.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mythic Sky Synth Lead.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mythic Sky Synth Lead.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mythic Sky Synth Lead.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Scarlet Synth Chimes.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Scarlet Synth Chimes.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Scarlet Synth Chimes.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Scarlet Synth Chimes.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Cutting Squares Synth Lead.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Cutting Squares Synth Lead.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Cutting Squares Synth Lead.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Cutting Squares Synth Lead.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Sweet Cream Synth Lead.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Sweet Cream Synth Lead.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Sweet Cream Synth Lead.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Sweet Cream Synth Lead.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crimson Horizon Synth Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crimson Horizon Synth Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crimson Horizon Synth Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Crimson Horizon Synth Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Luscious Swirls Synth Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Luscious Swirls Synth Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Luscious Swirls Synth Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Luscious Swirls Synth Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Velvetine Synth Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Velvetine Synth Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Velvetine Synth Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Velvetine Synth Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Wobbly Synth Pad.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Wobbly Synth Pad.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Wobbly Synth Pad.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Wobbly Synth Pad.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Eastern Synth Guitar.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Eastern Synth Guitar.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Eastern Synth Guitar.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Eastern Synth Guitar.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Bass/Solid Soul Electric Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Amped Up Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Big Bump Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Cream Soda Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Soul Fire Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Electric Piano/Other/Shimmering Electric Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Bass/Breathless Synth Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Bells/Azure Crystal Synth Bells.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Lime Drops Synth Pluck.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Mythic Sky Synth Lead.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Scarlet Synth Chimes.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Pad/Luscious Swirls Synth Pad.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Pad/Velvetine Synth Pad.exs",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Soulection.logicx/Alternatives/000/DisplayState.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Soulection.logicx/Alternatives/000/DisplayStateArchive",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Soulection.logicx/Alternatives/000/MetaData.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Soulection.logicx/Alternatives/000/ProjectData",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Soulection.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Soulection.logicx/Contents/Resources/template.tif",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Soulection.logicx/Contents/Resources/template_ios.png",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Soulection.logicx/Resources/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Soulection.logicx/Resources/ProjectInformation.plist",
    "~/Music/Logic Pro Library.bundle/Samples/Bass/Solid Soul Electric Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Amped Up Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bump Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Cream Soda Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Soul Fire Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Electric Piano/Processed/Shimmering Electric Piano.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bass/Breathless Synth Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bells",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Lime Drops Synth Pluck.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Mythic Sky Synth Lead.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Scarlet Synth Chimes.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Pad/Luscious Swirls Synth Pad.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Pad/Velvetine Synth Pad.aif",
  ]
end
