cask "ml-apc0002-oakfelder" do
  version "ecc4950f0cb774eb1dcd960a434043f3-48"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0002_oakfelder/ml_apc0002_oakfelder.aar"
  name "OakFelder"
  desc "ProducerPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0002_oakfelder/ml_apc0002_oakfelder.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_apc0002_oakfelder.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/Oak Felder",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_apc0002_oakfelder.plist",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/OakVerb.SDIR",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/Clap1AcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/Clap2AcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/HiHatAcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/HiHatOpen1AcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/HiHatOpen2AcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/HiHatOpen3AcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/Kick1AcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/Kick2AcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/Kick3AcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/PercAcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/ShakerAcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/SnapAcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/Snare1AcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/Snare2AcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/Snare3AcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Acoustic Bump.patch/TomAcousticBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Clap1HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Clap2HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Cymbal1HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Cymbal2HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/HiHat1HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/HiHat2HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/HiHatOpenHitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Kick1HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Kick2HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Kick3HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Perc1HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Perc2HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Snare1HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Snare2HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Snare3HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hit Synth.patch/Snare4HitSynth.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/ClapMixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/FXMixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/HiHat1MixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/HiHat2MixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/HiHatOpen1MixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/HiHatOpen2MixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/Kick1MixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/Kick2MixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/Kick3MixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/Perc1MixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/Perc2MixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/Perc3MixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/SnapMixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/Snare1MixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/Snare2MixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/Snare3MixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mixed Up.patch/TomMixedUp.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/BongoTwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/Clap1TwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/Clap2TwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/CymbalTwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/FXTwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/HiHat1TwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/HiHat2TwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/HiHatOpenTwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/Kick1TwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/Kick2TwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/Kick3TwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/Perc1TwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/Perc2TwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/Snare1TwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/Snare2TwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/Snare3TwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/SwooshTwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Two Ton Pop.patch/TambourineTwoTonPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 3 - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 3 - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 3 - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 3 - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal 1 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal 1 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal 1 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal 1 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal 2 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal 2 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal 2 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal 2 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Acoustic Bump.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bongo - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Acoustic Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Acoustic Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Acoustic Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Acoustic Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/FX - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 1 - Hit Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 1 - Hit Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 1 - Hit Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 1 - Hit Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 1 - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 1 - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 1 - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 1 - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 2 - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 2 - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 2 - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 2 - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 3 - Mixed Up.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 3 - Mixed Up.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 3 - Mixed Up.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 3 - Mixed Up.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Swoosh - Two Ton Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Swoosh - Two Ton Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Swoosh - Two Ton Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Swoosh - Two Ton Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Dark Lo-Fi Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Dark Lo-Fi Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Dark Lo-Fi Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Dark Lo-Fi Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Oak Piano Dream Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Oak Piano Dream Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Oak Piano Dream Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Oak Piano Dream Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Psychic Energy Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Psychic Energy Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Psychic Energy Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Psychic Energy Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Small Time Piano.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Small Time Piano.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Small Time Piano.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Keyboard/Acoustic Piano/Processed/Small Time Piano.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Cute Crush Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Cute Crush Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Cute Crush Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bells/Cute Crush Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Dark Heart Brass Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Dark Heart Brass Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Dark Heart Brass Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Brass/Dark Heart Brass Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fuzzy Soul Organ.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fuzzy Soul Organ.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fuzzy Soul Organ.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Fuzzy Soul Organ.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Grunge Dream Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Grunge Dream Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Grunge Dream Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Grunge Dream Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Harmonic Scream Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Harmonic Scream Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Harmonic Scream Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Harmonic Scream Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Hazy Plucked Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Hazy Plucked Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Hazy Plucked Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Hazy Plucked Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Heart Flutters Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Heart Flutters Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Heart Flutters Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Heart Flutters Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Plucked Sweet Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Plucked Sweet Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Plucked Sweet Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Plucked Sweet Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Overdrive Lead Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Overdrive Lead Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Overdrive Lead Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Overdrive Lead Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Aquatic Voices.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Aquatic Voices.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Aquatic Voices.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Aquatic Voices.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Distant Drift Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Distant Drift Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Distant Drift Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Distant Drift Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Cloudy Plucked Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Cloudy Plucked Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Cloudy Plucked Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Cloudy Plucked Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Noisy Plucked Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Noisy Plucked Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Noisy Plucked Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Plucked/Noisy Plucked Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Fuzzy Soul Organ.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Grunge Dream Synth.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Harmonic Scream Synth.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Hazy Plucked Synth.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Keyboard/Heart Flutters Synth.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Lead/Overdrive Lead Synth.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Aquatic Voices.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Pad/Distant Drift Synth.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Acoustic Bump Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Hit Synth Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Mixed Up Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Two Ton Pop Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Classical Grand.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Keyboard/Acoustic Piano/Grand Piano.exs",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Oak Felder.logicx/Alternatives/000/DisplayState.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Oak Felder.logicx/Alternatives/000/DisplayStateArchive",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Oak Felder.logicx/Alternatives/000/MetaData.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Oak Felder.logicx/Alternatives/000/ProjectData",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Oak Felder.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Oak Felder.logicx/Contents/Resources/template.tif",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Oak Felder.logicx/Contents/Resources/template_ios.png",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Oak Felder.logicx/Resources/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Oak Felder.logicx/Resources/ProjectInformation.plist",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws A1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws A2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws A3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws A4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws A5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws C4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws C5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws C6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws Eb2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws Eb3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws Eb4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws Eb5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws Gb1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws Gb2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws Gb3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws Gb4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws/Mini 3 VCO Saws Gb5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares A1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares A2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares A3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares A4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares A5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares C4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares C5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares C6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Eb2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Eb3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Eb4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Eb5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Gb1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Gb2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Gb3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Gb4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Gb5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Natural/Dripping.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Ah Lofi/AH Lofi A2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Ah Lofi/AH Lofi B3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Ah Lofi/AH Lofi C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Ah Lofi/AH Lofi D2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Ah Lofi/AH Lofi D4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Ah Lofi/AH Lofi E3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Ah Lofi/AH Lofi F2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Solo Vocals/Sustain/Ah Lofi/AH Lofi G3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal FX And Noises/Eh Ee Ah Oh Oo/EH Ee Ah Oh Oo 1 A2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal FX And Noises/Eh Ee Ah Oh Oo/EH Ee Ah Oh Oo 1 C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal FX And Noises/Eh Ee Ah Oh Oo/EH Ee Ah Oh Oo 1 D2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal FX And Noises/Eh Ee Ah Oh Oo/EH Ee Ah Oh Oo 1 E3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal FX And Noises/Eh Ee Ah Oh Oo/EH Ee Ah Oh Oo 1 F2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal FX And Noises/Eh Ee Ah Oh Oo/EH Ee Ah Oh Oo 1 G3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Clap 1 - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Clap 2 - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Hi-Hat - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Hi-Hat Open 1 - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Hi-Hat Open 2 - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Hi-Hat Open 3 - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Kick 1 - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Kick 2 - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Kick 3 - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Perc - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Shaker - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Snap - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Snare 1 - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Snare 2 - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Snare 3 - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Acoustic Bump Kit/Tom - Acoustic Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Clap 1 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Clap 2 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Cymbal 1 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Cymbal 2 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Hi-Hat 1 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Hi-Hat 2 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Hi-Hat Open - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Kick 1 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Kick 2 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Kick 3 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Perc 1 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Perc 2 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Snare 1 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Snare 2 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Snare 3 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hit Synth Kit/Snare 4 - Hit Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Clap - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/FX - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Hi-Hat - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Hi-Hat Open 1 - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Hi-Hat Open 2 - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Kick 1 - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Kick 2 - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Kick 3 - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Perc 1 - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Perc 2 - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Perc 3 - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Snap - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Snare 1 - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Snare 2 - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Snare 3 - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mixed Up Kit/Tom - Mixed Up.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Bongo - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Clap 1 - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Clap 2 - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Cymbal - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/FX - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Hi-Hat 1 - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Hi-Hat 2 - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Hi-Hat Open - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Kick 1 - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Kick 2 - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Perc 1 - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Perc 2 - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Snare 1 - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Snare 2 - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Snare 3 - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Swoosh - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Two Ton Pop Kit/Tambourine - Two Ton Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Keyboard/Acoustic Piano/Classical Grand_consolidated_h.caf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/024_C0KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/024_C0KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/024_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/024_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/031_G0KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/031_G0KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/031_G0KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/031_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/031_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/031_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/035_B0KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/035_B0KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/035_B0KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/035_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/035_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/038_D1KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/038_D1KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/038_D1KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/038_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/038_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/039_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/042_F#1KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/042_F#1KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/042_F#1KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/042_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/042_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/042_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/045_A1KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/045_A1KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/045_A1KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/045_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/045_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/045_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/050_D2KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/050_D2KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/050_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/050_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/050_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/051_D#2KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/054_F#2KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/054_F#2KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/054_F#2KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/054_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/054_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/054_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/058_A#2KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/058_A#2KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/058_A#2KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/058_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/058_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/058_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/060_C3KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/060_C3KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/060_C3KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/060_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/060_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/060_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/062_D3KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/062_D3KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/062_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/062_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/063_D#3KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/063_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/064_E3KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/064_E3KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/064_E3KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/064_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/064_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/064_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/065_F3KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/065_F3KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/065_F3KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/065_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/065_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/065_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/068_G#3KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/068_G#3KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/068_G#3KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/068_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/068_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/068_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/070_A#3KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/070_A#3KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/070_A#3KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/070_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/070_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/070_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/072_C4KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/072_C4KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/072_C4KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/072_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/072_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/072_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/077_F4KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/077_F4KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/077_F4KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/077_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/077_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/077_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/081_A4KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/081_A4KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/081_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/081_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/081_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/082_A#4KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/086_D5KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/086_D5KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/086_D5KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/086_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/086_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/086_ped_s.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/090_F#5KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/090_F#5KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/090_F#5KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/090_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/090_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/095_B5KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/095_B5KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/095_B5KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/095_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/095_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/099_D#6KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/099_D#6KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/099_D#6KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/099_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/099_ped_mf.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/101_F6KM56_H.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/101_F6KM56_M.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/101_F6KM56_S.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/101_ped_h.wav",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Grand Piano/101_ped_mf.wav",
  ]
end
