cask "ml-apc0010-tosinabasi" do
  version "ca77dfea95ff64ea76db71639ae91a1a"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0010_tosinabasi/ml_apc0010_tosinabasi.aar"
  name "TosinAbasi"
  desc "ProducerPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0010_tosinabasi/ml_apc0010_tosinabasi.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_apc0010_tosinabasi.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Ascension Bass Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Ascension Lead Harmony.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Ascension Lead Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Ascension Rhythm 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Ascension Rhythm 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Axial Spindles Arp 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Axial Spindles Arp 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Axial Spindles Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Axial Spindles Rhythm.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Between Worlds Arp 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Between Worlds Arp 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Bittersweet Memory Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Blazing Suns Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Blazing Suns Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Blue Metal Bass Riff 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Blue Metal Bass Riff 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Blue Metal Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Blue Metal Rhythm.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Broken Bonds Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Broken Bonds Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Climbing Hills Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Climbing Mountains Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Coarse Sands Bass Riff 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Coarse Sands Bass Riff 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Coarse Sands Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Coarse Sands Rhythm.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Coarse Sands Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Colorful Dreams Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Cosmic Dirt Bass Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Creeping In Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Creeping Out Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Crystalline Circuitry Arp High 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Crystalline Circuitry Arp High 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Crystalline Circuitry Arp Low.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Crystalline Circuitry Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Cyclic Energy Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Dire Times Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Dire Times Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Dire Times Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Eleventh Hour Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Engine Cycle Bass Rhythm 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Engine Cycle Bass Rhythm 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Engine Cycle Bass Rhythm 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Engine Cycle Bass Rhythm 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Engine Cycle Bass Rhythm 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Engine Cycle Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Engine Cycle Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Engine Cycle Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Engine Cycle Rhythm 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Engine Cycle Rhythm 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Fallen Fragments Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Fallen Fragments Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Fallen Fragments Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Feral Scream Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Flicker of Grey Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Ghost Light Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Grounding Pulse Bass Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Grounding Pulse Rhythm.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Hallowed Dissonance Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Head Trip Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Head Trip Bass Melody 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Head Trip Bass Melody 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Head Trip Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Head Trip Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Heavy Lifting Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Heavy Lifting Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Heavy Lifting Chords 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Heavy Lifting Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Heavy Lifting Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Heavy Lifting Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Infinite Precipice Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Infinite Precipice Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Inverse Square Bass Rhythm.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Inverse Square Lead Harmony.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Inverse Square Lead Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Inverse Square Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Inverse Square Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Inverse Square Pad 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Inverted Eclipse Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Languid Gaze Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Light Grains Arp High.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Light Grains Arp Low.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Liquid Stars Lead Harmony.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Liquid Stars Lead Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Liquid Stars Melody 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Liquid Stars Melody 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Lunar Days Low Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Lunar Days Upper Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Lunar Nights Melody 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Lunar Nights Melody 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Lunar Nights Melody 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Machine Grit Bass Rhythm 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Machine Grit Bass Rhythm 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Machine Grit Bass Rhythm 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Manic Mind Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Melting Mirage Arp 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Melting Mirage Arp 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Melting Mirage Bass Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Memory Drift Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Mind Waves Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Mind Waves Melody 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Mind Waves Melody 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Mind Waves Melody 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Mind Waves Melody 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Mind Waves Rhythm.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Moon Echoes Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Moving Mountains Ascending Riff 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Moving Mountains Ascending Riff 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Moving Mountains Ascending Riff 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Moving Mountains Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Moving Mountains Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Moving Mountains Bass Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Moving Mountains Chords High.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Moving Mountains Chords Low.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Moving Mountains Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Moving Mountains Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Moving Shadows Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Nail Biter Bass Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Nail Biter Descending Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Nail Biter Descending Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Nail Biter Rhythm.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Nail Biter Rhythmic Drone.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Nail Biter Tapping Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Nail Biter Tapping Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Neon Labyrinth Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Neon Labyrinth Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Neon Labyrinth Tapping Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Neural Drift Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/New Dawn Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/New Dawn Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/New Dawn Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/No Way Out Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Other Dimensions Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Other Dimensions Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Partial Eclipse Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Pensive Echoes Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Pensive Echoes Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Pensive Echoes Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Pensive Echoes Pad 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Pensive Echoes Rhythm.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Razor Edge Bass Riff 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Razor Edge Bass Riff 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Razor Edge Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Razor Edge Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Razor Edge Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Resonant Void Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Resonant Void Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Silver Spoon Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Snake Bite Muted Rhythm.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Snake Bite Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Snake Bite Rhythm 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Snake Bite Rhythm 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Snake Bite Riff 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Snake Bite Riff 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Stoic Staircase Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Stretching Thin Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/String Spiders Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Suns Beneath Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Suns Beneath Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Suns Beneath Muted Rhythm.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Suns Beneath Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Suns Beneath Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Tapestry of Blue Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Three by Four Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Time Spiral Ambient Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Time Spiral Ambient Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Time Spiral Ambient Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Time Spiral Bass Riff 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Time Spiral Bass Riff 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Time Spiral Distortion Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Time Spiral Rhythm.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Top of Mind Bass Melody 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Top of Mind Bass Melody 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Top of Mind Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Top of Mind Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Waiting For Dawn Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Waiting For Dawn Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/Tosin Abasi/Winter Mist Chords.caf",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_apc0010_tosinabasi.plist",
  ]
end
