cask "ml-apc0008-trakgirl" do
  version "15ffe5f383cc25c2681899e9a67f3a6e-11"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0008_trakgirl/ml_apc0008_trakgirl.aar"
  name "TRAKGIRL"
  desc "ProducerPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0008_trakgirl/ml_apc0008_trakgirl.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_apc0008_trakgirl.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Always Tomorrow Electric Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Arrive Gently Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Arrive Gently Reverse Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Arrive Gently Synth Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Arrive Gently Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Arrive Gently Synth Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Charmed Life Acoustic Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Charmed Life Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Charmed Life Guitar Room.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Charmed Life Kick 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Charmed Life Kick 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Charmed Life Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Charmed Life Shakers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Charmed Life Snaps.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Charmed Life Synth Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Chiptune Tip Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Chiptune Tip Synth Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Closer Still Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Closer Still Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deep Down Vibe Bongo.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deep Down Vibe Clave.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deep Down Vibe Electric Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deep Down Vibe Kick.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deep Down Vibe Percussion 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deep Down Vibe Percussion 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deep Down Vibe Ride Roll.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deep Down Vibe Shakers.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deep Funk Bass Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deep Funk Guitar Chords 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deep Funk Guitar Chords 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deep Knowledge Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deeper Love Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deeper Love Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Deeper Love Piano 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Disco Funk Guitar Riff 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Disco Funk Guitar Riff 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Down Low Funk Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Dreamtime Flow Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Dreamtime Flow Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Dreamtime Flow Piano 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Dreamtime Flow Piano 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Dreamtime Flow Piano 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Dreamtime Flow Piano 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Dreamtime Flow Synth Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Dreamtime Flow Synth Texture.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Drifting Pieces Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Drifting Pieces Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Drifting Pieces Piano 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Drifting Pieces Piano 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Driving Funk Guitar Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Faded Memories Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Faded Memories Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Family Feels Electric Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Far From Over Electric Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Flow Feels Electric Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Flow Feels Electric Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Flow Feels Electric Guitar 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Flow Feels Electric Guitar 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Flow Feels Reverse Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Flow Feels Synth Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Get Closer Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Get Closer Kicks.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Get Closer Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Get Closer Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Get Closer Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Get Closer Piano 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Get Closer Piano 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Get Closer Synth Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Get Closer Synth Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Get Closer Synth Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Graceful Moment Acoustic Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Graceful Moment Bass Drum.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Graceful Moment Echo Snare.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Graceful Moment Hi-Hats.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Graceful Moment Kick.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Graceful Moment Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Graceful Moment Reverse Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Graceful Moment Reverse Snare.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Heart of Gold Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Heart of Gold Synth Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Heart of Gold Synth Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Heart of Gold Synth Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Hit Me Up Bass Drum 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Hit Me Up Bass Drum 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Hit Me Up Bass Drum 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Hit Me Up Break.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Hit Me Up Hi-Hats 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Hit Me Up Hi-Hats 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Hit Me Up Piano Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Hit Me Up Snare 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Hit Me Up Snare 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Hit Me Up Synth Beeps.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Hit Me Up Synth Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Hit Me Up Synth Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Hopeful Beginnings Electric Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Hopeful Beginnings Electric Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Humble Beginnings Electric Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Jupiter Calling Synth Organ 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Jupiter Calling Synth Organ 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Jupiter Calling Synth Organ 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Laidback Flow Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Leap of Faith Electric Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Learn The Way Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Learn The Way Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Learn The Way Piano 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Lets Talk Electric Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Lets Talk Electric Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Like It Loose Guitar Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Like It Loose Guitar Picks.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Like It Loose Rhythm Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Liquid Soul Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Liquid Soul Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Liquid Soul Piano 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Lo-Fi Vibes Electric Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Lo-Fi Vibes Electric Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Lo-Fi Vibes Electric Piano 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Lo-Fi Vibes Electric Piano 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Lo-Fi Vibes Electric Piano 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Lo-Fi Vibes Electric Piano 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Lo-Fi Vibes Electric Piano 07.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Low Slung Funk Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Luscious Tones Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Luscious Tones Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Luscious Tones Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Miles From Home Electric Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Miles From Home Electric Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/New York Night Electric Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/New York Night Electric Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/New York Night Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Oh Yeah Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Opening Up Guitar Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Rock Steady Reggae Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Sense It Shaker Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Shades of Night Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Shades of Night Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Shades of Night Beat 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Shades of Night Beat 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Shifting Lights Electric Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Shifting Lights Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Shifting Lights Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Slink and Sly Funk Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Soulful Jam Guitar Riff 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Soulful Jam Guitar Riff 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Soulful Jam Guitar Riff 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Speaking in Dreams Kick.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Speaking in Dreams Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Speaking in Dreams Reverse Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Speaking in Dreams Reverse Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Speaking in Dreams Reverse Piano 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Speaking in Dreams Synth Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Speaking in Dreams Vocal Chop.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Stone Cold Rolls Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Streets of Soul Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Summer Longing Acoustic Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Summer Longing Acoustic Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Summer Longing Guitar Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Summer Longing Guitar Picking.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Surreal Rambling Vocal Chop.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Sweet Blues Electric Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Sweet Soulful Guitar Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Sweet Southern Guitar Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Sweet Summer Music Box.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Sweet Summer Synth Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Sweet Summer Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Sweet Summer Synth Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Thankful Moment Guitar Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Vintage Ballad Electric Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Waking Dream Watery Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Warm Waves Synth Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Warm Waves Synth Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Warm Waves Synth Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Warm Waves Synth Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Warm Waves Synth Textures 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Warm Waves Synth Textures 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Warm Waves Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Washed Away Piano 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Washed Away Piano 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Washed Away Synth Pad 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Washed Away Synth Pad 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Washed Away Synth Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Weathered Soul Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/TRAKGIRL/Wicked Funk Guitar Chords.caf",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_apc0008_trakgirl.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/CymbalGrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/HiHat1GrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/HiHat2GrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/HiHat3GrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/HiHat4GrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/Kick1GrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/Kick2GrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/Kick3GrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/Kick4GrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/PercGrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/RimGrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/Shaker1GrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/Shaker2GrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/SnapGrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/Snare1GrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/Snare2GrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Grimey Funk.patch/Snare3GrimeyFunk.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/ClapHardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/HiHat1HardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/HiHat2HardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/HiHat3HardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/HiHat4HardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/Kick1HardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/Kick2HardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/Kick3HardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/Kick4HardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/Perc1HardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/Perc2HardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/SnapHardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/Snare1HardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/Snare2HardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/Snare3HardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/Snare4HardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/TomHighHardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Hard Knocking.patch/TomLowHardKnocking.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/Clap1LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/Clap2LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/HiHat1LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/HiHat2LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/HiHatOpen1LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/HiHatOpen2LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/Kick1LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/Kick2LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/Kick3LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/Kick4LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/Perc1LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/Perc2LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/Perc3LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/PercFXLoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/Rim1LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/Rim2LoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lo-Fi Feels.patch/SnareLoFiFeels.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/Chimes1MysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/Chimes2MysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/Chimes3MysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/ClapMysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/CrashFX1MysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/CrashFX2MysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/HiHat1MysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/HiHat2MysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/HiHatOpenMysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/Kick1MysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/Kick2MysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/Snare1MysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/Snare2MysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/Snare3MysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/Snare4MysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Mystic Groove.patch/SwellMysticGroove.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 1 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim 2 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 4 - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 3 - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 4 - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 4 - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 4 - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 4 - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 4 - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 4 - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 4 - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 4 - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 1 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open 2 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash FX 1 - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash FX 1 - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash FX 1 - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash FX 1 - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash FX 2 - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash FX 2 - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash FX 2 - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash FX 2 - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Cymbal - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Grimey Funk.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 1 - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Grimey Funk.patch/com.apple.musicapps.intermediate.cache.zxml",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker 2 - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes 1 - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes 1 - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes 1 - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes 1 - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes 2 - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes 2 - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes 2 - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes 2 - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes 3 - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes 3 - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes 3 - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Chimes 3 - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Grimey Funk.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Grimey Funk.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Grimey Funk.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Grimey Funk.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Hard Knocking.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Hard Knocking.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Hard Knocking.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Hard Knocking.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 3 - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 3 - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 3 - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 3 - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX - Lo-Fi Feels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX - Lo-Fi Feels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX - Lo-Fi Feels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX - Lo-Fi Feels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Swell - Mystic Groove.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Swell - Mystic Groove.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Swell - Mystic Groove.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Swell - Mystic Groove.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/80s Pluck Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/80s Pluck Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/80s Pluck Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/80s Pluck Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Bass Twister.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Bass Twister.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Bass Twister.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Bass Twister.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Sweep Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Sweep Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Sweep Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Analog Sweep Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Moves Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Moves Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Moves Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Moves Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Texture Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Texture Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Texture Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Texture Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Low Growl Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Low Growl Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Low Growl Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Low Growl Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Rough Waves Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Rough Waves Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Rough Waves Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Rough Waves Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Silky Smooth Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Silky Smooth Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Silky Smooth Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Silky Smooth Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Sub Tone Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Sub Tone Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Sub Tone Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Sub Tone Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Modern Mystic Bowl.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Modern Mystic Bowl.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Modern Mystic Bowl.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Modern Mystic Bowl.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Sweet Dream Flute.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Sweet Dream Flute.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Sweet Dream Flute.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Sweet Dream Flute.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Supreme Lead Synth.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Supreme Lead Synth.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Supreme Lead Synth.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Supreme Lead Synth.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Heavenly Voices Choir.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Heavenly Voices Choir.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Heavenly Voices Choir.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Heavenly Voices Choir.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Shimmering Voice Texture.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Shimmering Voice Texture.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Shimmering Voice Texture.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Sound Effects/Shimmering Voice Texture.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Ancient Singing Bowl.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Ancient Singing Bowl.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Ancient Singing Bowl.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Ancient Singing Bowl.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Metallic Memories Bowl.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Metallic Memories Bowl.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Metallic Memories Bowl.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Soundscape/Metallic Memories Bowl.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Bass/Silky Smooth Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Bass/Sub Tone Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Grimey Funk Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Hard Knocking Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Mystic Groove Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Bass/80s Pluck Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Bass/Analog Sweep Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Bass/Deep Moves Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Bass/Deep Texture Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Bass/Low Growl Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Bass/Rough Waves Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Modern Mystic Bowl.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Sweet Dream Flute.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Lead/Supreme Lead Synth.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Sound Effects/Heavenly Voices Choir.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Sound Effects/Shimmering Voice Texture.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Soundscape/Ancient Singing Bowl.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Soundscape/Metallic Memories Bowl.exs",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/TRAKGIRL.logicx/Alternatives/000/DisplayState.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/TRAKGIRL.logicx/Alternatives/000/DisplayStateArchive",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/TRAKGIRL.logicx/Alternatives/000/MetaData.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/TRAKGIRL.logicx/Alternatives/000/ProjectData",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/TRAKGIRL.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/TRAKGIRL.logicx/Contents/Resources/template.tif",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/TRAKGIRL.logicx/Contents/Resources/template_ios.png",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/TRAKGIRL.logicx/Resources/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/TRAKGIRL.logicx/Resources/ProjectInformation.plist",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Cymbal - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Hi-Hat 1 - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Hi-Hat 2 - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Hi-Hat 3 - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Hi-Hat 4 - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Kick 1 - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Kick 2 - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Kick 3 - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Kick 4 - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Perc - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Rim - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Shaker 1 - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Shaker 2 - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Snap - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Snare 1 - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Snare 2 - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Grimey Funk Kit/Snare 3 - Grimey Funk.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Clap - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Hi-Hat 1 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Hi-Hat 2 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Hi-Hat 3 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Hi-Hat 4 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Kick 1 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Kick 2 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Kick 3 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Kick 4 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Perc 1 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Perc 2 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Snap - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Snare 1 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Snare 2 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Snare 3 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Snare 4 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Tom 1 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Hard Knocking Kit/Tom 2 - Hard Knocking.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Clap 1 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Clap 2 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Hi-Hat Closed 1 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Hi-Hat Closed 2 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Hi-Hat Open 1 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Hi-Hat Open 2 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Kick 1 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Kick 2 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Kick 3 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Kick 4 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Perc 1 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Perc 2 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Perc 3 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Perc FX - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Rim 1 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Rim 2 - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lo-Fi Feels Kit/Snare - Lo-Fi Feels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Chimes 1 - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Chimes 2 - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Chimes 3 - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Clap - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Crash FX 1 - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Crash FX 2 - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Hi-Hat 1 - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Hi-Hat 2 - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Hi-Hat Open - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Kick 1 - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Kick 2 - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Snare 1 - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Snare 2 - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Snare 3 - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Snare 4 - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Mystic Groove Kit/Swell - Mystic Groove.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bass/80s Pluck Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bass/Analog Sweep Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bass/Deep Moves Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bass/Deep Texture Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bass/Low Growl Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bass/Rough Waves Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bass/Silky Smooth Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bass/Sub Tone Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Modern Mystic Bowl.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Sweet Dream Flute.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Lead/Supreme Lead Synth.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Sound Effect/Heavenly Voices Choir.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Sound Effect/Shimmering Voice Texture.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Soundscape/Ancient Singing Bowl.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Soundscape/Metallic Memories Bowl.aif",
  ]
end
