cask "ml-apc0001-boysnoize" do
  version "d323096ec5ed2f46bb06fca3462f45b2-8"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0001_boysnoize/ml_apc0001_boysnoize.aar"
  name "BoysNoize"
  desc "ProducerPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0001_boysnoize/ml_apc0001_boysnoize.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_apc0001_boysnoize.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/Boys Noize",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_apc0001_boysnoize.plist",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/03 Plate Reverbs/0.7s_Drum Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/BassHitAnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/ClapAnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/CrashFXAnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/HiHat1AnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/HiHat2AnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/Kick1AnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/Kick2AnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/NoiseAnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/Perc1AnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/Perc2AnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/RimToneAnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/Snare1AnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/Snare2AnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/TomHighAnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/TomLowAnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/TomMidAnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Analog Drive.patch/ZapAnalogDrive.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/ClapBigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/HiHat1BigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/HiHat2BigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/HiHatOpenBigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/KickBigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/KickSubBigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/NoiseBigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/NoiseHighBigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/PercHighBigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/PercMidBigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/RimBigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/Snare1BigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/Snare2BigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/Snare3BigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/TomHighBigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Big Bang.patch/TomMidBigBang.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/Bell1ControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/Bell2ControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/Clap1ControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/Clap2ControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/HiHat1ControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/HiHat2ControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/HiHatOpenControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/Kick1ControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/Kick2ControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/Kick3ControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/Kick4ControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/RideControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/RimControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/Snare1ControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/Snare2ControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/TomHighControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/TomLowControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Control Voltage.patch/TomMidControlVoltage.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/ClapNaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/ClapReverseNaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/CrashNaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/CrashReverseNaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/HiHat1NaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/HiHat2NaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/HiHatOpenNaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/KickNaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/KickReverseNaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/RideNaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/RimNaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/Snare1NaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/Snare2NaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/TomHighNaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/TomLowNaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Natural Structures.patch/TomMidNaturalStructures.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 4 - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick Reverse - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick Reverse - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick Reverse - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick Reverse - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick Sub - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick Sub - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick Sub - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick Sub - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim Tone - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim Tone - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim Tone - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim Tone - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 3 - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash Reverse - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash Reverse - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash Reverse - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash Reverse - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/CrashFX - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/CrashFX - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/CrashFX - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/CrashFX - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap Reverse - Natural Structures.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap Reverse - Natural Structures.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap Reverse - Natural Structures.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap Reverse - Natural Structures.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bell 1 - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bell 1 - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bell 1 - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bell 1 - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bell 2 - Control Voltage.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bell 2 - Control Voltage.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bell 2 - Control Voltage.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Bell 2 - Control Voltage.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc High - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc High - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc High - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc High - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc Mid - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc Mid - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc Mid - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc Mid - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Bass Hit - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Bass Hit - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Bass Hit - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Bass Hit - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Clap Like Noise.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Clap Like Noise.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Clap Like Noise.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Clap Like Noise.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise High - Big Bang.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise High - Big Bang.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise High - Big Bang.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise High - Big Bang.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 1 - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 1 - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 1 - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 1 - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 2 - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 2 - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 2 - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Perc 2 - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Zap - Analog Drive.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Zap - Analog Drive.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Zap - Analog Drive.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Zap - Analog Drive.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Calculating Machine Arp.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Calculating Machine Arp.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Calculating Machine Arp.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Calculating Machine Arp.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Pitch Black Night Arp.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Pitch Black Night Arp.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Pitch Black Night Arp.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Arpeggiated/Pitch Black Night Arp.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Hollow Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Hollow Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Hollow Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Deep Hollow Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Doom Tune Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Doom Tune Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Doom Tune Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Doom Tune Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Noisy 808 Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Noisy 808 Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Noisy 808 Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Noisy 808 Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Organic Distortion Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Organic Distortion Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Organic Distortion Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Organic Distortion Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Analog Alarm Lead.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Analog Alarm Lead.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Analog Alarm Lead.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Analog Alarm Lead.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Horizon Noise Lead.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Horizon Noise Lead.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Horizon Noise Lead.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Horizon Noise Lead.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Tinfoil Monster Lead.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Tinfoil Monster Lead.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Tinfoil Monster Lead.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Tinfoil Monster Lead.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Massive Drone Wave Lead.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Massive Drone Wave Lead.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Massive Drone Wave Lead.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Massive Drone Wave Lead.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Calculating Machine Arp.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Arpeggiated/Pitch Black Night Arp.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Lead/Horizon Noise Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Lead/Massive Drone Wave Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Analog Drive Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Big Bang Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Control Voltage Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Natural Structures Kit.exs",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Boys Noize.logicx/Alternatives/000/DisplayState.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Boys Noize.logicx/Alternatives/000/DisplayStateArchive",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Boys Noize.logicx/Alternatives/000/MetaData.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Boys Noize.logicx/Alternatives/000/ProjectData",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Boys Noize.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Boys Noize.logicx/Contents/Resources/template.tif",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Boys Noize.logicx/Contents/Resources/template_ios.png",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Boys Noize.logicx/Resources/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/Boys Noize.logicx/Resources/ProjectInformation.plist",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Bass Hit - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Clap - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/CrashFX - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Hi-Hat 1 - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Hi-Hat 2 - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Kick 1 - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Kick 2 - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Noise - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Perc 1 - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Perc 2 - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Rim Tone - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Snare - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Tom High - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Tom Low - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Tom Mid - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Analog Drive Kit/Zap - Analog Drive.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Clap - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Hi-Hat Closed 1 - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Hi-Hat Closed 2 - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Hi-Hat Open - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Kick - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Noise - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Noise High - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Perc High - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Perc Mid - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Rim - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Snare 1 - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Snare 2 - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Snare 3 - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Tom High - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Tom Low - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Big Bang Kit/Tom Mid - Big Bang Kit.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Bell 1 - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Bell 2 - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Clap 1 - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Clap 2 - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Hi-Hat Closed 1 - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Hi-Hat Closed 2 - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Hi-Hat Open - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Kick 1 - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Kick 2 - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Kick 3 - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Kick 4 - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Ride - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Rim - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Snare 1 - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Snare 2 - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Tom High - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Tom Low - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Control Voltage Kit/Tom Mid - Control Voltage.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Clap - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Clap Reverse - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Crash - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Crash Reverse - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Hi-Hat Closed 1 - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Hi-Hat Closed 2 - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Hi-Hat Open - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Kick - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Kick Reverse - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Ride - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Rim - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Snare 1 - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Snare 2 - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Tom High - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Tom Low - Natural Structures.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Natural Structures Kit/Tom Mid - Natural Structures.aif",
  ]
end
