cask "ml-apc0009-pompom" do
  version "f5a6a24e7a3a16cdc2eba7fde67af3c2-12"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0009_pompom/ml_apc0009_pompom.aar"
  name "PomPom"
  desc "ProducerPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_apc0009_pompom/ml_apc0009_pompom.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_apc0009_pompom.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Adept Flourish Trumpet 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Adept Flourish Trumpet 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Adept Flourish Trumpet 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Adept Flourish Trumpet 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Adept Flourish Trumpet 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Airy Vibe Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Ascending Steps Trumpet 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Ascending Steps Trumpet 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Ascending Steps Trumpet 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Ascending Steps Trumpet 04.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Ascending Steps Trumpet 05.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Ascending Steps Trumpet 06.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Basement Party Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Beach Vibe Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Beach Vibe Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Best Of Times Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Bop City Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Bop City Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Bop City Fill.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Bop City Laser FX.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Bop City Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Bouncing Trumpet Stabs.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Chippy LoFi Drums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Click N Pop Fill.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Clicky Euro House Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Cloud Nine Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Cloud Nine Claps.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Cloud Nine Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Cloud Nine Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Cloud Nine Rhythm Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Cloud Nine Rhythm Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Cloud Nine Rhythm Guitar 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Cloud Nine Vox 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Cloud Nine Vox 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Cloud Nine Vox 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Company Of Angels Synth 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Company Of Angels Synth 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Company Of Angels Synth 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Crackling Noise Sweep.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Darkbeat Synth Melody.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Darkbeat Synth Vox Chants.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Digital Love Vox Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Dope Flow 808.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Dope Flow Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Dope Flow Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Dope Flow Hi-Hat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Dope Flow Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Dope Flow Tom Fill.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Dorian Trumpet Riff 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Dorian Trumpet Riff 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Dreaming Time Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Dreaming Time Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Dreaming Time Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Fire Island Groove.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Fire Island Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Fire Island Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Fire Island Organ Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Fire Island Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Fire Island Shaker.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Fire Island Synth.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Flanged Dystopia Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Flanged Dystopia Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Flanged Dystopia Guitar 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Fuzzy Growl Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Fuzzy Math Ukulele.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Gentle Harmony Trumpet 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Gentle Harmony Trumpet 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Gentle Harmony Trumpet 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Granite City Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Granite City Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Granite City Noise Sweep 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Granite City Noise Sweep 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Granite City Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Granite City Synth Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Granite City Synth Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Granite City Synth Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Granite City Vox Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Granite City Whistle.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Grooving Tom Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Happy Skies Drum Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Hazy Islands Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Hazy Islands Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Hazy Islands Beat 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Hazy Islands Drum Fill.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Hazy Islands Electric Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Hazy Islands Electric Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Hazy Islands Guitar Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Hazy Islands Synth Brass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Heard A Rumor Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Heard A Rumor Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Heard A Rumor Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Heard A Rumor Guitar Bend.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Heard A Rumor Keys.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Heard A Rumor Lead Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Heard A Rumor Synth Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Irreverent Echoes Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Jazzy Trumpet Riff.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Lights Out Whoosh FX.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Magic Guitalele Arp 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Magic Guitalele Arp 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Magic Guitalele Arp 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Magic Guitalele Choppy Chords.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Magic Guitalele Melody 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Magic Guitalele Melody 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Magic Guitalele Reverb FX.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Magic Guitalele Rhythm 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Magic Guitalele Rhythm 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Mellow Trumpet Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Muy Caliente 808.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Muy Caliente Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Muy Caliente Percussion 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Muy Caliente Percussion 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Muy Caliente Shaker.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Muy Caliente Synth Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Muy Caliente Synth Piano.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Muy Caliente Vox Percussion 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Muy Caliente Vox Percussion 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/New York LoFi Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/New York LoFi Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/New York LoFi Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/New York LoFi Hi-Hat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/New York LoFi Keys 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/New York LoFi Keys 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/New York LoFi Keys 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Outsider Swing Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Outsider Swing Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Over It Acoustic Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Over It Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Over It Claps.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Over It Fuzz Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Over It Synth Arp.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Over It Synth Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Over It Vocal Synth 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Over It Vocal Synth 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Pure Soul Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Pure Soul Claps.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Pure Soul Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Pure Soul Guitar Bend.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Pure Soul Guitar Strums.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Pure Soul Horn Pad.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Pure Soul Lead Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Pure Soul Reverse Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Pure Soul Rhythm Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Pure Soul Rhythm Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Pure Soul Synth Horn Stabs 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Pure Soul Synth Horn Stabs 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Pure Soul Vox.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rebel Grunge Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rustic Angels Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rustic Angels Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rustic Angels Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rustic Angels Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rustic Angels Guitar Riser.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rustic Angels Synth Riser.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rustic Angels Vox FX.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Beat 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Crackle FX.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail FX Riser.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Guitar Swells.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Lead Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Match FX 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Match FX 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Melody 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Melody 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Rhythm Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Rhythm Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Synth Riser.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Tom Fill.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Rusty Nail Vocoder Swells.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Smooth Jazz Trumpet 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Smooth Jazz Trumpet 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spooky Vibe Acoustic Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spooky Vibe Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spooky Vibe Electric Bass 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spooky Vibe Electric Bass 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spooky Vibe Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spooky Vibe Lead 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spooky Vibe Lead 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spooky Vibe Lead 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spooky Vibe Percussion.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spooky Vibe Vox FX 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spooky Vibe Vox FX 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spring Gossamer Beat 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spring Gossamer Beat 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spring Gossamer Drum Fill.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spring Gossamer Electric Bass.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spring Gossamer Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spring Gossamer Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spring Gossamer Guitar 03.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spring Gossamer Synth FX.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Spring Gossamer Vox Lead.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Stuffy Room Beat.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Time To Bounce Trumpet 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Time To Bounce Trumpet 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Triumphant Spirit Arp 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Triumphant Spirit Arp 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Triumphant Spirit Guitar Arp 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Triumphant Spirit Guitar Arp 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Triumphant Spirit Lead Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Triumphant Spirit Lead Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Triumphant Spirit Muted Guitar 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Triumphant Spirit Muted Guitar 02.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Triumphant Spirit Overdrive Guitar.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Triumphant Spirit Reverse Arp 01.caf",
    "~/Music/Logic Pro Library.bundle/Apple Loops/PomPom/Triumphant Spirit Reverse Arp 02.caf",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_apc0009_pompom.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/Clap1GreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/Clap2GreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/CrashGreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/HiHatGreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/HiHatOpenGreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/HiHatPedalGreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/Kick1GreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/Kick2GreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/NoiseFXGreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/RideGreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/RimGreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/ShakerGreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/Snare1GreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/Snare2GreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/TambourineGreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/TomHighGreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Green Lights.patch/TomLowGreenLights.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/Clap1LunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/Clap2LunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/CrashLunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/HiHat1LunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/HiHat2LunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/HiHatOpenLunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/Kick1LunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/Kick2LunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/PercLunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/RideLunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/RimLunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/ShakerLunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/Snare1LunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/Snare2LunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/TomHighLunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/TomLowLunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Lunar Bump.patch/TomMidLunarBump.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/ClapPhantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/CrashPhantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/HiHat1Phantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/HiHat2Phantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/HiHatOpenPhantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/Kick1Phantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/Kick2Phantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/Kick3Phantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/PercFX1Phantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/PercFX2Phantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/RimPhantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/ShakerPhantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/SnapPhantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/Snare1Phantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/Snare2Phantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/TomHighPhantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Phantoms.patch/TomLowPhantoms.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/ClapPuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/CrashPuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/Delay.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/HiHat1PuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/HiHat2PuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/HiHatOpenPuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/Kick1PuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/Kick2PuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/Perc1PuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/Perc2PuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/Reverb.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/RidePuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/RimPuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/ShakerPuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/SnapPuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/Snare1PuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/Snare2PuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/Pucker Pop.patch/TomPuckerPop.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 1 - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 2 - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/01 Kicks/Kick 3 - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Rim - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 1 - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/02 Snares/Snare 2 - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 1 - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat 2 - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Open - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/03 Hi-Hats/Hi-Hat Pedal - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Crash - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/04 Cymbals/Ride - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom High - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Low - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/05 Toms/Tom Mid - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 1 - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Clap 2 - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/06 Claps/Snap - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/07 Shakers/Shaker - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Lunar Bump.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Lunar Bump.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Lunar Bump.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc - Lunar Bump.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 1 - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Pucker Pop.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Pucker Pop.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Pucker Pop.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc 2 - Pucker Pop.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 1 - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 1 - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 1 - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 1 - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 2 - Phantoms.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 2 - Phantoms.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 2 - Phantoms.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Perc FX 2 - Phantoms.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/08 Percussion/Tambourine - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise FX - Green Lights.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise FX - Green Lights.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise FX - Green Lights.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Drums & Percussion/Electronic Drums/z01 Kit Pieces/09 FX/Noise FX - Green Lights.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Slide Attack Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Slide Attack Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Slide Attack Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Slide Attack Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Snappy Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Snappy Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Snappy Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Snappy Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Star Villain Bass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Star Villain Bass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Star Villain Bass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Bass/Star Villain Bass.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mellowed Out Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mellowed Out Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mellowed Out Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Mellowed Out Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Warbly Keys.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Warbly Keys.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Warbly Keys.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Keyboard/Warbly Keys.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Big Horn.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Big Horn.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Big Horn.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Big Horn.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Creepy Bells.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Creepy Bells.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Creepy Bells.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Creepy Bells.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Flanged Wobble.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Flanged Wobble.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Flanged Wobble.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Flanged Wobble.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Vocal Star.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Vocal Star.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Vocal Star.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Lead/Vocal Star.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Floating Flugels.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Floating Flugels.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Floating Flugels.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Floating Flugels.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/FM Bell Swells.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/FM Bell Swells.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/FM Bell Swells.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/FM Bell Swells.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Worn Tape Flutes.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Worn Tape Flutes.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Worn Tape Flutes.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Pad/Worn Tape Flutes.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Twilight Pulses.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Twilight Pulses.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Twilight Pulses.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/Synthesizer/Rhythmic/Twilight Pulses.patch/prelisten.caf",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/Rhythmic/Twilight Pulses.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Green Lights Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Lunar Bump Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Phantoms Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Drums & Percussion/Electronic Drums/Pucker Pop Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Bass/Slide Attack Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Bass/Snappy Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Bass/Star Villain Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Mellowed Out Keys.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Keyboard/Warbly Keys.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Lead/Big Horn.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Lead/Creepy Bells.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Lead/Flanged Wobble.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Lead/Vocal Star.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Pad/Floating Flugels.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Pad/FM Bell Swells.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Synthesizer/Pad/Worn Tape Flutes.exs",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/PomPom.logicx/Alternatives/000/DisplayState.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/PomPom.logicx/Alternatives/000/DisplayStateArchive",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/PomPom.logicx/Alternatives/000/DisplayStateMobile.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/PomPom.logicx/Alternatives/000/MetaData.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/PomPom.logicx/Alternatives/000/Project File Backups/00/MetaData.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/PomPom.logicx/Alternatives/000/Project File Backups/00/ProjectData",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/PomPom.logicx/Alternatives/000/ProjectData",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/PomPom.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/PomPom.logicx/Contents/Resources/template.tif",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/PomPom.logicx/Contents/Resources/template_ios.png",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/PomPom.logicx/Resources/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Live Loop Grids/PomPom.logicx/Resources/ProjectInformation.plist",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Clap 1 - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Clap 2 - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Crash - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Hi-Hat - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Hi-Hat Open - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Hi-Hat Pedal - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Kick 1 - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Kick 2 - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Noise FX - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Ride - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Rim - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Shaker - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Snare 1 - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Snare 2 - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Tambourine - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Green Lights Kit/Tom - Green Lights.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Clap 1 - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Clap 2 - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Crash - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Hi-Hat 1 - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Hi-Hat 2 - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Hi-Hat Open - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Kick 1 - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Kick 2 - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Perc - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Ride - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Rim - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Shaker - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Snare 1 - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Snare 2 - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Tom High - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Tom Low - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Lunar Bump Kit/Tom Mid - Lunar Bump.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Clap - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Crash - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Hi-Hat 1 - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Hi-Hat 2 - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Hi-Hat Open - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Kick 1 - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Kick 2 - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Kick 3 - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Perc FX 1 - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Perc FX 2 - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Rim - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Shaker - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Snap - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Snare 1 - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Snare 2 - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Tom High - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Phantoms Kit/Tom Low - Phantoms.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Clap - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Crash - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Hi-Hat 1 - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Hi-Hat 2 - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Hi-Hat Open - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Kick 1 - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Kick 2 - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Perc 1 - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Perc 2 - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Ride - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Rim - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Shaker - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Snap - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Snare 1 - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Snare 2 - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Electronic Drums/Pucker Pop Kit/Tom - Pucker Pop.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bass/Slide Attack Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bass/Snappy Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Bass/Star Villain Bass.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Mellowed Out Keys.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Keys/Warbly Keys.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Lead/Big Horn.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Lead/Creepy Bells.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Lead/Flanged Wobble.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Lead/Vocal Star.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Pad/Floating Flugels.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Pad/FM Bell Swells.aif",
    "~/Music/Logic Pro Library.bundle/Samples/Synthesizer/Pad/Worn Tape Flutes.aif",
  ]
end
