cask "ml-arx0007-elliedixon" do
  version "bc227a10ae2af43a69f1a2a44da024ce-43"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_arx0007_elliedixon/ml_arx0007_elliedixon.aar"
  name "EllieDixon"
  desc "Swing!"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_arx0007_elliedixon/ml_arx0007_elliedixon.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_arx0007_elliedixon.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_arx0007_elliedixon.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Alternatives/004/DisplayState.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Alternatives/004/DisplayStateArchive",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Alternatives/004/DisplayStateMobile.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Alternatives/004/MetaData.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Alternatives/004/ProjectData",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Alternatives/004/WindowImage.jpg",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Contents/Resources/template.png",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Alchemy Samples/Old Fragile Vinyl KeysA0000-056_G#2KM56_M-AF_2.aaz",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Alchemy Samples/Old Fragile Vinyl KeysB0000-Marimba ln f l1x  4a-AF_2.aaz",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Ac Guitar L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Ac Guitar R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Ac Guitar Riff alt L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Ac Guitar Riff alt R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Ac Guitar Riff alt4 L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Ac Guitar Riff alt4 R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Acoustic Guitar 1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Acoustic Guitar 10.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Acoustic Guitar 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Acoustic Guitar 3.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Acoustic Guitar 4.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Acoustic Guitar 5.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Acoustic Guitar 6.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Acoustic Guitar 7.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Acoustic Guitar 8.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Acoustic Guitar 9.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Acoustic Guitar.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Alien Feedback.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Backbeat Hats.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Baseball Bat FX.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Baseball Game.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Baseball Swing FX.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Bass 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Bass 3.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Bass 4.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Bass 5.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Bass Wind Down.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Bass.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Batter Up 1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Batter Up 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Batter Up 3.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Batter Up 4.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Batter Up 5.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Batter Up 6.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Batter Up 7.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Batter Up Alt.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Birds Pitched.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Birds.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Chorus Kick.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Chorus Vocal 1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Chorus Vocal 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Chorus Vocal 3.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Chorus Vox.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Closed HiHat.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Crowd Cheer.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Crowd Noise 1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Crowd Noise 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Crowd Noise 3.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Crowd Noise 4.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Crowd Noise 5.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Crowd Noise 6.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Distortion Build.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Distortion Layer.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Foley Snare.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Guitar 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Guitar 3.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Guitar 4.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Guitar Bass Double.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Guitar Chaos 1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Guitar Chaos 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Guitar Chaos 3.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Guitar Chaos 4.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Guitar Double 1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Guitar Double 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Guitar Riff improv L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Guitar Riff improv R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Guitar Riff L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Guitar Riff R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Harmony Vocal alt 1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Home Run.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Ice Keys alt 1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Ice Keys.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Layered Vocal L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Layered Vocal R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lead Vocal 1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lead Vocal 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lead Vocal 3.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low  Vocal alt lyr 3 .aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Harmony 1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Harmony Vocal.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Spoken Vocal 1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Spoken Vocal 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Vocal alt lyr 1 .aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Vocal alt lyr 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Vocal L alt 1 L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Vocal L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Vocal lyr 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Vocal Lyr 4.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Vocal Lyr 5.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Vocal lyr L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Vocal lyr R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Vocal R adlib.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Vocal R alt 1 R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Low Vocal R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal 1 L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal 1 R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal 2 L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal 2 R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal 3 L .aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal 3 R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal 4 L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal 4 R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal 5 L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal 5 R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal 6 L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal 6 R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal 7 L .aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal 7 R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Lyr Vocal R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Noise Curve.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Noise Sweep.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Outro Vocal.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Reversed Keys.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Ride Cymbal.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Shaker.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Snare Acoustic.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Snare Rim.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal 1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal 3.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal 4.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal 5.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal 6.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal 7.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal adlib 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal adlib 3.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal adlib.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt 5.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 10.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 11.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 12.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 13.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 14.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 15.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 16.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 17.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 18.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 19.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 3.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 4.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 5.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 6.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 7.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 8.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal alt lyr 9.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal lyr 1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal lyr 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal lyr 3.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal lyr 4.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Spoken Vocal lyr 5.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Strident Vocal adlib L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Strident Vocal adlib R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Strident Vocal Alt L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Strident Vocal Alt R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Strident Vocal alt2 L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Strident Vocal L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Strident Vocal lyr 5.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Strident Vocal lyr 6.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Strident Vocal Lyr L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Strident Vocal Lyr R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Strident Vocal Lyr3 R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Strident Vocal.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Texture Vocal.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Thirds improv L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Thirds improv R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Thirds Vocal alt lyr L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Thirds Vocal alt lyr R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Thirds Vocal L alt 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Thirds Vocal L alt 3.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Thirds Vocal L alt.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Thirds Vocal L_1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Thirds Vocal Lyr 5 L.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Thirds Vocal Lyr 5 R.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Thirds Vocal R alt 2.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Thirds Vocal R alt 4.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Thirds Vocal R alt.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Thirds Vocal R_1.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Audio Files/Whoosh.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Impulse Responses/0.2s_Snare Stretch.SDIR_1",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Impulse Responses/0.4s_Snare Chamber.SDIR_1",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Impulse Responses/02.0s Amphitheater-OST.SDIR_1",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Impulse Responses/1.6s_Bight & Empty.SDIR_1",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_A#6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_A#7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_A6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_A7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_B6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_B7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_C#6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_C#7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_C#8.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_C6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_C7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_C8.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_D#6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_D#7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_D#8.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_D6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_D7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_D8.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_E6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_E7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_E8.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_F#6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_F#7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_F6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_F7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_F8.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_G#6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_G#7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_G6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_f_G7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_A#6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_A#7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_A6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_A7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_B6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_B7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_C#6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_C#7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_C#8.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_C6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_C7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_C8.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_D#6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_D#7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_D#8.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_D6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_D7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_D8.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_E6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_E7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_E8.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_F#6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_F#7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_F6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_F7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_F8.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_G#6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_G#7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_G6.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Crotales/CHRO-Tri_p_G7.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Mellow Vibe Piano/Mellow Vibe Piano_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Old-Time Recording Keys/Old-Time Recording Keys_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Quick Sampler/Glass Piano.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Quick Sampler/Kick_1_Ibiza.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Quick Sampler/Room Snaps.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Quick Sampler/Snare 01 - Cinematic Funk.aif",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-01-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-02-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-03-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-04-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-05-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-06-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-07-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-08-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-09-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-10-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-11-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-12-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-13-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-14-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Media/Samples/Snaps/D2 SNAP-15-LR.wav",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Resources/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Demo Songs/Swing!.logicx/Resources/ProjectInformation.plist",
  ]
end
