cask "ml-ccp0005-jampack-orchestral" do
  version "36d4a7c63154f4cb75504168ff9e7b78-431"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_ccp0005_jampack_orchestral/ml_ccp0005_jampack_orchestral.aar"
  name "JamPackSymphonyOrchestra"
  desc "CompatibilityPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_ccp0005_jampack_orchestral/ml_ccp0005_jampack_orchestral.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_ccp0005_jampack_orchestral.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Apple Loops/z_Legacy/Orchestral",
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_ccp0005_jampack_orchestral.plist",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/02 Halls/06.6s Botta Church-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/01 Large Spaces/03 Plate Reverbs/4.4s_Big Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/02 Medium Spaces/01 Rooms/02.6s Hansa Studio-OST.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/01 Rooms/0.3s_Wooden Booth.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/02 Halls/1.3s_Diffuse Hall.SDIR",
    "~/Music/Logic Pro Library.bundle/Impulse Responses/03 Small Spaces/03 Plate Reverbs/1.1s_Vocal Plate.SDIR",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/French Horn Solo.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/French Horn Solo.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/French Horn Solo.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/French Horns.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/French Horns.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/French Horns.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/Full Brass.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/Full Brass.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/Full Brass.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/Trombones.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/Trombones.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/Trombones.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/Trumpets.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/Trumpets.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/Trumpets.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/Tuba.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/Tuba.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Brass/Tuba.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Boys Chamber Ensemble.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Boys Chamber Ensemble.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Boys Chamber Ensemble.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Chamber Choir.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Chamber Choir.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Chamber Choir.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Church Choir.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Church Choir.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Church Choir.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Classical Ensemble.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Classical Ensemble.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Classical Ensemble.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Classical Female Ensemble.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Classical Female Ensemble.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Classical Female Ensemble.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Classical Male Ensemble.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Classical Male Ensemble.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Classical Male Ensemble.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Female Chamber Choir.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Female Chamber Choir.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Female Chamber Choir.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Gospel Ensemble.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Gospel Ensemble.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Gospel Ensemble.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Gospel Vocal Effects.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Gospel Vocal Effects.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Gospel Vocal Effects.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Male Chamber Choir.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Male Chamber Choir.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Male Chamber Choir.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Mixed Choir.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Mixed Choir.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Choir/Mixed Choir.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Harp/Harp.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Harp/Harp.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Harp/Harp.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Keyboard/Celesta.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Keyboard/Celesta.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Keyboard/Celesta.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Keyboard/Harpsichord.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Keyboard/Harpsichord.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Keyboard/Harpsichord.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Crotales.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Crotales.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Crotales.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Glockenspiel.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Glockenspiel.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Glockenspiel.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Orchestral Kit.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Orchestral Kit.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Orchestral Kit.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Timpani.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Timpani.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Timpani.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Tubular Bells.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Tubular Bells.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Tubular Bells.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Xylophone.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Xylophone.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Percussion/Xylophone.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Basses.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Basses.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Basses.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Cellos.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Cellos.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Cellos.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Cinema Strings.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Cinema Strings.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Cinema Strings.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Full Strings.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Full Strings.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Full Strings.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Modern Strings.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Modern Strings.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Modern Strings.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Pop Strings.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Pop Strings.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Pop Strings.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Romance Strings.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Romance Strings.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Romance Strings.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Session Strings.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Session Strings.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Session Strings.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Smart Strings.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Smart Strings.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Smart Strings.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Studio Strings.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Studio Strings.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Studio Strings.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Violas.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Violas.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Violas.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Violins 1.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Violins 1.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Violins 1.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Violins 2.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Violins 2.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Strings/Violins 2.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Bassoon Solo.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Bassoon Solo.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Bassoon Solo.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Clarinet Solo.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Clarinet Solo.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Clarinet Solo.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Clarinets.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Clarinets.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Clarinets.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/English Horn.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/English Horn.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/English Horn.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Flute Solo.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Flute Solo.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Flute Solo.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Flutes.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Flutes.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Flutes.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Oboe.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Oboe.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Oboe.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Piccolo.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Piccolo.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Piccolo.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Saxophone.patch/#Root.cst",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Saxophone.patch/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Patches/Instrument/z_Legacy/Orchestral/Woodwinds/Saxophone.patch/data.plist",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Brass & Woodwinds/Funk Horn Section.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Keyboard/Acoustic Piano/Steinway Grand Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Keyboard/Acoustic Piano/Steinway Piano & Pad.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Keyboard/Acoustic Piano/Steinway Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Mallet/Glockenspiel.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Mallet/Marimba.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/01 Woodwinds",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/02 Brass",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/03 Percussion",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/04 Tuned Percussion",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/05 Keyboards",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/06 Harp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/07 Pipe Organ",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/09 Strings",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/10 Choir/Boys Chamber Ensemble+.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/10 Choir/Chamber Ensemble+.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/10 Choir/Chamber Female Ensemble+.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/10 Choir/Chamber Male Ensemble+.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/10 Choir/Church Choir.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/10 Choir/Classical Ensemble+.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/10 Choir/Classical Female Ensemble+.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/10 Choir/Classical Male Ensemble+.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/10 Choir/Gospel Ensemble+.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/10 Choir/Gospel Voice Effects+.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Orchestral/10 Choir/Mixed Choir.exs",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/04 Orchestral.logicx/Alternatives/000/DisplayState.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/04 Orchestral.logicx/Alternatives/000/DisplayStateArchive",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/04 Orchestral.logicx/Alternatives/000/MetaData.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/04 Orchestral.logicx/Alternatives/000/ProjectData",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/04 Orchestral.logicx/Contents/PkgInfo",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/04 Orchestral.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/04 Orchestral.logicx/Contents/Resources/template.tif",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/04 Orchestral.logicx/Resources/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/04 Orchestral.logicx/Resources/ProjectInformation.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/06 Music For Picture.logicx/Alternatives/000/DisplayState.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/06 Music For Picture.logicx/Alternatives/000/DisplayStateArchive",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/06 Music For Picture.logicx/Alternatives/000/MetaData.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/06 Music For Picture.logicx/Alternatives/000/ProjectData",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/06 Music For Picture.logicx/Contents/PkgInfo",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/06 Music For Picture.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/06 Music For Picture.logicx/Contents/Resources/template.tif",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/06 Music For Picture.logicx/Resources/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/06 Music For Picture.logicx/Resources/ProjectInformation.plist",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Steinway Grand Piano/Steinway Pedal V1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Steinway Grand Piano/Steinway Pedal V2",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Steinway Grand Piano/Steinway Pedal V3",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Steinway Grand Piano/Steinway V2",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Steinway Grand Piano/Steinway V3",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Steinway Grand Piano/Steinway V4",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Keyboard/Steinway Grand Piano/Steinway V5",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Mallet/Glockenspiel_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Mallet/Marimba",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Alto Sax",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Basses/Basses-L_legato_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Basses/Basses-L_legato_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Basses/Basses-L_legato_p",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Basses/Basses-L_tremolo_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Basses/Basses-L_trills-ht",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Basses/Basses-L_trills-wt",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Basses/Basses_pizz_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Basses/Basses_pizz_p",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Basses/Basses_stac_downbow_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Basses/Basses_stac_downbow_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Basses/Basses_stac_upbow_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Basses/Basses_stac_upbow_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Bassoon Solo/Bassoon-L_LV_na_sus_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Bassoon Solo/Bassoon-L_nA_sus_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Bassoon Solo/Bassoon_stac_f1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Bassoon Solo/Bassoon_stac_mf1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Celesta/Celesta_ES_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Cellos/Cellos-L_legato_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Cellos/Cellos-L_legato_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Cellos/Cellos-L_legato_p",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Cellos/Cellos-L_tremolo_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Cellos/Cellos-L_trills_ht",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Cellos/Cellos-L_trills_wt",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Cellos/Cellos_pizz_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Cellos/Cellos_pizz_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Cellos/Cellos_stac_downbow_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Cellos/Cellos_stac_downbow_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Cellos/Cellos_stac_upbow_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Cellos/Cellos_stac_upbow_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Choir/Boys Choir",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Choir/Chamber Choir/Chamber Female",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Choir/Chamber Choir/Chamber Male",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Choir/Church Choir",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Choir/Classical Choir/Classical Choir Female",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Choir/Classical Choir/Classical Choir Male",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Choir/Gospel Choir Voice Effects",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Choir/Gospel Choir",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Choir/Mixed Choir",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Church Organ/Organ Ged 8",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Church Organ/Organ Ged 8,4",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Church Organ/Organ Ged 8,4,2",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Church Organ/Organ Ged 8,4,2,Q",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Church Organ/Organ Ped 16,8",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Church Organ/Organ Ped 16,8,8",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Church Organ/Organ Pr 8",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Church Organ/Organ Pr 8,4",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Church Organ/Organ Pr 8,4,2 mix",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Church Organ/Organ Pr 8,4,2",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Church Organ/Organ Tutti",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Clarinet Solo/Clarinet-L_pA_sus_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Clarinet Solo/Clarinet_stac_f1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Clarinet Solo/Clarinet_stac_mp1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Clarinets/Clarinets-L_sus_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Clarinets/Clarinets-L_sus_p",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Clarinets/Clarinets_stac_f1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Clarinets/Clarinets_stac_mp1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Classical Flute",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Crotales/Crotales-Me_p",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Deep Bass",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/English Horn Solo/English Horn-L_mV_sus_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/English Horn Solo/English Horn_stac_f1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/English Horn Solo/English Horn_stac_mf1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Flute ensemble/Flutes-L_sus_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Flute ensemble/Flutes-L_sus_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Flute ensemble/Flutes_stac_f1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Flute ensemble/Flutes_stac_mf1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Flute Solo/Flute_LV_na_sus_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Flute Solo/Flute_stac_f1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Flute Solo/Flute_stac_mp1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/French Horns/French Horns_cre2_2s_mf-f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/French Horns/French Horns_nA_sus_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/French Horns/French Horns_nA_sus_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/French Horns/French Horns_stac_f1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/French Horns/French Horns_stac_mf1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Funk Horn Section",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Harp/Harp_ES_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Harpsichord",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Horn Solo/French Horn-L_oV_nA_sus_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Horn Solo/French Horn-L_oV_nA_sus_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Horn Solo/French Horn_oV_hA_4-120_f1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Horn Solo/French Horn_oV_hA_4-120_mf1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Oboe Solo/Oboe-L_mV_nA_sus_mp",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Oboe Solo/Oboe-L_wA_1-105_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Oboe Solo/Oboe_stac_f1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Oboe Solo/Oboe_stac_mf1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Additional Percussion",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Anvil",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Belltree",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Castanet",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/China Gong",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Claves",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Cymbal",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Field drum o",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Field drum w",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Glas-Chimes",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Gran casa",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Guiro",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/KTr_RS_trem",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Ktr_trem",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Piatti",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Piccolo drum",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Ratsche-4",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Roto_toms",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Shaker",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Sleigh-Bells1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Slitdrum",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Snare",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Taiko drum",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Tamburin",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Tamtam",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Triangle",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Wip",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Orchestral Kit/Woodblocks",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Piccolo/Piccolo-L_LV_nA_sus_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Piccolo/Piccolo_stac_f1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Piccolo/Piccolo_stac_p1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/String Ensemble",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Timpani/Timp-L_HA_trem_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Timpani/Timp-L_HA_trem_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Timpani/Timp-L_HA_trem_p",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Timpani/Timp_HA_ES_f1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Timpani/Timp_HA_ES_ff1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Timpani/Timp_HA_ES_mf1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Timpani/Timp_HA_ES_p1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Timpani/Timp_HA_trem-dyn_pp-ff_2s",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Trombones/Trombones_nA_sus_ff",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Trombones/Trombones_nA_sus_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Trombones/Trombones_stac_ff1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Trombones/Trombones_stac_mf1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Trumpets/Trumpets_nA_sus_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Trumpets/Trumpets_nA_sus_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Trumpets/Trumpets_stac_f1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Trumpets/Trumpets_stac_mf1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Tuba Solo/Tuba-L_nA_sus_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Tuba Solo/Tuba_stac_ff1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Tuba Solo/Tuba_stac_mf1",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Tubular Bells/Tubular Bells_led_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violas/Violas-L_legato_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violas/Violas-L_legato_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violas/Violas-L_legato_p",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violas/Violas-L_tremolo_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violas/Violas-L_trills-ht",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violas/Violas-L_trills-wt",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violas/Violas_pizz_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violas/Violas_pizz_p",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violas/Violas_stac_downbow_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violas/Violas_stac_downbow_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violas/Violas_stac_upbow_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violas/Violas_stac_upbow_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 1/Violins 1-L_legato_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 1/Violins 1-L_legato_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 1/Violins 1-L_legato_p",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 1/Violins 1-L_tremolo_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 1/Violins 1-L_trills-ht",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 1/Violins 1-L_trills-wt",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 1/Violins 1_pizz_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 1/Violins 1_pizz_p",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 1/Violins 1_stac_downbow_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 1/Violins 1_stac_downbow_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 1/Violins 1_stac_upbow_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 1/Violins 1_stac_upbow_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 2/Violins 2-L_legato_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 2/Violins 2-L_legato_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 2/Violins 2-L_legato_p",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 2/Violins 2-L_tremolo_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 2/Violins 2-L_trills-ht",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 2/Violins 2-L_trills-wt",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 2/Violins 2_pizz_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 2/Violins 2_pizz_p",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 2/Violins 2_stac_downbow_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 2/Violins 2_stac_downbow_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 2/Violins 2_stac_upbow_f",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Violins 2/Violins 2_stac_upbow_mf",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Orchestral/Xylophone/Xylophone_HO_f_L",
    "~/Music/Logic Pro Library.bundle/Samples/z_Legacy/Strings/Strings_consolidated.caf",
  ]
end
