cask "ml-ccp0018-alchemy-vintage-synth" do
  version "4b4eae7d5b14e3ed29b7365fca72d529-79"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_ccp0018_alchemy_vintage_synth/ml_ccp0018_alchemy_vintage_synth.aar"
  name "AlchemyVintageSynths"
  desc "CompatibilityPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_ccp0018_alchemy_vintage_synth/ml_ccp0018_alchemy_vintage_synth.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_ccp0018_alchemy_vintage_synth.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_ccp0018_alchemy_vintage_synth.plist",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Arpeggiated/70s Analog Sequencer.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Arpeggiated/80s Pop Synth Arpeggiator.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Arpeggiated/Berlin Oscillators.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Arpeggiated/Bouncing Comets.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Arpeggiated/Chunky Arpeggio Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Arpeggiated/Dark and Soft.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Arpeggiated/Hollow Psychedelic.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Arpeggiated/Mandrake Arp.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Arpeggiated/Microscopic Sine Waves.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Arpeggiated/Mod Arp Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Arpeggiated/Modern Bass Arpeggiator.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Arpeggiated/Ricocheting Phaedra.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Arpeggiated/Solid Modular.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Arpeggiated/Square Randomizer.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/70s Synth Intro.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/80s Classic Synth Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/80s Electro Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/80s Synth Pop Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Analog Dark Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Analog Dark Decay.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Analog Dark Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Analog Funk Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Analog Monster Punch.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Analog Saw Punch.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Analog Slow Sweep.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Analog Sub Sonic.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Analog Tight Sync Buzz.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Analogue Happiness.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Bass And Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Black Leather.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Block Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Boogie Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Chaos Glide Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Classic Lead Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Deep Plucks.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Deep Solid Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/DnB Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Fire Hose.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Funk Bass Sweeper.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Funk Boogie Synth Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Funk Buzz Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Juicy Funk Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Metrix Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Music and Lights.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Old Soul Funk.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Oxygen Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Parasite.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Resonant Sweep Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/River Of Sub Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Rotor Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Space Dance Octaves.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Steady Wobble Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Street Dance.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Sweep Saw Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Synth Mode.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Ultra Fat Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Vintage Resonant Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Wave Layers Bass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Bass/Wet Willy.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Brass/80s Pop Synth Brass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Brass/80s Slow Pop Sweep.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Brass/Brass Response.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Brass/Brassy Pad Swell.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Brass/Jump.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Brass/Oceanic.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Brass/Out Of Touch.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Brass/Prophetic Brass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Brass/Space Brass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Brass/Street Boogie.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Brass/Vintage Brassy Pad.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/70s Analog Synth Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/80s Analog Bells.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/80s Synth Pop Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Airy Synth Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Ana Lead Toolbox.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Analog Mellow Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Analog Sync Decay Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Analog Unison Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Anthem Hook Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Big 7th Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Bricks.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Bright Glide Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Burst Of Light.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Butter Cut Saw.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Butter Cut Square.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Classic 70s Funk Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Classic 70s Synth Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Classic 80s Epic Brass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Classic 80s Synth Brass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Classic.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Crazy Diamond.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Crispy Glide Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Dual Multipliers.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Epic Rift.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Festival Saw Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Fifths Super Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Flex Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Flutter Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Fluttering Patterns.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Funk Boogie Synth Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Funk Spike.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Futuristic Synth Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Grainy Blows.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Leads United.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Luscious Analog Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Mini Saw Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Modern R&B Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Monstrous Synth Stack.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Oddity.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Otherworldly Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Phase Saw.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Psychedelic Lab.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Pulse Width Fifths.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Punchy 80s Synth.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Purple Key.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Resonant Funk Solo.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Resonant Sweep.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Retro Synth Bells.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Ricochet Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Robot Learning To Speak.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Saw Glide Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Scream Sync.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Sizzle Oscillator.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Soft 70s Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Soft Comb Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Soft Distortion Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Soft Velocity Attack Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Space Rock Solo Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Square Squad.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Stretched Legato.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Stretched Staccato.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Sweeping Synth Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Sweet n Fuzzy.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Sweet Tremolo Keys.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Tempo Sync Morph Tremolo.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Time Wind.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Tokyo Futures.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Trance Lead Designer.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Triangle Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Triangular Phase.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Vox-like Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Lead/Wavetable Morph Lead.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Analog Pulse Pad.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Analog Resonant Sweep 01.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Analog Resonant Sweep 02.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Analog Silk.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Angelic Analog.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Band Pass Luster.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Brightly Glistening.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Candy Pop.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Chorused Dirt.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Dark Universe.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Deep Space Sweep.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Density Sine.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Double Bandwidth Pad.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Dual Ring Mod Pad.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Filtered Squares.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Flange Balm.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Folded Fifths.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Four Wave Morph Pad.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Fuzzy VCOs.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/High Altitude Drift.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Loose and Swirly.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Lunar Pools.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Luscious Sweeps.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Luscious Waves.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Majestic Waves.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Mellotron Flute.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Obie Warmth.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Oxygen Strings.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Phased Beauty.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Pulse Sweep.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Q Sweep.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Resonant Sweeps.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Sea Wave.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Slow Dual Formant Pad.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Soft and Gentle.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Swept Saw Pad.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Swirling Combs.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/The Wanderer.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Triangle Pad.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Vowel Phasing.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Warm and Soft.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Warm Vintage Analog Pads.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Pad/Wavetable Morphs.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Sound Effects/Grainy Sample and Hold.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Sound Effects/Hats Sequence.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Sound Effects/Hyper Spin.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Sound Effects/Hyper-Spin.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Sound Effects/Resonant Sample and Hold.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Sound Effects/Rise Bubble Sine.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Sound Effects/Shimmering Stars.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Strings",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Aluminum Bandpass.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Aqua Motif.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Attack Sweep.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Bending Around Synth.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Binary Sun.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Bright Sky.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Classic 80s Synth.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Cream Pie.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Crossing Destiny.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Dust Synth.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Editorial.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Electronic Rose Keys.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Ensemble Power Pluck.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Fluid PWM Pick.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Layer Synth Pick.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Luscious Polyphony.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Lush Meadows.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Mellow Synth.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Midnight Jupiter Keys.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Mirror Objects.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Motion Pluck.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Needle Fraction.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Phase Square Pick.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Phasers Set to Stun.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Poly Synth Forever.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Poly Talking Synth.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Power Lurks Within.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Pulse Sugar Pick.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Pulses and Pad.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Pumping Out Waves.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Pure Poly Synth Stack.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Retro Synth Pluck.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Silver Saw.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Simple Analog.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Sine D.N.A..acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Skylight.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Snow Fall Bells.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Soft Fun.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Soft Plucky Synth.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Southern Living.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Suburban.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Sweet Dreams Pick.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Synth Pop Pick.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Tokyo Pick.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Velocity Duelists.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Vintage Obsession.acp",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Alchemy/z_Legacy/Synth/Wide Splashy Pad.acp",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/1974 Dark Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Nasal Boost Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Saw Punch Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Sub Sonic Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Tri Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Wow Bass/Analog Wow Bass C0.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Wow Bass/Analog Wow Bass C1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Wow Bass/Analog Wow Bass C2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Wow Bass/Analog Wow Bass C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Wow Bass/Analog Wow Bass C4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Wow Bass/Analog Wow Bass F#0.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Wow Bass/Analog Wow Bass F#1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Wow Bass/Analog Wow Bass F#2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Analog Wow Bass/Analog Wow Bass F#3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Arpy Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Dirty Swell Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 2 Saw Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Saws",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares A1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares A2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares A3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares A4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares A5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares C4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares C5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares C6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Eb2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Eb3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Eb4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Eb5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Gb1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Gb2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Gb3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Gb4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini 3 VCO Squares/Mini 3 VCO Squares Gb5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini M Attack Sust Bass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Mini Synth",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Analog Bass/Tube Triangle",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/Black Sun/Black Sun C0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/Black Sun/Black Sun C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/Black Sun/Black Sun F#0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/Black Sun/Black Sun F#1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/CBass Math",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Digital Bass/Shocking Wave",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Real Bass/MMBass Mute",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Bass/Single Samples/Doom Wave C1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass A0.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass A1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass A2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass A3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass A4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass A5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass C0.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass C1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass C2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass C4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass C5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass C6.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass D#0.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass D#1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass D#2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass D#3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass D#4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass D#5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass F#0.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass F#1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass F#2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass F#3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass F#4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/80s Analog Brass/80s Analog Brass F#5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/Analog Dark Tuba",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/FM Voice OB Brass",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/Vintage Synth Horn",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Brass/Synth Brass/Vintage Synth Trumpet",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Drums/Electronic Drums/Ambient/Ambient Kick 2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Electric Guitars/Pad Scratching",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Guitars/Electric Guitars/Stereo Steel",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Harpsichord 1/Harpsichord 1 Mute A3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Harpsichord 1/Harpsichord 1 Mute A4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Harpsichord 1/Harpsichord 1 Mute B2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Harpsichord 1/Harpsichord 1 Mute B5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Harpsichord 1/Harpsichord 1 Mute C4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Harpsichord 1/Harpsichord 1 Mute C5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Harpsichord 1/Harpsichord 1 Mute D3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Harpsichord 1/Harpsichord 1 Mute E4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Harpsichord 1/Harpsichord 1 Mute E5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Harpsichord 1/Harpsichord 1 Mute F2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Harpsichord 1/Harpsichord 1 Mute F3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Harpsichord 1/Harpsichord 1 Mute G2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Keys/Other Keys/Harpsichord 1/Harpsichord 1 Mute G5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Loops/Melodic Loops/MM Love It Synth C3 128bpm 16bts.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Analog/80s Classic Synth",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Dirty Flange C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Fast Bandpass.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Formant Atmo C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Glissing Resonance 01 C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Glissing Resonance 02 C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Loose And Floppy 01 C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Loose And Floppy 02 C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Phased Beauty 01 C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Phased Beauty 02 C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Slow Bandpass.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Soft Fifth Blend C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Soft Flange C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Wanderer 01 C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Pads/Single Samples/Wanderer 02 C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Sound Effects/Technology/Circuit Bent/CB Tand 19.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Single Samples/Super Rich Wave 01 C2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Single Samples/Super Rich Wave 02 C2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Soundscapes/Single Samples/Theory Atmo C2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Mellotron Violins",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Synth Strings 2",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Synth Strings I",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Vintage Synth Viola",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Vintage Synth Violin",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Vocoder Bright Strings",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Strings/Synth Strings/Vocoder Strings",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Ambient Solo",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Sawtooth",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C7.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Square/1974 Square C8.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Triangle",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Wet Funk Solo",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/1974 Wet Funk Solo2",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 102 C1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 102 C2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 102 C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 102 C4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 102 C5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 102 F#1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 102 F#2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 102 F#3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 102 F#4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 103 C1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 103 C2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 103 C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 103 C4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 103 C5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 103 F#1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 103 F#2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 103 F#3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog 103 F#4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Saturation C1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Saturation C2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Saturation C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Saturation C4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Saturation C5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Saturation F#1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Saturation F#2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Saturation F#3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Saturation F#4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Sweep C1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Sweep C2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Sweep C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Sweep C4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Sweep C5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Sweep F#1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Sweep F#2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Sweep F#3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog 101/Analog Sweep F#4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Open Saws",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Sync Buzz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead A#1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead A#2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead A#3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead A#4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead A#5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead A#6.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead A#7.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead C1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead C2-C-A-1.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead C2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead C4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead C5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead C6.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead C7.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead C8.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead E1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead E2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead E3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead E4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead E5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead E6.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead E7.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead G1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead G2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead G3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead G4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead G5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead G6.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Analog Unison Lead/Analog Unison Lead G7.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Dream Sweep",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Dual Triangles",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty 2",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty A 1 1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty A 2 1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty A 3 1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty A 4 1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty C 1 1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty C 2 1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty C 4 1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty C 5 1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty C3 1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty Eb 1 1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty Eb 2 1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty Eb 3 1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty Eb 4 1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty Gb 1 1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty Gb 2 1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty Gb 3 1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat And Dirty/Fat And Dirty Gb 4 1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Fat Strings",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Handmade Synth",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Hard Sync",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Mini M Attack Sweep",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Mini M Dark Decay",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Noise Pad",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Short Saw",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm A1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm A2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm A3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm A4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm A5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm C1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm C2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm C4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm C5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm C6.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm Eb1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm Eb2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm Eb3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm Eb4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm Eb5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm Gb1.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm Gb2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm Gb3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm Gb4.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Stereo P W M/Stereo Pwm Gb5.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Sync Decay Pulse",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz A#0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz A#1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz A#2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz A#3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz A#4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz A#5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz A#6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz A0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz C1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz C2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz C3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz C4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz C5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz C6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz C7.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz E1.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz E2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz E3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz E4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz E5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz E6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz F0.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz G2.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz G3.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz G4.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz G5.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Three Saw Buzz/Three Saw Buzz G6.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Titanic Saw",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Waveshaped Sines",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Analog/Wide Trance",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Burst Of Light-B-A00.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Butter Cut Saw-A-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Butter Cut Square-A-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Classic 80s Synth Brass-C-A-1.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Classic 80s Synth Brass-D-A-1.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Editorial-A-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Editorial-B-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Luscious Analog Lead-A-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Custom/Sine D.N.A.-A-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/Digitalis Pad/Digitalis Pad C4-A-A01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Digital/FM Saw",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/High Detuning Sines C7.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Lead Sync 2 Lt Z.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Soft Monopad Db3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Synth Growl Db2.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Wavetables/Wavetable A 01.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Wavetables/Wavetable A 02.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Wavetables/Wavetable B 01.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/Wavetables/Wavetable B 02.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/West Coast Synth Waveforms/Hard Vowel Drone C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/West Coast Synth Waveforms/Soft Vowel Drone C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/West Coast Synth Waveforms/West Coast Synth Stereo Soft Sync 1 C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/West Coast Synth Waveforms/West Coast Synth Stereo Soft Sync 2 C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/West Coast Synth Waveforms/West Coast Synth Wave Multiplier 1 C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Synth/Single Samples/West Coast Synth Waveforms/West Coast Synth Wave Multiplier 2 C3.wav",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Vocals/Vocal Instruments/Vox Smothered/Vox Smothered 1 Sus mf A1-A-AS01.aaz",
    "~/Music/Logic Pro Library.bundle/Samples/Alchemy Samples/Woodwinds/Synth Woodwinds/Mellotron Flutes",
  ]
end
