cask "ml-ccp0008-logic10-instruments" do
  version "8fe9c9aba78dc3ed7f152b7f31d04224-885"
  sha256 :no_check

  url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_ccp0008_logic10_instruments/ml_ccp0008_logic10_instruments.aar"
  name "LogicProLegacyInstruments"
  desc "CompatibilityPack"
  homepage "https://audiocontentdownload.apple.com/"

  livecheck do
    url "https://audiocontentdownload.apple.com/universal/ContentPacks_3/ml_ccp0008_logic10_instruments/ml_ccp0008_logic10_instruments.aar"
    strategy :header_match do |headers|
      etag = headers["etag"]
      return unless etag

      etag = etag.delete_prefix('"')
      etag = etag.delete_suffix('"')
      etag.downcase
    end
  end

  preflight do
    require "fileutils"
    target_dir = File.expand_path("~/Music/Logic Pro Library.bundle")
    FileUtils.mkdir_p(target_dir)
    system "aa", "extract", "-i", File.join(staged_path, "ml_ccp0008_logic10_instruments.aar").to_s, "-d",
           target_dir
  end

  zap trash: [
    "~/Music/Logic Pro Library.bundle/Application Support/Package Definitions/ml_ccp0008_logic10_instruments.plist",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Blue Ridge Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Bluebird Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Brooklyn Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Detroit Garage Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/East Bay Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Four on the Floor Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Heavy Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Liverpool Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Manchester Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Motown Revisited Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Neo Soul Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Portland Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Retro Rock Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Roots Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Scientific Method Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Slow Jam Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Smash Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/SoCal Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Speakeasy Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Drum Kit Designer/Sunset Kit v1.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/Bass/Muted Electric Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Claps/Stereo",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Cowbell/Stereo",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Blue Ridge Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Bluebird Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Brooklyn Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Detroit Garage Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/East Bay Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Four on the Floor Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Heavy Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Liverpool Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Manchester Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Motown Revisited Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Neo Soul Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Portland Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Retro Rock Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Roots Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Scientific Method Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Slow Jam Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Smash Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/SoCal Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Speakeasy Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Sunset Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Shaker/Stereo",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Blue Ridge Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Bluebird Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Brooklyn Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Detroit Garage Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/East Bay Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Four on the Floor Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Heavy Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Liverpool Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Manchester Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Motown Revisited Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Neo Soul Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Portland Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Retro Rock Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Roots Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Scientific Method Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Slow Jam Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Smash Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/SoCal Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Speakeasy Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Sunset Kit",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Sticks/Stereo",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer Tambourine/Stereo",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Internal/Drum Kit Designer/Drum Kit Designer/Stereo",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Bass/Fingerstyle Electric Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Bass/Fretless Electric Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Bass/Latin Baby Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Bass/Liverpool Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Bass/Liverpool.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Bass/P-Bass iOS small.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Bass/Palm Muted Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Bass/Picked Rock Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Bass/Prog Rock Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Bass/Stinger Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Bass/Subby Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Bass/Thumbstroke Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Bass/Upright Ballad Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Bass/Upright Jazz Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Brass & Woodwinds/Bassoon iOS KB.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Brass & Woodwinds/Brass Ensemble iOS KB.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Brass & Woodwinds/Clarinet iOS KB.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Brass & Woodwinds/Flute iOS KB.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Brass & Woodwinds/French Horn iOS KB.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Brass & Woodwinds/Oboe iOS KB.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Acoustic Drums/Basic Classic Studio Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Acoustic Drums/Basic Live Rock Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Acoustic Drums/Basic Vintage Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Acoustic Drums/Classic Studio Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Acoustic Drums/Live Rock Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Acoustic Drums/Vintage Kit.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Electronic Drums/Basic Classic Drum Machine.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Electronic Drums/Basic Hip Hop Drum Machine.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Electronic Drums/Basic House Drum Machine.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Electronic Drums/Classic Drum Machine.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Electronic Drums/Hip Hop Drum Machine.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Electronic Drums/House Drum Machine.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Kitpieces/Metronome HiHat 2.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Kitpieces/Metronome Sidestick 2.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Drums & Percussion/Kitpieces/Metronome Woodblock 2.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Guitar/Acoustic Guitar KB.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Guitar/Acoustic Harmonics.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Guitar/Steel String Acoustic.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Guitar/Vintage Strat KB.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Guitar/Warm Electric KB.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Guitar/Warm Electric.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Keyboard/Acoustic Piano/Classical Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Keyboard/Acoustic Piano/Steinway Grand Piano 2.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Keyboard/Acoustic Piano/Yamaha Grand Piano.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Mallet/Glass Marimba Hard Mallet.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Mallet/Glass Marimba Muted.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Mallet/Glass Marimba Soft Mallet.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Mallet/Glockenspiel.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Strings/Cello.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Strings/Double Bass.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Strings/Hollywood Strings.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Strings/Strings Pizzicato iOS KB.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Strings/Strings Staccato iOS KB.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Strings/Strings Sustain iOS KB.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Strings/Strings.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Strings/Upright iOS small.exs",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Textures/Drones",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Textures/FX",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Sampler/z_Legacy/Textures/Pads",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Adept Machine.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Boutique 78.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Boutique 808.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Boutique 909.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Boutique SP12.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Classic UK Hip Hop.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Drag & Drop Samples.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Dub Smash.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Electro Bump.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Empty Kit.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Epic Electro.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Fizzy Beats.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Grimy 909.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Gritty Funk.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Hit Machine.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Indie Disco.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Italo Disco.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/LoFi Glitch.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Low Down Dub.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Major Crush.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Massive Beat.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Minimal Glitch.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Minimalistic.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Modern Club.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Modern Machines.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Retro Machines.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Steely Beats.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Synth Box.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Techno 808.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Unreal Acoustic.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Vintage Machines.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/01 Drum Kits/Vox Box.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/02 Drum Banks/Effects Bank.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/02 Drum Banks/HiHat Bank.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/02 Drum Banks/Kick Bank.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/02 Drum Banks/Percussion Bank.pst",
    "~/Music/Logic Pro Library.bundle/Plug-In Settings/Ultrabeat/02 Drum Banks/Snare Bank.pst",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/05 Multi-Track Stereo Production.logicx/Alternatives/000/DisplayState.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/05 Multi-Track Stereo Production.logicx/Alternatives/000/DisplayStateArchive",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/05 Multi-Track Stereo Production.logicx/Alternatives/000/MetaData.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/05 Multi-Track Stereo Production.logicx/Alternatives/000/ProjectData",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/05 Multi-Track Stereo Production.logicx/Contents/PkgInfo",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/05 Multi-Track Stereo Production.logicx/Contents/Resources/en.lproj/InfoPlist.strings",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/05 Multi-Track Stereo Production.logicx/Contents/Resources/template.tif",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/05 Multi-Track Stereo Production.logicx/Resources/com.apple.musicapps.tags.plist",
    "~/Music/Logic Pro Library.bundle/Projects/Templates/05 Multi-Track Stereo Production.logicx/Resources/ProjectInformation.plist",
    "~/Music/Logic Pro Library.bundle/Samples/Bass/Muted Electric Bass_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Blue Ridge Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Bluebird Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Brooklyn Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Detroit Garage Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/East Bay Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Four on the Floor Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Heavy Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Liverpool Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Manchester Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Motown Revisited Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Neo Soul Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Portland Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Retro Rock Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Roots Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Scientific Method Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Slow Jam Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Smash Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/SoCal Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Speakeasy Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Kick/Stereo/Sunset Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Blue Ridge Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Bluebird Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Brooklyn Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Detroit Garage Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/East Bay Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Four on the Floor Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Heavy Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Liverpool Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Manchester Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Motown Revisited Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Neo Soul Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Portland Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Retro Rock Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Roots Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Scientific Method Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Slow Jam Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Smash Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/SoCal Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Speakeasy Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Drum Kit Designer Snare/Stereo/Sunset Kit",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v1 Claps_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v1 Cowbell_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v1 Shaker_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v1 Sticks_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v1 Tambourine_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v2 Claps_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v2 Shaker_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v2 Tambourine_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v3 Claps_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v3 Shaker_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v3 Tambourine_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/AP v4 Tambourine_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Blue Ridge Kit_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Bluebird Kit Crash_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Bluebird Kit HiHat_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Bluebird Kit Kick_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Bluebird Kit Ride_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Bluebird Kit Snare_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Bluebird Kit Toms_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Brooklyn Kit Crash_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Brooklyn Kit HiHat_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Brooklyn Kit Kick_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Brooklyn Kit Ride_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Brooklyn Kit Snare_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Brooklyn Kit Toms_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Detroit Garage Kit Crash_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Detroit Garage Kit HiHat_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Detroit Garage Kit Kick_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Detroit Garage Kit Ride_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Detroit Garage Kit Snare_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Detroit Garage Kit Toms_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/East Bay Kit Crash_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/East Bay Kit HiHat_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/East Bay Kit Kick_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/East Bay Kit Ride_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/East Bay Kit Snare_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/East Bay Kit Toms_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Four on the Floor Kit Crash_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Four on the Floor Kit HiHat_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Four on the Floor Kit Kick_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Four on the Floor Kit Ride_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Four on the Floor Kit Snare_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Four on the Floor Kit Toms_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Heavy Kit Crash_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Heavy Kit HiHat_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Heavy Kit Kick_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Heavy Kit Ride_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Heavy Kit Snare_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Heavy Kit Toms_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Liverpool Kit Crash_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Liverpool Kit HiHat_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Liverpool Kit Kick_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Liverpool Kit Ride_consolidated.caf",
    "~/Music/Logic Pro Library.bundle/Samples/Drums & Percussion/Acoustic Drums/Drum Kit Designer/Stereo v1/Liverpool Kit Snare_consolidated.caf",
  ]
end
