cask "font-misans-l3" do
  version "1.000"
  sha256 "467fe0171ec9ea21d925aba9c032b1a775a3e756c458f075e7a2ee57568b0c79"

  url "https://hyperos.mi.com/font-download/MiSans_L3.zip"
  name "MiSans L3"
  homepage "https://hyperos.mi.com/font/en/rare-word/"

  font "MiSans L3/MiSans L3.ttf", target: "MiSansL3.ttf"

  caveats do
    <<~EOS
      # Generated by `otfinfo`
      Family:              MiSans L3
      Subfamily:           Regular
      Full name:           MiSans L3
      PostScript name:     MiSans-L3
      Version:             Version 1.000
      Unique ID:           1.000;HNYI;MiSans L3
      Designer:            Beijing Xiaomi Mobile Software Co.,Ltd & Hanyi Fonts
      Manufacturer:        Hanyi Fonts
      Copyright:           Copyright (c)  2020-2023  Beijing Xiaomi Mobile Software Co.,Ltd. All Rights Reserved.
      Vendor ID:           HNYI
      Permissions:         Editable
    EOS
  end
end
