cask "font-misans-tibetan" do
  version "1.600"
  sha256 :no_check

  url "https://hyperos.mi.com/font-download/MiSans_Tibetan.zip"
  name "MiSans Tibetan VF"
  homepage "https://hyperos.mi.com/font/en/details/tibetan/"

  # if sha256 == "168fc3be3c6ec9fe53550da63201691c99f329402c6fb85cf8aa4adbc14b964d"
  #   font "MiSans Tibetan/可变字体/MiSansTibetanVF.ttf"
  # elsif sha256 == "96ae675ee6b594daffc3bc6bef9a415d6516e70abefe25ed6d5988dfcd64d5eb"
  #   font "MiSans Tibetan/MiSansTibetanVF.ttf"
  # end

  font "MiSans Tibetan/MiSansTibetanVF.ttf", target: "MiSansTibetan[wght].ttf"

  preflight do
    if Dir.exist?("#{staged_path}/MiSans Tibetan/可变字体")
      FileUtils.mv("#{staged_path}/MiSans Tibetan/可变字体/MiSansTibetanVF.ttf",
                   "#{staged_path}/MiSans Tibetan/MiSansTibetanVF.ttf")
    end
  end

  caveats do
    <<~EOS
      # Generated by `otfinfo`
      Family:                 MiSans Tibetan VF
      Subfamily:              Regular
      Full name:              MiSans Tibetan VF
      PostScript name:        MiSansTibetanVF
      Version:                Version 1.600
      Unique ID:              1.600;HNYI;MiSans Tibetan VF
      Designer:               Beijing Xiaomi Mobile Software Co.,Ltd & Hanyi Fonts
      Manufacturer:           Hanyi Fonts
      Copyright:              Copyright © 2023-2024 Beijing Xiaomi Mobile Software Co.,Ltd. All Rights Reserved.
      Vendor ID:              HNYI
      Permissions:            Editable
      Axis 0:                 wght
      Axis 0 name:            Weight
      Axis 0 range:           150 700
      Axis 0 default:         330
      Instance 0 name:        Thin
      Instance 0 position:    150
      Instance 1 name:        ExtraLight
      Instance 1 position:    200
      Instance 2 name:        Light
      Instance 2 position:    250
      Instance 3 name:        Normal
      Instance 3 position:    305
      Instance 4 name:        Regular
      Instance 4 position:    330
      Instance 5 name:        Medium
      Instance 5 position:    380
      Instance 6 name:        Demibold
      Instance 6 position:    450
      Instance 7 name:        Semibold
      Instance 7 position:    520
      Instance 8 name:        Bold
      Instance 8 position:    630
      Instance 9 name:        Heavy
      Instance 9 position:    700
    EOS
  end
end
