cask "font-misans-gurmukhi" do
  version "1.000"
  sha256 "54bcc86185ca2cda83f05128dd06e23eb1826dfc1b1ca6f65258c13344ba54a2"

  url "https://hyperos.mi.com/font-download/MiSans_Gurmukhi.zip"
  name "MiSans Gurmukhi VF"
  homepage "https://hyperos.mi.com/font/en/details/gurmukhi/"

  font "MiSans Gurmukhi/MiSans Gurmukhi VF.ttf", target: "MiSansGurmukhi[wght].ttf"

  caveats do
    <<~EOS
      # Generated by `otfinfo`
      Family:                 MiSans Gurmukhi VF
      Subfamily:              Regular
      Full name:              MiSans Gurmukhi VF
      PostScript name:        MiSansGurmukhiVF
      Version:                Version 1.000
      Unique ID:              Monotype Imaging Inc.:MiSans Gurmukhi VF:2023
      Manufacturer:           Monotype Imaging Inc.
      Vendor URL:             http://www.monotype.com/
      Copyright:              Copyright © Beijing Xiaomi Mobile Software Co.,Ltd. All Rights Reserved.
      Vendor ID:              MONO
      Permissions:            Editable
      Axis 0:                 wght
      Axis 0 name:            Weight
      Axis 0 range:           150 700
      Axis 0 default:         330
      Instance 0 name:        Thin
      Instance 0 position:    150
      Instance 1 name:        ExtraLight
      Instance 1 position:    200
      Instance 2 name:        Light
      Instance 2 position:    250
      Instance 3 name:        Normal
      Instance 3 position:    305
      Instance 4 name:        Regular
      Instance 4 position:    330
      Instance 5 name:        Medium
      Instance 5 position:    380
      Instance 6 name:        Demibold
      Instance 6 position:    450
      Instance 7 name:        Semibold
      Instance 7 position:    520
      Instance 8 name:        Bold
      Instance 8 position:    630
      Instance 9 name:        Heavy
      Instance 9 position:    700
    EOS
  end
end
