cask "font-misans-tc" do
  version "4.009"
  sha256 :no_check

  url "https://hyperos.mi.com/font-download/MiSans_TC.zip"
  name "MiSans TC VF"
  homepage "https://hyperos.mi.com/font/en/details/tc/"

  # if sha256 == "e4d17f5af09e3f5194c816ba592d0990d8b377248a896f04657c967d9f4d53f3"
  #   font "MiSans TC/Misans TC VF.ttf"
  # elsif sha256 == "417831f033601f1738fefb2ce9158586d0143385a9dd0c4cfa985bcc16c7443b"
  #   font "MiSans TC/可变字体/MisansTC VF.ttf"
  # end

  font "MiSans TC/Misans TC VF.ttf", target: "MiSansTC[wght].ttf"

  preflight do
    if Dir.exist?("#{staged_path}/MiSans TC/可变字体")
      FileUtils.mv("#{staged_path}/MiSans TC/可变字体/MisansTC VF.ttf",
                   "#{staged_path}/MiSans TC/Misans TC VF.ttf")
    end
  end

  caveats do
    <<~EOS
      # Generated by `otfinfo`
      Family:                 Misans TC VF
      Subfamily:              Regular
      Full name:              Misans TC VF
      PostScript name:        MisansTCVF
      Version:                Version 4.009
      Unique ID:              4.009;HNYI;Misans TC VF
      Designer:               Beijing Xiaomi Mobile Software Co.,Ltd & Hanyi Fonts
      Manufacturer:           Hanyi Fonts
      Vendor URL:             https://www.hanyi.com.cn/
      Copyright:              Copyright © 2020-2025 Beijing Xiaomi Mobile Software Co.,Ltd. All Rights Reserved.
      Vendor ID:              HNYI
      Permissions:            Editable
      Axis 0:                 wght
      Axis 0 name:            Weight
      Axis 0 range:           150 700
      Axis 0 default:         330
      Instance 0 name:        Thin
      Instance 0 position:    150
      Instance 1 name:        ExtraLight
      Instance 1 position:    200
      Instance 2 name:        Light
      Instance 2 position:    250
      Instance 3 name:        Normal
      Instance 3 position:    305
      Instance 4 name:        Regular
      Instance 4 position:    330
      Instance 5 name:        Medium
      Instance 5 position:    380
      Instance 6 name:        Demibold
      Instance 6 position:    450
      Instance 7 name:        Semibold
      Instance 7 position:    520
      Instance 8 name:        Bold
      Instance 8 position:    630
      Instance 9 name:        Heavy
      Instance 9 position:    700
    EOS
  end
end
