cask "font-misans-khmer" do
  version "1.200"
  sha256 :no_check

  url "https://hyperos.mi.com/font-download/MiSans_Khmer.zip"
  name "MiSans Khmer VF"
  homepage "https://hyperos.mi.com/font/en/details/khmer/"

  # if sha256 == "ebd601b77f64f054ee1107f9fa0022f57284ae6e2c3342c924893b324cf96c60"
  #   font "MiSans Khmer/可变字体/MiSansKhmerVF.ttf"
  # elsif sha256 == "5369e44d4ea4696a8245504cda592320486eec276403857fff63985239420306"
  #   font "MiSans Khmer/MiSansKhmerVF.ttf"
  # end

  font "MiSans Khmer/MiSansKhmerVF.ttf", target: "MiSansKhmer[wght].ttf"

  preflight do
    if Dir.exist?("#{staged_path}/MiSans Khmer/可变字体")
      FileUtils.mv("#{staged_path}/MiSans Khmer/可变字体/MiSansKhmerVF.ttf",
                   "#{staged_path}/MiSans Khmer/MiSansKhmerVF.ttf")
    end
  end

  caveats do
    <<~EOS
      # Generated by `otfinfo`
      Family:                 MiSans Khmer VF
      Subfamily:              Regular
      Full name:              MiSans Khmer VF
      PostScript name:        MiSansKhmerVF-Regular
      Preferred family:       MiSans Khmer VF
      Preferred subfamily:    Regular
      Version:                Version 1.200
      Unique ID:              1.200;HNYI;MiSansKhmerVF-Regular
      Designer:               Beijing Xiaomi Mobile Software Co.,Ltd & Hanyi Fonts & Anagata Design
      Manufacturer:           Hanyi Fonts
      Vendor URL:             https://www.hanyi.com.cn/
      Copyright:              Copyright © 2023-2024  Beijing Xiaomi Mobile Software Co.,Ltd. All Rights Reserved.
      Sample text:            ពុម្ពអក្សរសម្រាប់ភាសាខ្មែរ
      Vendor ID:              HNYI
      Permissions:            Editable
      Axis 0:                 wght
      Axis 0 name:            Weight
      Axis 0 range:           150 700
      Axis 0 default:         330
      Instance 0 name:        Thin
      Instance 0 position:    150
      Instance 1 name:        ExtraLight
      Instance 1 position:    200
      Instance 2 name:        Light
      Instance 2 position:    250
      Instance 3 name:        Normal
      Instance 3 position:    305
      Instance 4 name:        Regular
      Instance 4 position:    330
      Instance 5 name:        Medium
      Instance 5 position:    380
      Instance 6 name:        Demibold
      Instance 6 position:    450
      Instance 7 name:        Semibold
      Instance 7 position:    520
      Instance 8 name:        Bold
      Instance 8 position:    630
      Instance 9 name:        Heavy
      Instance 9 position:    700
    EOS
  end
end
