cask "font-misans-latin" do
  version "4.007"
  sha256 :no_check

  url "https://hyperos.mi.com/font-download/MiSans_Latin.zip"
  name "MiSans Latin VF"
  homepage "https://hyperos.mi.com/font/en/details/latin/"

  # if sha256 == "d24091ccd409a4152ffcc12cd659c16df9cdcdb4c702d8ae355b321e711f0004"
  #   font "MiSans Latin/可变字体/MiSansLatinVF.ttf"
  # elsif sha256 == "501235d00ecd18b8e1f2fe972c96c4e30e0c073f3298d533094d3b653345a245"
  #   font "MiSans Latin/MiSans Latin VF.ttf"
  # end

  font "MiSans Latin/MiSans Latin VF.ttf", target: "MiSansLatin[wght].ttf"

  preflight do
    if Dir.exist?("#{staged_path}/MiSans Latin/可变字体")
      FileUtils.mv("#{staged_path}/MiSans Latin/可变字体/MiSansLatinVF.ttf",
                   "#{staged_path}/MiSans Latin/MiSans Latin VF.ttf")
    end
  end

  caveats do
    <<~EOS
      # Generated by `otfinfo`
      Family:                 MiSans Latin VF
      Subfamily:              Regular
      Full name:              MiSans Latin VF
      PostScript name:        MiSansLatinVF
      Version:                Version 4.007
      Unique ID:              4.007;HNYI;MiSans Latin VF
      Manufacturer:           Hanyi Fonts
      Vendor URL:             https://www.hanyi.com.cn/
      Copyright:              Copyright © 2020-2024 Beijing Xiaomi Mobile Software Co.,Ltd. All Rights Reserved.
      Vendor ID:              HNYI
      Permissions:            Editable
      Axis 0:                 wght
      Axis 0 name:            Weight
      Axis 0 range:           150 700
      Axis 0 default:         330
      Instance 0 name:        Thin
      Instance 0 position:    150
      Instance 1 name:        ExtraLight
      Instance 1 position:    200
      Instance 2 name:        Light
      Instance 2 position:    250
      Instance 3 name:        Normal
      Instance 3 position:    305
      Instance 4 name:        Regular
      Instance 4 position:    330
      Instance 5 name:        Medium
      Instance 5 position:    380
      Instance 6 name:        Demibold
      Instance 6 position:    450
      Instance 7 name:        Semibold
      Instance 7 position:    520
      Instance 8 name:        Bold
      Instance 8 position:    630
      Instance 9 name:        Heavy
      Instance 9 position:    700
    EOS
  end
end
