cask "font-misans-thai" do
  version "1.003"
  sha256 "84ab9b312a0abe8505cb00aedfe040b5eac4d7ae19a9ff3e9a422f58a13250ee"

  url "https://hyperos.mi.com/font-download/MiSans_Thai.zip"
  name "MiSans Thai VF"
  homepage "https://hyperos.mi.com/font/en/details/thai/"

  font "MiSans Thai/可变字体/MiSans Thai VF.ttf", target: "MiSansThai[wght].ttf"

  caveats do
    <<~EOS
      # Generated by `otfinfo`
      Family:                 MiSans Thai VF
      Subfamily:              Regular
      Full name:              MiSans Thai VF
      PostScript name:        MiSansThaiVF
      Version:                Version 1.003
      Unique ID:              Monotype Imaging Inc.:MiSans Thai VF:2024
      Manufacturer:           Monotype Imaging Inc.
      Vendor URL:             http://www.monotype.com
      Copyright:              Copyright © Beijing Xiaomi Mobile Software Co.,Ltd. All Rights Reserved.
      Vendor ID:              MONO
      Permissions:            Editable
      Axis 0:                 wght
      Axis 0 name:            Weight
      Axis 0 range:           150 700
      Axis 0 default:         330
      Instance 0 name:        Thin
      Instance 0 position:    150
      Instance 1 name:        ExtraLight
      Instance 1 position:    200
      Instance 2 name:        Light
      Instance 2 position:    250
      Instance 3 name:        Normal
      Instance 3 position:    305
      Instance 4 name:        Regular
      Instance 4 position:    330
      Instance 5 name:        Medium
      Instance 5 position:    380
      Instance 6 name:        Demibold
      Instance 6 position:    450
      Instance 7 name:        Semibold
      Instance 7 position:    520
      Instance 8 name:        Bold
      Instance 8 position:    630
      Instance 9 name:        Heavy
      Instance 9 position:    700
    EOS
  end
end
